### ISSUE TITLE
Add support for non-US versions

### ISSUE THREAD

**Issue by NiceneNerd** [NiceneNerd/BCML#1]
Right now the reference RSTB and the hash table only contain entries for the USen version of BOTW. For BCML to work fully with other versions, files specific to them must be added.

**Comment by KarinMiku** [comment]
Any news on this? :c i want to create a video tutorial (in spanish) of your tool so ppl who use my linkle dialogue edit can use it with their mods but i cant cuz BCML cant detect the Bootup_USes yet

**Comment by KarinMiku** [comment]
@NiceneNerd 
Any news on this? :c i want to create a video tutorial (in spanish) of your tool so ppl who use my linkle dialogue edit can use it with their mods but i cant cuz BCML cant detect the Bootup_USes yet

**Comment by NiceneNerd** [comment]
Should be finished as of 2.0.
