### ISSUE TITLE
dependecy syaz0 does not build in 3.9

### ISSUE THREAD

**Issue by OnikenX** [NiceneNerd/BCML#100]
### dependecy syaz0 does not build in 3.9

it is now deprecated and does not let me create an issue

### installing inside a pyenv with python 3.8 works but running does not:

```[pywebview] QT cannot be loaded```

ive been trying to install in many ways but none are working.

OS: Archlinux x64

**Comment by NiceneNerd** [comment]
Not sure if I can do anything about syaz0 yet, but did you try installing 
`pyqtwebengine` with 3.8? I use 3.8 myself.

**Comment by OnikenX** [comment]
it worked, thanks very much
