### ISSUE TITLE
bcml_3_setup.exe Installer Issue

### ISSUE THREAD

**Issue by zac642008** [NiceneNerd/BCML#105]
The installer crashes when attempting to extract python.

**Comment by NiceneNerd** [comment]
Did you run it more than once? Try deleting `%USERPROFILE%\.python` and trying again.

**Comment by NiceneNerd** [comment]
Otherwise you'll need to catch the error, maybe by screen recording or something

**Comment by zac642008** [comment]
I'll be damned, worked like a charm
cheers m8
