### ISSUE TITLE
New installer bugs

### ISSUE THREAD

**Issue by AeliusSaionji** [NiceneNerd/BCML#106]
Windows defender ate the installer mid install, and attempting to rerun it fails with:
```
Checking for Python...
Looks like you need Python! Downloading Python 3.7.9...
Downloaded Python. Extracting...
ERROR: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Failed to create file 'C:\Users\aelius\.python\python.exe' while expanding the archive file 'C:\Users\aelius\AppData\Local\Temp\python.zip' contents as the file 'C:\Users\aelius\.python\python.exe' already exists. Use the -Force parameter if you want to overwrite the existing directory 'C:\Users\aelius\.python\python.exe' contents when expanding the archive file.
```

More accurately, this happens anytime you rerun the installer even without Windows Defender meddling.

After deleting the .python folder and starting again, I get this:

```
ERROR: Could not find a part of the path 'C:\Users\aelius\Desktop\BCML.lnk'.
```
Probably because I have Onedrive managing my desktop. I wouldn't want a desktop shortcut tho :)

Manually created a Desktop folder, deleted .python, and now it works! But the start menu shortcuts from previous install still exists, which might confuse other users.

Final note- maybe consider putting python in appdata\local?

Thanks!

**Comment by NiceneNerd** [comment]
Should all be fixed now 0e014c3e3b876f4377fa2e60ea57c46b53395c23
