### ISSUE TITLE
New Uninstaller bugs

### ISSUE THREAD

**Issue by cdhn6469** [NiceneNerd/BCML#107]
the uninstaller window will only open for a millisecond and close , and i just type "Set-ExecutionPolicy RemoteSigned" in windows power shell to fix it
![is](https://user-images.githubusercontent.com/28061010/103614392-72202d00-4f63-11eb-9dc9-be34e5648ac7.png)
(chinese system language)

**Comment by NiceneNerd** [comment]
I'm not sure if I can do anything about that, except maybe make a note in the docs.

**Comment by NiceneNerd** [comment]
Fixed with the new release.
