### ISSUE TITLE
windows security detected trojan

### ISSUE THREAD

**Issue by crystalBee98** [NiceneNerd/BCML#108]
<img width="407" alt="Screenshot 2021-01-05 075818" src="https://user-images.githubusercontent.com/76993199/103620693-da531c80-4f2b-11eb-9774-0694f9c0ab0d.png">

If you cant open that its simply a screenshot of windows security when I tried to install the new release. Its came up as a severe threat and trojan the details given are below:
"This program is dangerous and executes commands from an attacker."

**Comment by NiceneNerd** [comment]
The source code is in this repo, you can see for yourself it's fine. Feel free to submit a report to Microsoft that it's a false positive. Unfortunately, lots of executables built using ps2exe get flagged, because some time ago some malware made with ps2exe made a big run around.
