### ISSUE TITLE
New installer BCML cant install some mods

### ISSUE THREAD

**Issue by Uranite** [NiceneNerd/BCML#109]
Here is some mods new installer bcml cant install:
https://gamebanana.com/gamefiles/13593
https://gamebanana.com/skins/174566
When looking at task manager, bcml only uses about 10% CPU, about 5% GPU, and no Disk usage at all (0 MB/s)

I can install these mods when i downgrade to [v3.2.3](https://github.com/NiceneNerd/BCML/releases/tag/v3.2.3)

**Comment by NiceneNerd** [comment]
The new installer has nothing to do with it. I happened to edit the way BCML peeks into mods for certain meta information, but I didn't realize this would actually break compatibility with BNPs made using 2.x.  (Though I have no idea why a mod as new as girly animations would be a 2.x BNP.) I've made a fix which will be in the next release; in the meantime you can download the mod(s) manually, change the extension to `.zip`, and it will work.

**Comment by Uranite** [comment]
> The new installer has nothing to do with it. I happened to edit the way BCML peeks into mods for certain meta information, but I didn't realize this would actually break compatibility with BNPs made using 2.x. (Though I have no idea why a mod as new as girly animations would be a 2.x BNP.) I've made a fix which will be in the next release; in the meantime you can download the mod(s) manually, change the extension to `.zip`, and it will work.

Okay, thanks for the fast reply!

**Comment by NiceneNerd** [comment]
Fixed with the new release.
