### ISSUE TITLE
CI triggers mail notification multiple times

### ISSUE THREAD

**Issue by Lucide** [NiceneNerd/BCML#110]
Hi, I'm watching the repo for new releases. In the last weeks I've been receiving 2-3 mail notifications per release, pointing to different commits. Perhaps something wrong in the CI pipeline?

![image](https://user-images.githubusercontent.com/33134209/103915187-2d36fa80-510b-11eb-90be-5c32d3ffa6ed.png)

**Comment by NiceneNerd** [comment]
The CI setup should be fine; this was caused by a vicious battle between myself and a new GitHub action workflow.

**Comment by Lucide** [comment]
Ahh understandable. Alright, I'm gonna close the issue right here.
Keep it up! 👍
