### ISSUE TITLE
Problems with updating to / installing 3.3.1

### ISSUE THREAD

**Issue by LNBZero** [NiceneNerd/BCML#111]
Hello again NicineNerd,

Thanks again for helping with the issue recently with the persistent update notification while there not being one.

Though right now there seems to be a big update, apparently even mandatory for several new mod updates. I've tried updating through BMCL itself but after it claims to have updated and needs a restart it won't restart. Restarting it manually I notice it didn't update at all and the version is still 3.2.0. I figured I could just download the new installer and overwrite the current installation but that is what this issue is about:

First time I ran it it would get just close while downloading some bundle. Second time it would download fine (I assume) but when putting my directory and hitting enter it would instantly close. I've also tried the default directory, which I rather not seeing my C drive is a fairly small SSD not used for game related files, but no avail there either.

I've tried to run the installed as Administrator as well but again it simply closes at the directory step.

Many thanks in advance for any help!

**Comment by NiceneNerd** [comment]
Fixed with the new release.

**Comment by LNBZero** [comment]
Ok, many thanks again! Though I see no installer version and only the zip to compile. Am I misunderstanding or should I have some more patience for the installer download?

**Comment by NiceneNerd** [comment]
Per the readme, the new ZIP has `setup.exe` inside. Extract the ZIP where you please and run the setup.

**Comment by LNBZero** [comment]
Many thanks again! It works!

I've not seen the changes on the front page and I went straight to the releases page. My apologies! Sorry to have wasted your time.
