### ISSUE TITLE
bcml uninstall shortcut doesnt show in start menu but still exist and works

### ISSUE THREAD

**Issue by Uranite** [NiceneNerd/BCML#112]
bcml uninstall shortcut doesnt show in start menu but still exist and works
![image](https://user-images.githubusercontent.com/62639703/104085506-9d1bc100-5282-11eb-9933-09d02d942100.png)

**Comment by NiceneNerd** [comment]
So where is it?

**Comment by Uranite** [comment]
> So where is it?

no i mean the shortcut is still there at AppData\Roaming\Microsoft\Windows\Start Menu\Programs\BCML but it doesnt show on the start menu
![IMG_20210110_012110028](https://user-images.githubusercontent.com/62639703/104105698-7db48080-52e2-11eb-84c3-68a64519ef2f.jpg)

**Comment by Uranite** [comment]
oh the uninstaller shows at bcml folder at start menu, it just doesnt show at recently added
