### ISSUE TITLE
Several content folders from mods failing to merge

### ISSUE THREAD

**Issue by Jaitsu** [NiceneNerd/BCML#113]
Just started using BCML, version 3.3.2.

Installed a few mods, including [this Fierce Deity armor reskin](https://gamebanana.com/skins/162218) and Second Wind. Both contain several folders under content, but in my merged (9999_BCML) folder, only Actor, Event, Map, Pack, and System under content, and Map and Pack under aoc/0010, seem to have carried over. As such, the Fierce Deity armor mod is only affecting the inventory thumbnail rather than the armor itself - and I haven't progressed far enough to see if things from Second Wind are missing. I didn't see any errors during installation, and the rstb.log in the Fierce Deity mod lists the Model folder files, although they aren't actually merged.

Please let me know if there's any further info or logs that would be helpful.

**Comment by NiceneNerd** [comment]
The 9999_BCML folder isn't supposed to contain all of the content, only the stuff which actually was produced by one of the mergers. If you're using Cemu, the merge that includes all of the content will be automatically placed in your graphic packs. If you're not using Cemu, the Export button generates a ZIP with the whole pack.
