### ISSUE TITLE
Windows Security blocking & quarantining BCML 3.3.2's setup.exe - labelled as "Severe" threat?

### ISSUE THREAD

**Issue by floral-qua-floral** [NiceneNerd/BCML#114]
Just attempted to update to BCML 3.3.2. I believe prior to this I was running 3.2.3, so I decided to uninstall the old version prior to installing the new one, as suggested in 3.3.0's changelog.

After unzipping the contents of the bundled zip, I was able to run the setup.exe file to completion without interruption. However after I closed the dialogue that said it was finished, Windows Security immediately reported that it had found threats. Checking the log says that it detects BCML's setup.exe as a "Severe" threat, and has quarantined & blocked it. The installer did create the Start menu shortcuts that I had directed it to, however they don't seem to do anything - I'm not able to open the app.

Here are the two relevant entries in the Windows Security log:
![image](https://user-images.githubusercontent.com/49110090/104102948-85860d80-526d-11eb-8325-3b0f4c249c41.png)

**Comment by NiceneNerd** [comment]
I don't know where it could come up with that thread; the source for the installer is available at https://github.com/NiceneNerd/bcml-installer, and you can easily verify that building it matches the exe in the download. As for the shortcut not working, what happens if you run from the command prompt `C:\Games\BCML 3.3.2\python.exe -m bcml`?

**Comment by NiceneNerd** [comment]
I've cleared one build of the installer as a false positive with Microsoft, so it _should_ be fine from here on out. Also, I fixed the most common cause of the new BCML shortcut not launching in the latest release bundle, so all should be well now.
