### ISSUE TITLE
Can't complete initial setup linux

### ISSUE THREAD

**Issue by NekoNoor** [NiceneNerd/BCML#115]
I installed bcml 3.3.2 through pip on arch linux and i can't finish the initial setup. i also have to click every button several times for it to register.

I can't seem to record properly right now but i'm clicking on the floppy disk icon in the last page of the initial setup and i can't finish it

This message shows up in the logs a bunch of times if i run it from the terminal
```
[pywebview] Error occurred while evaluating function dir_exists
Traceback (most recent call last):
  File "/home/nekonoor/.local/lib/python3.9/site-packages/webviewb/util.py", line 175, in js_bridge_call
    func_params = param if not param else json.loads(param)
  File "/usr/lib/python3.9/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not dict
```

**Comment by NiceneNerd** [comment]
It's probably using the GTK webview, which seems to be very picky and buggy on some systems. Install pyqtwebengine instead.

**Comment by NekoNoor** [comment]
thank you that works
