### ISSUE TITLE
BCML Not Launching

### ISSUE THREAD

**Issue by Nepezi** [NiceneNerd/BCML#116]
I followed instructions exactly as written on GameBanana using the Windows installer, went through setup, created the shortcuts. But when I try to open the shortcuts (tried both start menu and desktop) nothing happens. Try to run the file they point to, nothing happens. 

I'll have Task Manager open and *sometimes* a Python process will run, but it won't do anything, and if it weren't for the process appearing in the list, there would be no indication anything had even been opened. I've tried waiting a few minutes to see if it loads up, I've tried uninstalling and reinstalling, I've tried redownloading and reinstalling, I've even restarted my computer. No change.

Windows 10, confirmed it's allowed through firewall, tried running as admin, please help

**Comment by Nepezi** [comment]
Followed a thread in the comments on GameBanana, program opening but damn those are some hoops to jump through

**Comment by NiceneNerd** [comment]
Fortunately I have a new build of the installer with a workaround.
