### ISSUE TITLE
No info how to install mods to switch on the manual/guide/readme

### ISSUE THREAD

**Issue by orangpelupa** [NiceneNerd/BCML#125]
after installing mods, the mods is not installed into atmosphere\contents\01007EF00011E000\romfs

but installed into %appdata%\Local\bcml\mods_nx\9999_BCML\01007EF00011E000\romfs instead

no info how to install it to switch microsd card.

**Comment by NiceneNerd** [comment]
This is explained in the in-app help.

**Comment by orangpelupa** [comment]
may i have a direction, where in the in-app help file is it? i only found the help file only says to click "install" to install the mods

**Comment by NiceneNerd** [comment]
Exporting for Console
