### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by Heliodore24** [NiceneNerd/BCML#126]
Can't install the last version, keep having this error :
![image](https://user-images.githubusercontent.com/53257868/107892529-077cec80-6f26-11eb-92cc-9a8cd2336a18.png)

**Comment by NiceneNerd** [comment]
I don't know that language

**Comment by Heliodore24** [comment]
"impossible to save the shortcut" if that what you don't understand

**Comment by NiceneNerd** [comment]
Hmm, it doesn't explain why, so that makes it hard to guess. Does it work if you just do the desktop shortcut?

**Comment by Heliodore24** [comment]
When I do it with just the desktop shortcut, I have the same error

**Comment by NiceneNerd** [comment]
I have no idea, I'm afraid. Windows does not here provide a useful error message in the slightest.

**Comment by Heliodore24** [comment]
At least, you've tried. Thanks.
