### ISSUE TITLE
BCML Not Syncing with GameBanana 

### ISSUE THREAD

**Issue by kputschko** [NiceneNerd/BCML#127]
My BCML is having trouble syncing with GameBanana.  It just spins while syncing forever.  I am still able to manually load and install BNP files I download from the site.  Any recommendations on fixing the sync?  Can I uninstall/reinstall while keeping my mod setup intact?

**Comment by NiceneNerd** [comment]
Has it ever synced before? The first sync could take a fairly long time.

**Comment by kputschko** [comment]
Yeah it was syncing in the past. I had updated to the latest version last week, and it was even syncing after the update.  The latest version was released on Feb 8, and I had it working properly until this past weekend, Feb 14 or so.

**Comment by NiceneNerd** [comment]
Where is BCML installed (full path preferably)?

**Comment by kputschko** [comment]
I appreciate your responses!  I have it in the downloads folder
(C:/Users/.../Downloads/bcml-win64-bundle_b2b19).

**Comment by NiceneNerd** [comment]
In that case run `C:\Users\xxx\Downloads\bcml-win64-bundle_b2b19\python.exe -m bcml bcml-debug` in the Command Prompt, then try to sync GameBanana and see if the console shows any errors or anything. Preferably screenshot the whole console window.

**Comment by kputschko** [comment]
Two errors:

[0217/165022.636:ERROR:cookie_monster.cc(891)] Found cookies with duplicate
creation times in backing store: {name='pv', domain='.gamebanana.com',
path='/'}
[0217/165022.637:ERROR:cookie_monster.cc(891)] Found cookies with duplicate
creation times in backing store: {name='cto_bundle', domain='gamebanana.com',
path='/'}

**Comment by NiceneNerd** [comment]
Implemented a workaround for when GB doesn't behave.

**Comment by kputschko** [comment]
Hey @NiceneNerd, this issue is still occurring with the same errors in the debug window, even on the latest version of BCML 3.4.6:

```
C:\Users\kp>Downloads\bcml-win64-bundle_b2b19\python.exe -m bcml bcml-debug
[0424/104436.829:ERROR:cookie_monster.cc(891)] Found cookies with duplicate creation times in backing store: {name='pv', domain='.gamebanana.com', path='/'}
[0424/104436.829:ERROR:cookie_monster.cc(891)] Found cookies with duplicate creation times in backing store: {name='cto_bundle', domain='gamebanana.com', path='/'}
[0424/104448.898:ERROR:request_handler.cpp(109)] [Browser process] OnRenderProcessTerminated()
```

**Comment by NiceneNerd** [comment]
Those errors don't really mean anything, but GB did make some API changes that I'll probably need to account for. I'll reopen this until the API change is supported.
