### ISSUE TITLE
Can't install Mods through Gamebanana or Manually

### ISSUE THREAD

**Issue by LuckyLuigiX4** [NiceneNerd/BCML#128]
I've spent some time trying to fix this issue myself, but I am at a loss. The title says it all really.
All I have to go on is this through my terminal (I'm on Linux)

```keving@LuigiPC BCML]$ python -m bcml
QSettings::value: Empty key passed
QSettings::value: Empty key passed
[pywebview] Error occurred while evaluating function get_mods
Traceback (most recent call last):
  File "/home/keving/BCML/webviewb/util.py", line 175, in js_bridge_call
    func_params = param if not param else json.loads(param)
  File "/usr/lib/python3.9/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not dict
[pywebview] Error occurred while evaluating function check_mod_options
Traceback (most recent call last):
  File "/home/keving/BCML/webviewb/util.py", line 175, in js_bridge_call
    func_params = param if not param else json.loads(param)
  File "/usr/lib/python3.9/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not dict```

Trying to install Manually just hangs on the "One sec" Box forever. And trying to click on the Gamebanana Tab causes the window to get stuck trying to load a blank screen.

**Comment by NiceneNerd** [comment]
So, three problems:

1. The JSON serialization error I've seen before but can't replicate. It *only* happens on Python 3.9, but even then it only seems to happen on some systems and I haven't been able to produce it myself.
2. Getting stuck on One Sec _could_ indicate a problem with the 7-Zip binary or it could be a result of the above problem.
3. Can you elaborate on the GB tab thing? Does it say it's syncing, or it is totally and completely blank?

**Comment by LuckyLuigiX4** [comment]
Sure. For the Second Question, I downloaded a bnp from GameBanana to try doing it manually, and it didn't work. I just tried it with that option enabled, still stuck. (Also want to mention as I forgot before, I have to do into the json file and change the settings there myself because saving settings in the application doesn't actually save them, no matter how much I click on the save button)

For the 3rd question, when I click on the GB tab, the whole window just becomes gray (the dark theme color I believe), and it doesn't say anything, just a gray background.

**Comment by NiceneNerd** [comment]
So, most likely, all of this does come from the JSON encoding issue. I don't have any idea where that issue is coming from though, as I haven't been able to replicate it with Python 3.9 on Manjaro or Ubuntu so far. TBH I don't think I'll be able to find the cause unless someone who actually has the issue runs BCML with a Python debugger.

**Comment by LuckyLuigiX4** [comment]
well If I can figure out how to run BCML with a python debugger, I'd be happy to send a log if thats how it works
Otherwise, I'm kind of stuck right now.

**Comment by LuckyLuigiX4** [comment]
I just thought of something. Since this issue seems to only happen on python 3.9, is there a way I could run BCML with Python 3.8?

**Comment by NiceneNerd** [comment]
Sure, use `[pyenv](https://github.com/pyenv/pyenv)`

**Comment by LuckyLuigiX4** [comment]
Thank you. Once I figure out how to use it I'll let you know if it worked or not. Not gonna bother you asking for a tutorial. I'm sure you have better things to do with your time than typing up one.

**Comment by NiceneNerd** [comment]
It's not too hard once you get it set up, and it's _so_ insanely helpful. I have Python 3.9, 3.8, and 3.7 all working side-by-side with very few issues thanks to pyenv.

**Comment by LuckyLuigiX4** [comment]
Good news, I got closer than last time with running BCML. Bad news, now I'm getting this error, but to me at least it looks a lot more fixable.

```
keving@LuigiPC BCML]$ python -m bcml
[pywebview] QT cannot be loaded
Traceback (most recent call last):
  File "/home/keving/BCML/webviewb/guilib.py", line 32, in import_qt
    import webviewb.platforms.qt as guilib
  File "/home/keving/BCML/webviewb/platforms/qt.py", line 38, in <module>
    from PyQt5 import QtCore
ImportError: /home/keving/.pyenv/versions/3.8.7/lib/python3.8/site-packages/PyQt5-5.15.3-py3.8-linux-x86_64.egg/PyQt5/QtCore.abi3.so: undefined symbol: _ZdlPvm, version Qt_5
[pywebview] GTK cannot be loaded
Traceback (most recent call last):
  File "/home/keving/BCML/webviewb/guilib.py", line 18, in import_gtk
    import webviewb.platforms.gtk as guilib
  File "/home/keving/BCML/webviewb/platforms/gtk.py", line 36, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
Traceback (most recent call last):
  File "/home/keving/.pyenv/versions/3.8.7/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/keving/.pyenv/versions/3.8.7/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/keving/BCML/bcml/__main__.py", line 129, in <module>
    main()
  File "/home/keving/BCML/bcml/__main__.py", line 117, in main
    webview.start(
  File "/home/keving/BCML/webviewb/__init__.py", line 123, in start
    guilib = initialize(gui)
  File "/home/keving/BCML/webviewb/guilib.py", line 79, in initialize
    raise WebViewException(
webviewb.util.WebViewException: You must have either QT or GTK with Python extensions installed in order to use pywebview.


```
Hopefully its an easy fix at least.

**Comment by LuckyLuigiX4** [comment]
I'm unsure if you have seen my reply. I have tried a few things to fix the issue and nothing has changed. Any Ideas?

**Comment by NiceneNerd** [comment]
Eh, these dependencies between multiple versions are always very weird, and when I solve them it always seems to be by accident. What distro do you have?

**Comment by LuckyLuigiX4** [comment]
Manjaro

**Comment by NiceneNerd** [comment]
You might try reinstalling the `python-pyqtwebengine` and `python-pyqt5` packages, maybe?

**Comment by LuckyLuigiX4** [comment]
Same error. Im going to try and do another reinstall of bcml, I don't know what else to do

**Comment by NiceneNerd** [comment]
Closing: stale and unable to reproduce
