### ISSUE TITLE
Uninstalling this is VERY DANGEROUS, PERMANENTLY DELETES ALL FILES IN FOLDER OF .EXE

### ISSUE THREAD

**Issue by xecus922** [NiceneNerd/BCML#131]
So I just downloaded this today, installed, I click the BCML.exe that was placed in my startup menu and all I see is a white page saying something about 404 and HTTPStatus not found. 

As I'm trying different things to try and get this to work since there's nothing about this error in the troubleshooting steps, I try extracting the installation files located in the bcml bundle folder within the rar into my cemu folder so it's in the same folder as the cemu.exe to see if that works. Still doesn't work. 

Next thing I do is I uninstall BCML so I can just remove the BCML files and try redownloading it. Guess what happens? Not only does it delete the BCML files it also permanently deleted ALL my CEMU files as well. So all the configuring and setting up CEMU went down the drain. 

This is not how an uninstaller should work, it should not be deleting every single file in the same folder as the .exe. And this isn't about just me, I was lucky enough to place the BCML files in my CEMU folder so all it deleted was my emulator files. If someone places these BCML installation files in their root hard drive folder then uses the BCML uninstall.exe their entire hard drive will be wiped...I don't think I need to say more.

**Comment by Vehdrehl** [comment]
"This is not how an uninstaller should work". Indeed, and it's not how it works. Nothing about BCML will uninstall, remove or touch any non-BCML files whatsoever. I think you ought to say more. Such as the exact steps you took. because this is a well known, valid and extremely helpful tool that many use daily and have never encountered anything even remotely close to what you're stating. You haven't even sought help, you just went straight to the blame-game. Although most will not buy this as they have experience with this fantastic tool and are aware of what it does, spreading disinformation about anyone's hard work is a very disingenuous and underhanded thing to do.

**Comment by xecus922** [comment]
"Nothing about BCML will uninstall, remove or touch any non-BCML files whatsoever"

False, you're 100% incorrect, you're telling lies and you clearly have not even bothered attempting to reproduce this. 

"You just went straight to the blame-game" 

LOL do you even know the meaning of these words you're using? "Blame-game"? How is me reporting an issue with a program "blame-game"? So if an application is causing issues and not working as intended it means they're "blaming". You are clearly a child with that mentality and extremely immature, please go address your emotional and personal issues. Please learn the meaning of words you use next time, child. 

"valid and extremely helpful tool that many use daily and have never encountered anything even remotely close to what you're stating." 

You don't speak for everyone and you don't have the slightest clue of what issues others are experiencing with BCML. And if what you were claiming was true there wouldn't be 90+ issues here on the github post alone and users having issues with it all over Reddit so you're a liar like I said and your only purpose here is to try and kiss ass and shut anyone up claiming to have issues with BCML, you're a shill. And for that reason this will be my last reply to your irrelevant, ignorant and immature, childish posts.

I will no longer be reading or replying to anything else you have to say as everything you've said in your post has been irrelevant. Go find someone else to beg for attention and try to argue with, troll.  

Anyways, here is video proof of BCML deleting unrelated files. 

https://vimeo.com/520849354

As you can see in this video I've reproduced this in a fresh Windows Sandbox environment (basically like a virtual machine). I created 10 test folders (Named Test 1 to Test 10), I even made a folder called 'DON'T DELETE ME BCML' and I placed some random image files in the same folder as the BCML installation files. I go to the start menu, choose the BCML Uninstall.exe file and everything is deleted from the folder, every single one of those unrelated folders and images that were in the folder are permanently deleted. 

So like I said, this is not how an uninstaller should behave.

**Comment by NiceneNerd** [comment]
Who installs apps to folders with other stuff? Even if you're extracting something to the same general area as something else it should at least get its own subfolder. This isn't a bug.

**Comment by xecus922** [comment]
That's so inconsiderate and closed minded. You just assume every single computer user on the planet is always going to place installation files in an empty folder. You assume that no one would ever accidentally install/extract an archive's contents in a root directory or try to place them with other files during troubleshooting, that no one would ever make a mistake with where they extract their installation files....so closed minded. 

And this is besides the point that you've created an uninstaller that doesn't even uninstall properly, it just wipes everything in the directory, an uninstaller is supposed to uninstall YOUR PROGRAM'S FILES, not YOURS AND THE USER'S FILES. Can't believe I actually have to tell this to someone, I'm speechless. Not surprised you closed this so quick to hide it and save face so you don't accept responsibility for making such a terrible uninstaller. This is the first time I've seen an uninstaller so bad that it just deletes everything including the user's files in my 20+ years of using computers and various uninstallers, this is just awful and you know the disaster's you could cause leaving it like this so you close this so people don't find out, too funny.

Good luck in life man you'll need it.

**Comment by NiceneNerd** [comment]
https://www.google.com/search?q=anger+management+classes+near+me
https://www.google.com/search?q=how+to+stop+overreacting+to+dumb+stuff
https://www.google.com/search?q=how+not+to+be+an+entitled+brat

And yes, I'm very closed minded about things that are a complete waste of my time. If you don't like it, fork the project and fix it and put me "out of business" with your superior work.

The number of hours I've put into trying to make BCML easier to install for noobs who can't figure out how to use pip is way out of proportion to the amount of time I actually have between my full time job, grad studies, wife, and 5 children. If you had come here with even the most basic level of human decency and consideration I might have considered trying to squeeze in some time to help you out, but instead you burst in here as an entitled jerk, insulting myself and my work and throwing a temper tantrum like my 2 year old.

**Comment by NiceneNerd** [comment]
To be clear about the facts themselves, it deletes everything in the same folder as `setup.exe`.
