### ISSUE TITLE
BCML Doesn't install itself but presents a message saying it was successfully installed

### ISSUE THREAD

**Issue by redacted187** [NiceneNerd/BCML#133]
![image](https://user-images.githubusercontent.com/4555642/111053452-7b2cef00-8429-11eb-918d-f9962adb67ef.png)
There is no desktop shortcut despite that option being checked, and nothing shows up in windows when I search for 'BCML'. I try to run it from the bcml.exe, but that doesn't work either. I have all the requirements, I have Python 3.9 installed and added to PATH. I have Visual Studio= build tools, I have *poured* through stackoverflow and various forums trying to resolve this myself but got absolutely nowhere, Installing via pip install doesn't work either, and does this:

PS E:\> pip install bcml
Collecting bcml
  Using cached bcml-3.3.4-py3-none-any.whl (29.0 MB)
Collecting PyYAML~=5.3.1
  Using cached PyYAML-5.3.1-cp39-cp39-win_amd64.whl (212 kB)
Collecting cefpython3~=66.0
  Using cached cefpython3-66.1-py2.py3-none-win_amd64.whl (69.0 MB)
Collecting xxhash~=1.4
  Using cached xxhash-1.4.4.tar.gz (54 kB)
Collecting pythonnet>=2.5.0rc2
  Using cached pythonnet-2.5.2.tar.gz (1.9 MB)
Collecting aamp>=1.4.1
  Using cached aamp-1.4.1-py3-none-any.whl (337 kB)
Collecting numpy==1.19.2
  Using cached numpy-1.19.2.zip (7.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting oead~=1.2.0
  Using cached oead-1.2.1-cp39-cp39-win_amd64.whl (881 kB)
Collecting rstb>=1.2.0
  Using cached rstb-1.2.2-py3-none-any.whl (15 kB)
Collecting botw-havok~=0.3.18
  Using cached botw_havok-0.3.18-py3-none-any.whl (117 kB)
Collecting requests~=2.23.0
  Using cached requests-2.23.0-py2.py3-none-any.whl (58 kB)
Collecting botw-utils==0.2.3
  Using cached botw_utils-0.2.3-py3-none-any.whl (3.5 MB)
Collecting byml>=2.3.1
  Using cached byml-2.4.2-py3-none-any.whl (16 kB)
Collecting colorama~=0.4.3
  Using cached colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting sortedcontainers~=2.0
  Using cached sortedcontainers-2.3.0-py2.py3-none-any.whl (29 kB)
Collecting pycparser
  Using cached pycparser-2.20-py2.py3-none-any.whl (112 kB)
Collecting chardet<4,>=3.0.2
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Using cached urllib3-1.25.11-py2.py3-none-any.whl (127 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Using legacy 'setup.py install' for pythonnet, since package 'wheel' is not installed.
Using legacy 'setup.py install' for xxhash, since package 'wheel' is not installed.
Building wheels for collected packages: numpy
  Building wheel for numpy (PEP 517) ... done
  Created wheel for numpy: filename=numpy-1.19.2-cp39-cp39-win_amd64.whl size=4818190 sha256=fb2d026de5285778eb0ab2d21b0d6aaad9424f5d24f99a5aa1ade24da62e566f
  Stored in directory: c:\users\e\appdata\local\pip\cache\wheels\a3\17\dd\f2dba23a35bb6008732772ccfb13d3d0e537fbc6919ce6862b
Successfully built numpy
Installing collected packages: xxhash, urllib3, sortedcontainers, PyYAML, pycparser, oead, numpy, idna, colorama, chardet, certifi, rstb, requests, pythonnet, cefpython3, byml, botw-utils, botw-havok, aamp, bcml
    Running setup.py install for xxhash ... done
    Running setup.py install for pythonnet ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\e\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\E\\AppData\\Local\\Temp\\pip-install-m1gwmc3i\\pythonnet_971786947286433e8c959d4837b62957\\setup.py'"'"'; __file__='"'"'C:\\Users\\E\\AppData\\Local\\Temp\\pip-install-m1gwmc3i\\pythonnet_971786947286433e8c959d4837b62957\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\E\AppData\Local\Temp\pip-record-hhgxa_u_\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\e\appdata\local\programs\python\python39\Include\pythonnet'
         cwd: C:\Users\E\AppData\Local\Temp\pip-install-m1gwmc3i\pythonnet_971786947286433e8c959d4837b62957\
    Complete output (6 lines):
    usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: setup.py --help [cmd1 cmd2 ...]
       or: setup.py --help-commands
       or: setup.py cmd --help

    error: option --single-version-externally-managed not recognized
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\e\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\E\\AppData\\Local\\Temp\\pip-install-m1gwmc3i\\pythonnet_971786947286433e8c959d4837b62957\\setup.py'"'"'; __file__='"'"'C:\\Users\\E\\AppData\\Local\\Temp\\pip-install-m1gwmc3i\\pythonnet_971786947286433e8c959d4837b62957\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\E\AppData\Local\Temp\pip-record-hhgxa_u_\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\e\appdata\local\programs\python\python39\Include\pythonnet' Check the logs for full command output.

**Comment by redacted187** [comment]
I've been using literally ALLLLL (Not exaggerating) of my freetime for the last **3** days trying to get this to work. I am burnt out on  all my favorite passtimes and I needed something to focus on and latched on to this. I'm in a cold sweat at my computer and have been spending probably an unhealthy amount of time, anxiety, and energy working on just *installing* BCML. The more I fail, the more desperate I get, and thus the more energy I feel like pouring into it. PLEASE please help me. I know this is so lame but at this point I'm obsessed and I've hit a wall which is a terrible feeling

**Comment by NiceneNerd** [comment]
A couple things:
1. Per the readme, you can't use 3.9. 
2. When the setup says it creates shortcuts but doesn't, AFAIK it is impossible to find out why on either your or my end, so the solution is to manually make a shortcut to the bundled `pythonw.exe` file and add `-m bcml` as arguments.
