### ISSUE TITLE
BCML only shows first file (first .rar) when installing mods with multiple files (multiple .rar) via GameBanana view

### ISSUE THREAD

**Issue by zardini123** [NiceneNerd/BCML#135]
Hi!  Thank you for making such a wonderful tool!

Using the GameBanana viewer in BCML, searching "Zelda's Ballad," and attempting install via the install button ,the "Install Mod" window only shows shield_fix.rar.  As one can see in the [GameBanana website for Zelda's Ballad](https://gamebanana.com/skins/179455), there are 3 .rar files.

Let me know if you cannot replicate!  Thank you!

**Comment by NiceneNerd** [comment]
If you view the mod instead of clicking Install directly, the mod info window will have install options for each of the files.
![image](https://user-images.githubusercontent.com/6720029/112221200-29d4ea80-8bf5-11eb-836a-d2ab0e6ddc03.png)

**Comment by zardini123** [comment]
When I was letting BCML sit for a little bit, the "Install Mod" window popped up for ZeldasBallad.rar.  Being that zelda's ballad is a hefty mod (500 mb) total, it seems BCML had to download the entire file before prompting the user.  Should I open a new issue?  This seems like a problem others could run into in the future.
