### ISSUE TITLE
No such file or directory: ~/.local/share/applications/bcml-schema.desktop

### ISSUE THREAD

**Issue by Fates-End** [NiceneNerd/BCML#138]
I've been having a heck of a time trying to get this installed properly on Linux. Compiling from source ran me into some errors, so I tried just installing it from pip, but that straight up won't launch, saying that it needs "bcml-schema.desktop". What on earth is bcml-schema.desktop? I can't find a single mention of it anywhere, whether in the repository, the issues, or just on a raw google search.

**Comment by NiceneNerd** [comment]
It's not the file itself, but one of the folders it belongs in. Does `~/.local/share/applications` exist?

**Comment by Fates-End** [comment]
> It's not the file itself, but one of the folders it belongs in. Does `~/.local/share/applications` exist?

No, it doesn't. Would creating an empty directory with that name help any?

**Comment by NiceneNerd** [comment]
Yeah, and I'll make sure it does that automatically in the future.

**Comment by Fates-End** [comment]
After creating the directory and manually installing a library that my version of debian doesn't have in its repository, I got it to start up, but it seems to be stuck on "Checking Folder, One Sec". The only terminal output I'm getting is:

`js: Uncaught TypeError: channel.execCallbacks[message.id] is not a function
js: Uncaught TypeError: channel.execCallbacks[message.id] is not a function
js: Uncaught TypeError: channel.execCallbacks[message.id] is not a function
js: Uncaught TypeError: channel.execCallbacks[message.id] is not a function
js: Uncaught TypeError: channel.execCallbacks[message.id] is not a function
js: Uncaught TypeError: channel.execCallbacks[message.id] is not a function
js: Uncaught TypeError: channel.execCallbacks[message.id] is not a function
js: Uncaught TypeError: channel.execCallbacks[message.id] is not a function
js: Uncaught TypeError: channel.execCallbacks[message.id] is not a function
js: Uncaught TypeError: channel.execCallbacks[message.id] is not a function
js: Uncaught TypeError: channel.execCallbacks[message.id] is not a function
js: Uncaught TypeError: channel.execCallbacks[message.id] is not a function
js: Uncaught TypeError: channel.execCallbacks[message.id] is not a function
js: Uncaught TypeError: channel.execCallbacks[message.id] is not a function
js: Uncaught TypeError: channel.execCallbacks[message.id] is not a function
js: Uncaught TypeError: channel.execCallbacks[message.id] is not a function
js: Uncaught TypeError: t.props.onHide is not a function
js: Uncaught TypeError: t.props.onHide is not a function
`

**Comment by Fates-End** [comment]
Ah, nevermind, it was just a really, really long load time. Seems to work fine now.
