### ISSUE TITLE
Identifying changed text entries step fails

### ISSUE THREAD

**Issue by GingerAvalanche** [NiceneNerd/BCML#14]
When I try to load the mod found here https://gamebanana.com/gamefiles/8387 for installation, the step "Identifying changed text entries..." always fails. It spits out the following error in the log.

Traceback (most recent call last):
  File "d:\python37\lib\site-packages\bcml\install.py", line 258, in main
    with open(tmptext / rel_path, 'r', encoding='utf-8') as mod_file:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\USERNAME\\AppData\\Local\\bcml\\tmp_text\\DemoMsg\\Demo101_0.msyt'

Thing is, when I extract the Bootup_USen.pack from that mod, that file is there.

Also, BCML changes which file it can't find. Sometimes it's Demo101_0, sometimes Demo033_0, sometimes BalladOfHeroRito, etc. All of the files it claims it can't find, are there in the mod's Bootup_USen.pack

**Comment by NiceneNerd** [comment]
Basically resolved [in this commit](https://github.com/NiceneNerd/BCML/commit/1ad05838e1302d97e8ba4c344fc76996766a826c)
