### ISSUE TITLE
python3.9 compatibility

### ISSUE THREAD

**Issue by JanzenJohn** [NiceneNerd/BCML#142]
syaz0 as a yaz0 decompress method is deprecated, and was replaced by oead
https://github.com/zeldamods/oead

I can not compile syaz0 (Cmake errorcode 2)
and can't install it from wheel / .whl files

**Comment by JanzenJohn** [comment]
this is fixed as described in #100

**Comment by NiceneNerd** [comment]
BCML does not itself require syaz0, mind you. The syaz0 requirement comes from the rstb library, which has been updated to use oead in its repo but never received a new release.
