### ISSUE TITLE
Cant select language

### ISSUE THREAD

**Issue by JanzenJohn** [NiceneNerd/BCML#143]
In the options for Game Language there aren't any languages.

![image](https://user-images.githubusercontent.com/51709412/113571317-b45e1680-9605-11eb-806d-207d077999d0.png)

**Comment by NiceneNerd** [comment]
Have you already set a valid game directory?

**Comment by JanzenJohn** [comment]
I think so, all inside the mlc01 folder where as instructed by the tooltip

![image](https://user-images.githubusercontent.com/51709412/113574207-28e78400-960b-11eb-8701-3a78bc819b10.png)

**Comment by JanzenJohn** [comment]
Okay idk what happened but after resetting the paths it suddenly worked.

**Comment by DALucifer13** [comment]
i've got the same issue as this guy, but re-setting path variables did nothing. this is happening on my first try at using bcml.

**Comment by JanzenJohn** [comment]
Was my first try to, restart (pc) and reset all paths,  and try to select a language again

**Comment by DALucifer13** [comment]
there a quick way to do that? seems like it would take a while to reenter all the different path options.

**Comment by NiceneNerd** [comment]
Are the folders you selected actually valid?

**Comment by DALucifer13** [comment]
im trying to set it up in switch mode, and there is little documentation on how to do it in switch. i assumed(maybe wrongly) that you could export into any folder then transfer it to the switch after. 

![image](https://user-images.githubusercontent.com/56401014/115293243-fbdcba80-a14e-11eb-91ce-689dbbdf24a1.png)

**Comment by NiceneNerd** [comment]
You can export into any folder and transfer to Switch later, but your game folders aren't green. You need to provide the paths to your 1.6.0 game files and DLC files first.

**Comment by DALucifer13** [comment]
how do you get the game files? the nx dump tool only looks like it works if you have the cartridge, and mine is download.
