### ISSUE TITLE
Unable to tell if download is is actually happening or not.

### ISSUE THREAD

**Issue by MaxandreOgeret** [NiceneNerd/BCML#145]
Hello, 

It would be a nice feature to display some kind of information that allow the user to tell if something is happening or not. For example for the download you could display the number of bytes downloaded.

What do you think ? 

Thanks !

**Comment by Drakonas** [comment]
I second this personally. Also when I press "Update" then not choose an update file, it still processes some data even though it didn't change anything. I assume it's remerging. It would be nice to cancel the update when no file is chosen.

**Comment by LordOfEdge** [comment]
I would also like to add that this sort of feature would be really useful during the installation process. Very large mods such as the Zelda's Ballad mod sometimes install for 30+ minutes in my experience, and it would be nice to know whether they are hanging or not.

**Comment by GingerAvalanche** [comment]
BCML is reaching the end of its development lifetime. Efforts are being put into a replacement tool, where features like this will be much easier to implement. Closing this as not planned for BCML.
