### ISSUE TITLE
Mod won't load after adding to BCML

### ISSUE THREAD

**Issue by Gueymonster** [NiceneNerd/BCML#147]
Hi all! 

I have finished setting up BCML, however whenever I add any mod and launch CEMU, the mod does not appear to show up and it is just the vanilla game. I'm not sure if there is anything I'm doing wrong, but I would really appreciate some help!

**Comment by Gueymonster** [comment]
I would like to add that I went through the help guide on BCML. To clarify the problem I am having is that I've installed my mods (Linkle) in BCML, but they don't take effect in game. After checking BCML in graphics packs in my CEMU and checking "disable hard links for master mod" option in BCML settings, the mod still does not take effect in game.

**Comment by NiceneNerd** [comment]
Paste the contents of `%LOCALAPPDATA%\bcml\settings.json`

**Comment by Gueymonster** [comment]
Hey Caleb,

Thanks for your help! Here are the contents of %LOCALAPPDATA%\bcml\settings.json. Please let me know if there is any other information you need! 

{
  "cemu_dir": "C:\\Program Files (x86)\\CEMU",
  "game_dir": "C:\\Program Files (x86)\\CEMU\\mlc01\\usr\\title\\00050000\\101c9500\\content",
  "game_dir_nx": "",
  "update_dir": "C:\\Program Files (x86)\\CEMU\\mlc01\\usr\\title\\0005000e\\101c9400\\content",
  "dlc_dir": "C:\\Program Files (x86)\\CEMU\\mlc01\\usr\\title\\0005000c\\101c9400\\content\\0010",
  "dlc_dir_nx": "",
  "store_dir": "C:\\Users\\Asad\\AppData\\Local\\bcml",
  "export_dir": "C:\\Users\\Asad\\Desktop\\CEMU\\graphicPacks\\BreathOfTheWild_BCML",
  "export_dir_nx": "",
  "load_reverse": false,
  "site_meta": "",
  "no_guess": false,
  "lang": "EUen",
  "no_cemu": false,
  "wiiu": true,
  "no_hardlinks": true,
  "force_7z": false,
  "suppress_update": false,
  "loaded": true,
  "nsfw": false,
  "changelog": true,
  "strip_gfx": false,
  "auto_gb": true,
  "dark_theme": false,
  "last_version": "3.4.8"
}

**Comment by NiceneNerd** [comment]
So, it appears BCML is exporting the merged graphic pack to a different Cemu folder (`C:\Users\Asad\Desktop\CEMU\graphicPacks\BreathOfTheWild_BCML`) than the one you otherwise appear to be using (`C:\Program Files (x86)\CEMU`)

**Comment by Gueymonster** [comment]
Hey Caleb,

I see, so this is why the mods are not taking effect. I need to make BCML export the merged graphics pack to the correct CEMU folder (C:\Program Files (x86)\CEMU). Do you know how I can change BCML to export to correct Cemu folder? I have attached a screenshot of my Game Folders settings.

Thanks! 
![Capture](https://user-images.githubusercontent.com/83485593/116799111-16565280-aac4-11eb-821c-3047689a1268.PNG)

**Comment by NiceneNerd** [comment]
The export folder was removed as a user configurable setting with Cemu only as of 3.4.7. You can manually change it in your settings file from `C:\Users\Asad\Desktop\CEMU\graphicPacks\BreathOfTheWild_BCML` to `C:\Program Files (x86)\CEMU\graphicPacks\BreathOfTheWild_BCML`.

**Comment by Gueymonster** [comment]
Hey Caleb,

I am not sure how I can manually change it and which settings file you are referring to. If you are referring to the settings.json file from %LOCALAPPDATA%\bcml\settings.json, I have tried changing export_dir from
C:\Users\Asad\Desktop\CEMU\graphicPacks\BreathOfTheWild_BCML to C:\Program Files (x86)\CEMU\graphicPacks\BreathOfTheWild_BCML and it is still not working. 

Thanks

**Comment by NiceneNerd** [comment]
That is the right way to change it, but bear in mind you need to remerge after changing it, and since you have Cemu installed into Program Files (a bad idea, FWIW), you'll probably need to run BCML as admin for it to work.

**Comment by Gueymonster** [comment]
Hey Caleb,

After remerging, I got the mods to work! Thank you so much for helping me getting my mods on BCML working! You are the best! 

Thanks! 
Asad
