### ISSUE TITLE
BCML graphics pack not showing up in Cemu

### ISSUE THREAD

**Issue by grimgreb** [NiceneNerd/BCML#149]
BCML graphics pack is not on the list in Cemu. Have downloaded community graphics packs, searched BCML in all graphics packs, remerged... a few others also have this problem. https://www.reddit.com/r/CemuPiracy/comments/l7wab1/bcml_mods_not_showing_up_in_game/gv8ydtp/
thank you for your help.

**Comment by NiceneNerd** [comment]
Paste your BCML settings file

**Comment by grimgreb** [comment]
Apologies, where do I find that? I can't paste the settings.json file from bcml folder...

**Comment by adcar** [comment]
To anyone else having this issue - this answer fixed it for me 

https://www.reddit.com/r/CemuPiracy/comments/l7wab1/bcml_mods_not_showing_up_in_game/h1b0xsm?utm_source=share&utm_medium=web2x&context=3
