### ISSUE TITLE
Unicode Decode Error

### ISSUE THREAD

**Issue by JonathanChuyan** [NiceneNerd/BCML#152]
Seems to be charset problem,how to fix it?
`Using cached syaz0-1.0.1.tar.gz (704 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\python39\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\jonathan\\AppData\\Local\\Temp\\pip-install-0e4us3tj\\syaz0\\setup.py'"'"'; __file__='"'"'C:\\Users\\jonathan\\AppData\\Local\\Temp\\pip-install-0e4us3tj\\syaz0\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\jonathan\AppData\Local\Temp\pip-pip-egg-info-ct5z5uj3'
         cwd: C:\Users\jonathan\AppData\Local\Temp\pip-install-0e4us3tj\syaz0\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\jonathan\AppData\Local\Temp\pip-install-0e4us3tj\syaz0\setup.py", line 67, in <module>
        long_description = fh.read()
    UnicodeDecodeError: 'gbk' codec can't decode byte 0x94 in position 2381: illegal multibyte sequence
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

**Comment by NiceneNerd** [comment]
That error pertains to syaz0, not BCML itself, and comes when using Python 3.9, which is not supported.
