### ISSUE TITLE
Mods downloaded in BCML, directories green, game still loading vanilla.

### ISSUE THREAD

**Issue by SpriteKnight27** [NiceneNerd/BCML#158]
Unsure as to why the mods, specifically the linkle mod, armor icons, and title screen aren't loading with the game. I am launching from BCML, the directories are green, I've even tried to launch the mods individually to no success. It seems the workarounds in other similar threads aren't working for this issue.

**Comment by DasBroti** [comment]
tried exporting the mods and manually put them into graphic packs ?

**Comment by NiceneNerd** [comment]
You've tried all of these already? https://github.com/NiceneNerd/BCML/blob/master/docs/trouble.md#ive-installed-my-mods-in-bcml-but-they-dont-take-effect-in-cemu
