### ISSUE TITLE
BCML Wont Launch 

### ISSUE THREAD

**Issue by QuartzNeko** [NiceneNerd/BCML#162]
I keep getting this error I dont know how to fix ```
raise RuntimeError("BCML could not load its settings file") from err
RuntimeError: BCML could not load its settings file
```

**Comment by jordanbtucker** [comment]
I would move your `AppData\Local\bcml` folder to your desktop as a backup, then start BCML. (Make sure you've moved it and not just copied it.) This will reset BCML to default settings, so you'll have to configure your Cemu folders again, but at least it should start working again.

1. In Windows, click Start
2. Type `Run` and hit enter
3. Type `%LOCALAPPDATA%` and hit enter
4. Find the `bcml` folder and move it to your desktop
5. Start BCML

Once you've got BCML working again, you can delete the backup `bcml` folder on your desktop.

**Comment by QuartzNeko** [comment]
When I do that nothing happens no error log either still does not open

**Comment by jordanbtucker** [comment]
Can you post your `settings.json` file located at `c:\users\vampire\appdata\local\bcml\settings.json`

**Comment by QuartzNeko** [comment]
there is no settings.json

**Comment by jordanbtucker** [comment]
Hmm. I'm not really sure how to help then. That error is saying there is a problem on line 9 of the file at `%LOCALAPPDATA%\bcml\settings.json` (or possibly `tmp_settings.json`), so I'm not sure why it's giving that error if neither of those files exist. Maybe the developer can chime in and help you out.

**Comment by QuartzNeko** [comment]
I had this error on windows so I tried to do a clean install on my linux and I get same error

**Comment by jordanbtucker** [comment]
Hmm. I just did a clean install on Ubuntu 20.04. I did get two different errors, but I only needed to add `~/.local/bin` to my PATH and run `sudo apt install qt5-default` to fix them. It's working for me.

I did not get the error that you posted.

How are you installing BCML? I'm using `pip install bcml` with Python 3.8 on both Windows and Ubuntu.

**Comment by QuartzNeko** [comment]
I am using the command Py -m pip install bcml, when that did not work I tried to do manual but same thing followed the githubs instructions  and set paths on windows

**Comment by QuartzNeko** [comment]
Sooo on my linux i got it working by typing xdg-mime --help
windows not working but since i have it working on linux i will mark as solved
