### ISSUE TITLE
AppData folder doesn't exist where defined

### ISSUE THREAD

**Issue by yiays** [NiceneNerd/BCML#163]
When using Python for Windows when it's installed from the Windows Store, appdata is redirected to a virtual AppData directory for security purposes, in my case it's C:\Users\asrie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\bcml instead of what bcml expects (C:\Users\asrie\AppData\Local\bcml) this doesn't seem to cause any errors other than when bcml is showing the location of a mod folder. As shown below.

![image](https://user-images.githubusercontent.com/7791524/120731637-1ec50180-c538-11eb-8b1a-7ce53a6a2c84.png)

**Comment by NiceneNerd** [comment]
There are lots of other hangups that often occur when using Python from the Windows Store, so I don't really support it. I would recommend reinstalling Python from the Python website directly.
