### ISSUE TITLE
Tried all methods on the in-app troubleshoot, game still crashes after loading shaders.

### ISSUE THREAD

**Issue by MisakiSawada** [NiceneNerd/BCML#165]
Cemu crashes after loading shaders no matter what I do even after going through everything in the in-app troubleshoot guide. Even with a fresh download with no mods loaded in, the game still crash after loading in the shaders. Even if I launch the game from Cemu, as long as the bcml is checked in the graphic pack, it crashes. The only thing I have not tried is checking the bootup.pack and that is because I couldn't find them nor do I know what to do with that. Any help would be great!

**Comment by Uranite** [comment]
have you tried renaming the shadercache folder to something else and check if it crashes or not, if it still does you can rename the folder back

**Comment by NiceneNerd** [comment]
My guess is either your dump itself or your something about your folder settings related to the dump is wonky.
