### ISSUE TITLE
Unable to install BCML

### ISSUE THREAD

**Issue by TakaShaw** [NiceneNerd/BCML#169]
Hi, this may be a stupid, common occurrence, but I'm having an issue where I cannot install BCML via Python. When I execute the "pip install bcml" command, I'm given the following error.

```
>>> pip install bcml
  File "<stdin>", line 1
    pip install bcml
        ^
SyntaxError: invalid syntax
```
I have Python 3.8 installed, and the latest Windows Visual redistributable installed. I'm not sure what I'm doing wrong, or even _if_ I'm doing something wrong.

**Comment by Jmitmax** [comment]
Hi, I had the same problem and was only able to solve it this way.
It must be installed through the Windows command line.
Run the command line and write
python -m pip install bcml
This solution has its drawbacks. I don't know where the BCML folder is and there is no BCML.exe.
To run BCML you need to go to
C:\Users\YOU_NAME\AppData\Local\Programs\Python\Python_YOU_NUMBER\Scripts\
and find BCLM file there and run it with python.

**Comment by TakaShaw** [comment]
That sounds pretty roundabout, but hopefully I can find another solution to this. I appreciate you taking the time to let me know about this though!

**Comment by Torphedo** [comment]
Just run the same command in regular command prompt, that's how you're supposed to do it. Once that's done, just enter `bcml` into cmd to launch BCML.

**Comment by Uranite** [comment]
did you check 'Add python to path' option when installing it?

**Comment by TakaShaw** [comment]
Well, I had selected "Add python to path" when I had installed, but I tried Jmitmath's method and it works out, so... I can't seem to install it any other way.
