### ISSUE TITLE
Cannot uninstall mods from BCML

### ISSUE THREAD

**Issue by yikeronim8** [NiceneNerd/BCML#170]
Aight lads, i'm at fucking wits end. Quick rundown

- playing BoTW on Cemu
- want to try second wind (expansion)
- get bcml all up and running following the guide
- download Second wind and Alternative bandana mods
- second wind starts bugging out with blood moons (common glitch) so I try to uninstall it
- its uninstalled in the bcml menu but not in my actual game
- try reinstalling bcml (put pip uninstall bcml and pip install bcml in cmd) same issue
- only way to get the shitty mod to stop working is by unchecking the "BCML" graphic pack which stops me from using ALL my bcml mods

Google gives me nothing, apparently i'm the only dumbass to encounter this issue

See below for a picture of what I mean. 
![1624763459746](https://user-images.githubusercontent.com/86563271/123549534-6cacde00-d761-11eb-91a2-4e674c65cdf6.png)

Second wind is obviously not installed but it apparently is

**Comment by Torphedo** [comment]
I'd guess something in BCML isn't able to push to Cemu for some reason. Uninstalling BCML didn't fix it because BCML doesn't do anything in memory, just sends the files for Cemu to load. The reason that unchecking BCML works is because that has Cemu stop loading the modpack BCML has created. My advice would be to delete the BCML graphics pack, then try to re-install BCML and get it working from scratch again. I'm unsure why it would be doing this, but without further info that's the easiest catch-all for the issue.

**Comment by Torphedo** [comment]
> 
> 
> I'd guess something in BCML isn't able to push to Cemu for some reason. Uninstalling BCML didn't fix it because BCML doesn't do anything in memory, just sends the files for Cemu to load. The reason that unchecking BCML works is because that has Cemu stop loading the modpack BCML has created. My advice would be to delete the BCML graphics pack, then try to re-install BCML and get it working from scratch again. I'm unsure why it would be doing this, but without further info that's the easiest catch-all for the issue.

(My only theory is that maybe you changed a filepath or setting somewhere between installing SW and having this issue)

**Comment by yikeronim8** [comment]
Hey thanks for the response. I tried to delete the graphics pack but I then have no way of reobtaining it. Reinstalling BCML doesn't download a new BCML graphics pack for some reason.

I'll try  it again now

**Comment by yikeronim8** [comment]
Yea, reinstalled it fully (pip uninstall bcml and then pip install bcml) and it redownloads BCML all fine, I can even download mods and stuff. But the BCML graphics pack never recreates itself after i've deleted it

**Comment by Torphedo** [comment]
> 
> 
> Yea, reinstalled it fully (pip uninstall bcml and then pip install bcml) and it redownloads BCML all fine, I can even download mods and stuff. But the BCML graphics pack never recreates itself after i've deleted it

I had a similar issue while trying to make a tutorial for BCML. For me, the pack only appeared after I remerged, even though I already had a mod installed. While you're at it, make sure your Cemu folder points to the folder directly containing the executable.

**Comment by yikeronim8** [comment]
> > Yea, reinstalled it fully (pip uninstall bcml and then pip install bcml) and it redownloads BCML all fine, I can even download mods and stuff. But the BCML graphics pack never recreates itself after i've deleted it
> 
> I had a similar issue while trying to make a tutorial for BCML. For me, the pack only appeared after I remerged, even though I already had a mod installed. While you're at it, make sure your Cemu folder points to the folder directly containing the executable.

I assume you mean the CTRL+M function in BCML (the icon that says "Remerge"). I did that and yea, didn't work

EDIT: Found the problem. I actually made a backup of the BCML folder and put it in a completely different folder (it's a habit I have whenever I delete a folder just incase something like this happens, i.e no way of getting it back). 

Turns out, that folder existing anywhere on the same drive as my emulator or Cemu (i'm ASSUMING) stops it from being recreated. Deleting the BCML graphics pack entirely finally recreated a new one upon remerge.

So yea, anyone else that gets my problem, hopefully this solves it. Cheers for your help

**Comment by Torphedo** [comment]
> 
> 
> > > Yea, reinstalled it fully (pip uninstall bcml and then pip install bcml) and it redownloads BCML all fine, I can even download mods and stuff. But the BCML graphics pack never recreates itself after i've deleted it
> > 
> > 
> > I had a similar issue while trying to make a tutorial for BCML. For me, the pack only appeared after I remerged, even though I already had a mod installed. While you're at it, make sure your Cemu folder points to the folder directly containing the executable.
> 
> I assume you mean the CTRL+M function in BCML (the icon that says "Remerge"). I did that and yea, didn't work
> 
> EDIT: Found the problem. I actually made a backup of the BCML folder and put it in a completely different folder (it's a habit I have whenever I delete a folder just incase something like this happens, i.e no way of getting it back).
> 
> Turns out, that folder existing anywhere on the same drive as my emulator or Cemu (i'm ASSUMING) stops it from being recreated. Deleting the BCML graphics pack entirely finally recreated a new one upon remerge.
> 
> So yea, anyone else that gets my problem, hopefully this solves it. Cheers for your help

Interesting. Glad it's fixed!
