### ISSUE TITLE
BCML won't launch BOTW or Cemu 

### ISSUE THREAD

**Issue by Cyberjynx** [NiceneNerd/BCML#171]
Traceback (most recent call last):
  File "c:\python38\lib\site-packages\bcml\_api.py", line 32, in status_run
    data = func(*args, **kwargs)
  File "c:\python38\lib\site-packages\bcml\_api.py", line 483, in launch_cemu
    Popen(cemu_args, cwd=str(util.get_cemu_dir()))
  File "c:\python38\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\python38\lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 740] The requested operation requires elevation

I get this error when trying to launch Cemu and I nothing happens at all when I try and launch BOTW... Any idea what's wrong?

Thanks in advance!

**Comment by linktlh** [comment]
NAB. You have your cemu.exe set to require administrator to run, thus bcml must be ran as administrator to be able to launch it.

**Comment by Cyberjynx** [comment]
NAB? How rude... Anyway, thanks for your help.

**Comment by linktlh** [comment]
> NAB? How rude... Anyway, thanks for your help.

That wasn’t to be rude, NAB is so anyone looking on knows they don’t need to fix something. It’s a fairly common term used. I apologize if it offended you.
