### ISSUE TITLE
mainstatic.yml Trial of the Sword placement issue

### ISSUE THREAD

**Issue by CEObrainz** [NiceneNerd/BCML#172]
It seems with BCML 3.4.9 if you install a mod with edits to the static.mubin file it'll cause Link's placement during the Trial of the Sword intro cutscene to appear under Hyrule. The player is still able to proceed so there's no impact to gameplay. If a BNP file was created prior to the introduction of the mainstatic merging this issue won't occur as BCML doesn't generate that file.

I've tested this by downgrading BCML to 3.4.1, generating a Second Wind BNP and then upgrading back to 3.4.9. If you need access to test files I can provide them.

**Comment by NiceneNerd** [comment]
What shows up in the mainstatic log in that case?

**Comment by CEObrainz** [comment]
Uploaded a file from SW where it's still occurring.
[mainstatic.txt](https://github.com/NiceneNerd/BCML/files/6909443/mainstatic.txt)

**Comment by Torphedo** [comment]
I took a look at this, removing the final entry in the current release of 1.9.9a fixes it. That entry has something to do with the Labors of the Hero shrine, but from my testing, it works perfectly with it removed. Here's the entry:
```StartPos:
  '-20303243405':
    Map: C-8
    PlayerState: Wait
    PosName: CDungeon200_1
    Rotate: {X: 0.0, Y: 3.30931854, Z: 0.0}
    Translate: {X: -2030.18005, Y: 323.989197, Z: 3404.67603}
  '-20303243409':
    Map: C-8
    PlayerState: Wait
    PosName: StartPos_CDungeon200
    Rotate: {X: 0.0, Y: 3.30931854, Z: 0.0}
    Translate: {X: -2030.18384, Y: 323.989197, Z: 3408.48389}

**Comment by Torphedo** [comment]
> 
> 
> I took a look at this, removing the final entry in the current release of 1.9.9a fixes it. That entry has something to do with the Labors of the Hero shrine, but from my testing, it works perfectly with it removed. Here's the entry:
> 
> ```
>   '-20303243405':
>     Map: C-8
>     PlayerState: Wait
>     PosName: CDungeon200_1
>     Rotate: {X: 0.0, Y: 3.30931854, Z: 0.0}
>     Translate: {X: -2030.18005, Y: 323.989197, Z: 3404.67603}
>   '-20303243409':
>     Map: C-8
>     PlayerState: Wait
>     PosName: StartPos_CDungeon200
>     Rotate: {X: 0.0, Y: 3.30931854, Z: 0.0}
>     Translate: {X: -2030.18384, Y: 323.989197, Z: 3408.48389}
> ```

Update: removing this also breaks the teleport point for that shrine. Not sure whether or not this is a BCML issue

**Comment by CEObrainz** [comment]
If it helps, here is a DiffCheck between the Hyrule Builder output of SW 1.9.10 and the BCML Master static mubin of the same version: https://www.diffchecker.com/FLjjsfWU

As you'll see the Master Sword placement and a few other things are removed.
