### ISSUE TITLE
Question about syaz0/oead

### ISSUE THREAD

**Issue by JupiterSky11** [NiceneNerd/BCML#173]
Will this ever be updated to use oead/is there a workaround so I can use it?  I'm not really interested in going through the painful process of python version control, I've already tried it twice and neither attempt went very smoothly, so I'm stuck with 3.9.

I did manage to get the syaz0 compiler past asking for pybind, but after that the errors got even worse, so after looking into syaz0 I realized it's been deprecated and its functionality was moved into oead.  Oead is compatable with python 3.9, so if I can skip the installation of syaz0 or modify the code to call for oead instead that should work.

**Comment by NiceneNerd** [comment]
It uses oead, but some of the other dependencies still use syaz0. Plus there are still other dependencies that don't support 3.9 for other reasons.

**Comment by JupiterSky11** [comment]
:+1:
