### ISSUE TITLE
Unpacking Game Tutorial Link leads to blank help page

### ISSUE THREAD

**Issue by Nosrick** [NiceneNerd/BCML#180]
Pretty much what it says in the title.
Within `Help > Troubleshooting > How do I get an unpacked game dump to use with BCML?` section, clicking the `This Tutorial` link leads to the Help window going completely blank.

**Comment by NiceneNerd** [comment]
It works for me; can you visit ZeldaMods.org in your browser?

**Comment by Nosrick** [comment]
> It works for me; can you visit ZeldaMods.org in your browser?

I can, yeah, and I found the page by searching for it in my browser, so I'm not sure what's going on.
Are there any logs I can provide?

**Comment by NiceneNerd** [comment]
Hmm, I don't think the help browser does any logging at all. Do other external links in the help work (e.g. the tutorial video, software license stuff)?

**Comment by Nosrick** [comment]
Yup, as far as I can tell, they do.
Just clicked the tutorial video button, and went through the licenses. All working, on that front.

**Comment by NiceneNerd** [comment]
What's your OS?

**Comment by Nosrick** [comment]
Windows 10, version 21H1.

**Comment by NiceneNerd** [comment]
I'll have to fiddle with it when I'm back on Windows later, but I've got no good ideas so far.

**Comment by Nosrick** [comment]
Thanks! It's probably some odd edge case going on, on my end, but I thought it'd be a good idea to report it anyway.

**Comment by linktlh** [comment]
Can confirm, It appears it's unable to handle the certificates correctly:
`[0901/072639.820:ERROR:ssl_client_socket_impl.cc(1098)] handshake failed; returned -1, SSL error code 1, net_error -113`

The web part of BCML is a little over my head though.
