### ISSUE TITLE
i dont even know anymore

### ISSUE THREAD

**Issue by IpGa13** [NiceneNerd/BCML#182]
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'C:\\Users\\________\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\botw_havok\\classes\\common\\hkcdStaticMeshTreehkcdStaticMeshTreeCommonConfigunsignedintunsignedlonglong1121hkpBvCompressedMeshShapeTreeDataRun.py' what the hell is this

**Comment by NiceneNerd** [comment]
That error comes from Python being unable to access extremely long file paths. It's a common problem for people using the Microsoft Store version of Python. Switch to a standard Python installation and never use the Microsoft Store for anything ever.
