### ISSUE TITLE
Infinite loading issue when trying to load into a shrine with BCML enabled in graphic packs.

### ISSUE THREAD

**Issue by imaybemomo** [NiceneNerd/BCML#184]
Issue only happened after I updated to the latest version of BCML and started a new save, not sure which version I had before updating. It let me do three of the four tutorial shrines before it started but now I can't do any of the shrines

I tried a fresh install of BOTW. If I disable ALL mods in BCML and try to launch BOTW Cemu will close after loading my shaders, I have to disable BCML in Cemu's graphic packs before it allows me to load in. I can load into the shrine with it disabled and then reactivate BCML's graphic pack once I'm back outside. Trying to enter a shrine or load a save that's already inside of a shrine results in the infinite loading.

**Comment by NiceneNerd** [comment]
Depending on how old your previous version of BCML was, it's possible you'd need to reinstall your mods.

**Comment by imaybemomo** [comment]
> Depending on how old your previous version of BCML was, it's possible you'd need to reinstall your mods.

Wow, embarrassed I didn’t try this. I figured disabling them was enough, thank you for the quick response c:
