### ISSUE TITLE
Potential Optimization for uninstalling mods

### ISSUE THREAD

**Issue by Torphedo** [NiceneNerd/BCML#186]
Not necesarily a bug, but I saw a few places where the remerging and uninstalling could be sped up significantly. The main one is this: when uninstalling a mod/mods that are already disabled, the entire load order remains in the same priority relative to each other, and therefore shouldn't need a remerge. The priority values could be adjusted for the new gap, but without being remerged. This would make uninstalling old mods significantly faster and less annoying.

**Comment by Torphedo** [comment]
Just got implemented. Thanks, Nicene!

**Comment by linktlh** [comment]
See 3985504fcd1a7dce182bbf7d51138d27de9474fc
