### ISSUE TITLE
Feature Request: Make options diff to base mod

### ISSUE THREAD

**Issue by t3nk3y** [NiceneNerd/BCML#192]
As is, if a file exists in a mod, and the exact same file exists in an option, that file will be stored in the BNP twice.
Ideally, options would be handled as if the main mod was installed, and then the option was installed on top of it, making just the diffs get applied.

**Comment by NiceneNerd** [comment]
This is supposed to be the existing behaviour, so I'll have to check into why it's not happening

**Comment by t3nk3y** [comment]
As you said this isn't supposed to be happening, and I re-tested this, and it isn't happening, I'll assume I must have either had some weird issue when this came up up, or that I haven't gotten enough sleep, and shouldn't have open this issue.

My apologies.

**Comment by ArchLeaders** [comment]
xD It happens to the best of us.
