### ISSUE TITLE
Feature Request: Options may need a priority/ordering system as well

### ISSUE THREAD

**Issue by t3nk3y** [NiceneNerd/BCML#193]
The documentation is not clear on this, but, as is, I believe the base mod is installed first.  Then the option is installed over it.  However, if there are multiple options that might conflict with each other, there is no clear explanation of how this case is handled.

I think the ideal behavior would be to have a priority string in the info file for the option, and in the GUI, have the ability to order them with a drag and drop.

P.S. sorry for inundating you with these, but they are all things I ran in to while working on mods, and left me questioning/wanting.  I really appreciate all of the work you've done here, and I figure it doesn't hurt to put the FR up here.

**Comment by ArchLeaders** [comment]
> The documentation is not clear on this, but, as is, I believe the base mod is installed first. Then the option is installed over it. However, if there are multiple options that might conflict with each other, there is no clear explanation of how this case is handled.
> 
> I think the ideal behavior would be to have a priority string in the info file for the option, and in the GUI, have the ability to order them with a drag and drop.
> 
> P.S. sorry for inundating you with these, but they are all things I ran in to while working on mods, and left me questioning/wanting. I really appreciate all of the work you've done here, and I figure it doesn't hurt to put the FR up here.

Shouldn't any _options_ that edit the same file(s) be pick-one only options?

Maybe I misunderstood the request. But having a sort order for options seems a bit unnecessary.

**Comment by t3nk3y** [comment]
The specific situation where I came across this one is on a mod that had files in a pack within a TitleBG.  The mod removes several files from the pack, but only when Option A is selected.  A different set of files are removed from the pack for Option B.  And it also handles having neither of those in place.  New files are then added via Models and to a baslist to replace the now missing files.

As you suggested, I initially thought the answer would be to have A and B and C, and force the user to pick one.  However, as the Select One options isn't able to force selection, and will even allow skipping the selection, ATM, I went a different route.  I removed all of the files that might get overwritten from the base pack file, then split the optional replacements in to more parts, and set a part that would always be the base, another option that would add a file that would overwrite some files, a different one to additionally overwrite others.

Overall, I'm happy with the workaround I've got in place, in fact, it might be the better way to do things.  However, it was more difficult for me to break things up and make it happen this way, than it would have been if I could have just said, here is the base Option A has higher priority than the base, and Option B has higher priority than Option A.

I think this is a somewhat niche FR, and I wouldn't press hard for the feature.

**Comment by NiceneNerd** [comment]
I managed to add require single selects: will that suffice here?

**Comment by t3nk3y** [comment]
I think the required singe select goes a long way.  However, if not putting this process in the hands of the modder, to decide, I think a documentation update that, at least, says "Don't do this" or "If you do this, here is what will happen" would really help.

This will let modders know they should not put in multiple options that make changes to non-mergable files.  Maybe I should just open a different FR for documentation to bring more clarity around the merging process with options.

Make it clear the core mod files go in first and options overwrite those.  I'm still left wondering what specific rules there are around packs as well.  As an example, I'm not sure which files are files that will be merged(TitleBG, for instance will be merged), and which ones will simply overwrite(And sbfres, as an example seems to get completely overwritten, even though other tools can break that down in to parts).  Which things will be handled in logs?  If a single file is handled by logs in the core, and again in options, do both sets of changes get merged?

That kind of stuff.  If you want I'll open an FR for things that I think would help modders gain clarity on how BNPs and BCML work.

**Comment by NiceneNerd** [comment]
> Make it clear the core mod files go in first and options overwrite those. I'm still left wondering what specific rules there are around packs as well. As an example, I'm not sure which files are files that will be merged(TitleBG, for instance will be merged), and which ones will simply overwrite(And sbfres, as an example seems to get completely overwritten, even though other tools can break that down in to parts). Which things will be handled in logs? If a single file is handled by logs in the core, and again in options, do both sets of changes get merged?

To answer this specifically, for packs it's as simple as SARCs can get merged but no other archive format (simply because only SARC has good Python libs). Things that go into logs are whatever kinds of content have a dedicated merger, a full list of which can be seen in the remerge menu, advanced options, or here: https://github.com/NiceneNerd/BCML/blob/master/bcml/mergers/__init__.py#L138. This stuff is discussed briefly in the BNP help docs: https://github.com/NiceneNerd/BCML/blob/master/docs/bnp.md#workings-of-a-bnp

If there is anything more specific that should go in the docs, I'd welcome a PR. BNPs and their logs were never really designed to be edited manually, but if it is useful to some, more documentation is not out of the question

**Comment by t3nk3y** [comment]
I'm not really looking to mess with the BNP files themselves, but to understand how to structure the folders of my mod to best achieve functionality/compatibility, especially with options in mind.  I've seen enough of what gets put in the BNP's by BCML to know how to modify the contents of what is in a BNP to get the results I want, but I feel like I shouldn't be doing that, and understanding how BCML converts the folder and contents to BNP would help with that.

Specifically speaking of SARC files.  The sbeventpack is a SARC file, but I don't think BCML is breaking that down, and re-assembling it in to minimal parts.  When these get added, they seem to have the full contents of the file supplied by the mod.  I'm working with one mod right now that would be way easier to work on if BCML would export these files to BNP's that contain only the minimum of what is needed to re-construct the archives.  This is especially helpful when doing what I am doing, which is converting Wii U mods to Switch mods, as I'm looking to find the differences, and if BCML did 90% of the work for me, that's just wonderful. (along those lines, a standalone app for diffing BOTW data could be super handy, and you built a strong framework for that already)

It sounds like BCML should already be breaking down sbeventpack's diffing, and outputting only what's changed, for the BNP.  Maybe this is the only format where it's working.  Or maybe I only thing it's not working, and I'm wrong.  I will double check later tonight when I have time.

Anyway it goes, this feel progressively off topic for this issue, so I'm going to close this one, and I'll open another to gather info from you, and will then convert what I learn to docs and put up a PR with those docs once I have them together.  I can't really build it till I have a full understanding, but I can save you the trouble of having to explain things repeatedly.

**Comment by NiceneNerd** [comment]
> The sbeventpack is a SARC file, but I don't think BCML is breaking that down, and re-assembling it in to minimal parts. When these get added, they seem to have the full contents of the file supplied by the mod.

To clarify, some SARCs have merging disabled if merging them tends to cause serious problems, and event packs are among them.
