### ISSUE TITLE
Feature Request: Export BNP to build directory.

### ISSUE THREAD

**Issue by t3nk3y** [NiceneNerd/BCML#194]
The idea here is to have a way to take a BNP, and produce the folder structure needed to turn it's extracted contents in to the structure needed to re-create the BNP.  As is, it's practically there, except, the logs are not de-constructed back to files.  I would think these should get deconstructed to the minimal files needed to re-create the BNP.

This would be very helpful for mod maintainers, as we would have a solid footing to stand on when producing updates to BNPs.  It wouldn't be so bad if we were keeping git repositories with a build structure, but the contents of the mods are likely a no-go on free/open source git hosts, so having a way to put the build structure back in place is super helpful.

Again thanks, and I swear this is the last FR for tonight.

**Comment by NiceneNerd** [comment]
I'm not clear on this one: is this supposed to do something fundamentally different than the BNP->standalone tool?

**Comment by t3nk3y** [comment]
Yes, the BNP->standalone doesn't seem to support options at all, for one, so it wont export the directory structure needed to re-create the various options, and, two, it produces assets that are full size, not just the files that have been changed.  Having these diff only assets to work with, is really helpful for organizing through mod work, IMO.

I'm basically looking for the exact same thing as is found in the BNP, except that the logs would also be merged in to the files they are effecting.  But they would preferably do so in a minimal way.  So, for instance, if the log modifies something in a TitleBG, it wouldn't export an entire TitleBG with all of the assets.  Just like how the TitleBG that is stored in a BNP when there are actual files that have to be stored, will only have those changed files in it, I would like the exported TitleBG(as an example) to only contain the sub files that were modified by the logs(and if there are changed files as well, those should go there.)

**Comment by GingerAvalanche** [comment]
Given the fact that BCML is at EOL, and the fact that its successor UKMM won't use the log-based diff format, I'm going to close this.
