### ISSUE TITLE
Creating a BNP does not overwrite destination BNP if BNP exists

### ISSUE THREAD

**Issue by t3nk3y** [NiceneNerd/BCML#196]
When creating a BNP file from BCML, if the BNP exists, the file picker will ask if we want to overwrite the file.  If we say Yes, instead of the file being overwritten, an "Add" operation is performed in 7z, and this adds or updates new or changed files, but does not delete any files from the 7z that are not in the source directory.

This means that any files you remove from your mod, will not get removed from the destination BNP if it already exists, instead of the expected behavior of the BNP being completely overwritten with a new one based on the source path.

Can you add something around line 437 of dev.py to check if file exists, and delete it if it does, before creating the new BNP?
https://github.com/NiceneNerd/BCML/blob/5b4a5115098e79985daae2f06408d48367866858/bcml/dev.py#L437

Something like this, I didn't modify and create a PR, as I don't see the os library being loaded in BCML, and am not sure if you would want to use it here, or have another library you prefer to use to work with existance/removal of files:
```py
    print(f"Saving output file to {str(output)}...")
    if os.path.exists(str(output)):
        os.remove(str(output))
    x_args = [util.get_7z_path(), "a", str(output), f'{str(tmp_dir / "*")}']
```

**Comment by ArchLeaders** [comment]
Oh, yeah. I was going to report that. Forgot to though. Thanks
