### ISSUE TITLE
[Feature Request] Code Patch Merging Optimizations

### ISSUE THREAD

**Issue by Torphedo** [NiceneNerd/BCML#197]
I was recently tinkering with code patch BNPs, and was annoyed by how slow it was to test installing them (to see if the options were working). I was thinking, similar to my previous issue about disabled mods not needing a remerge when uninstalling, code patches could be made much faster by skipping a full remerge if the selected BNP has only a patches folder. So, if you installed a code patch BNP, BCML would push the code patch to Cemu, but not remerge since no assets were touched. (Same on uninstall)

**Comment by GingerAvalanche** [comment]
Do Cemu code patches use more than one asm file per graphic pack? If not, you've never needed to remerge, as files have been linked from source location to graphic pack folder (and so any changes to the source would be reflected there)
