### ISSUE TITLE
Installing multiple mods with options at once, via the queue, only asks options for 1 mod

### ISSUE THREAD

**Issue by t3nk3y** [NiceneNerd/BCML#198]
If you attempt to install more than one mod at a time, and multiple of those mods have options, BCML should be presenting options from each of the mods.  However, it only shows the options for a single mod.  All mods do install, but I'm not sure what options it installs for the other option laden mods.

The setup in this image only showed options for Girly Animation Pack, but not for Zelda's Ballad Switch
![image](https://user-images.githubusercontent.com/26716328/136135413-3421d06f-134b-4511-8643-1377da4e85e9.png)

**Comment by NiceneNerd** [comment]
Fixed in 12167ff37da3c715fc7df0da912265430e69d728
