### ISSUE TITLE
Bcml won't launch (White screen)

### ISSUE THREAD

**Issue by Lollilollo04** [NiceneNerd/BCML#206]
Hello, I was installing second wind mod, but bcml crashed and now everytime i try to open It i get a White screen and bcml won't load, i tried reinstalling It and moving the bcml folder from appdata, any ideas on how to fix It? btw i'm on Windows 10, thanks.

**Comment by NiceneNerd** [comment]
I've never been able to replicate this error, so I've no idea what the problem is. Probably solvable by running `pip install cefpython3`, though

**Comment by Lollilollo04** [comment]
![Uploading IMG_20211112_140420.jpg…]()
It Is still like this even After i installed cefpython3

**Comment by NiceneNerd** [comment]
There's no image

**Comment by NiceneNerd** [comment]
Try running `bcml-debug` and watching the console for errors.

**Comment by Lollilollo04** [comment]
I opened bcml-debug and After 15 seconds It worked, thanks, i close.
