### ISSUE TITLE
No language are displayed to be selected during setup

### ISSUE THREAD

**Issue by DpKBulb** [NiceneNerd/BCML#219]
![image](https://user-images.githubusercontent.com/31826297/143729170-ab6462fc-df90-4875-bb93-b961a28a2fc6.png)

Hello, as you can see in this screenshot of my window, I don't have any language displayed in the dropdown. It blocks me at this step. 

Installed on Win10 x64
Python 3.8 provide in the zip archive on gamebanana

**Comment by NiceneNerd** [comment]
Do the language packs actually exist in the base+update folder, under `Pack/Bootup_XXxx.pack`?

**Comment by DpKBulb** [comment]
![image](https://user-images.githubusercontent.com/31826297/143729693-d7c30fa0-2f06-488a-b796-acf7baf28b9d.png)

Yep just found it, in the rofs folder

**Comment by NiceneNerd** [comment]
Does it work after restarting BCML and resetting the folders?

**Comment by NiceneNerd** [comment]
Oh, one thing I noticed that's probably not related: your current settings will delete your whole game dump the first time you try to install a mod.
