### ISSUE TITLE
everytime i try to install bcml i get an error with visual studio c++ 14.0

### ISSUE THREAD

**Issue by undertalez9** [NiceneNerd/BCML#222]
![image](https://user-images.githubusercontent.com/76131060/145459570-1e14383b-8d92-41a4-bdda-b8621f586d52.png)

**Comment by Torphedo** [comment]
install Python 3.7 or 3.8, and don't use the Microsoft Store. Not sure if it's relevant to this particular error but 3.9 will not work

**Comment by undertalez9** [comment]
> 

it happened again.

**Comment by ArchLeaders** [comment]
Install Visual C++ Runtime https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by Torphedo** [comment]
oh yeah, that'd do it

**Comment by undertalez9** [comment]
> Install Visual C++ Runtime https://aka.ms/vs/17/release/vc_redist.x64.exe

i already installed that, finally i installed bcml with 3.7 bc 3.10/3.9/3.8 was giving that error

**Comment by Torphedo** [comment]
oh yeah, 3.10 won't work either

**Comment by GingerAvalanche** [comment]
>  ![image](https://user-images.githubusercontent.com/76131060/145462156-3785c280-8fbc-4ecc-a5e9-2bcbb610899b.png)

This screenshot shows that the installation is happening with a version of Python downloaded from the Microsoft Store. Download Python from the Python website. The Microsoft Store versions will always fail with BCML - the path they install to is too long, and Windows will break when trying to install BCML

**Comment by GingerAvalanche** [comment]
![image](https://datatofish.com/wp-content/uploads/2018/10/0001_add_Python_to_Path.png)

Reinstall Python from the exe and check this box.

**Comment by undertalez9** [comment]
> ![image](https://camo.githubusercontent.com/42954d7b1c4f3b3f7f8c11464d733b6543a6b9c135629df2a200fbd39dfcc6a6/68747470733a2f2f64617461746f666973682e636f6d2f77702d636f6e74656e742f75706c6f6164732f323031382f31302f303030315f6164645f507974686f6e5f746f5f506174682e706e67)
> 
> Reinstall Python from the exe and check this box.

now i get this error 
![image](https://user-images.githubusercontent.com/76131060/145463662-a49ffbf0-052c-43f7-83c0-adbe6f981ef6.png)

**Comment by NiceneNerd** [comment]
Dude, that's 32 bit Python

**Comment by ArchLeaders** [comment]
That was a picture from Ginger though.

**Comment by NiceneNerd** [comment]
It's still what he used, per the error

**Comment by ArchLeaders** [comment]
Right

**Comment by GingerAvalanche** [comment]
I probably shouldn't have used a random picture I found on the internet. Even with the red box, the intent was probably missed.
