### ISSUE TITLE
Unable to update BCML 

### ISSUE THREAD

**Issue by TheTrueShadow** [NiceneNerd/BCML#225]
Traceback (most recent call last):
  File "E:\BCML\pkgs\bcml\_api.py", line 49, in status_run
    data = func(*args, **kwargs)
  File "E:\BCML\pkgs\bcml\_api.py", line 738, in update_bcml
    raise RuntimeError(result.stderr)
RuntimeError: ERROR: Could not install packages due to an EnvironmentError: [WinError 5] Access is denied: 'e:\\bcml\\pkgs\\_yaml.cp37-win_amd64.pyd'
Consider using the `--user` option or check the permissions.

![Screenshot 2021-12-11 183338](https://user-images.githubusercontent.com/80232013/145694871-d675f5bf-31fc-4344-94c7-4b0022631947.png)

**Comment by GingerAvalanche** [comment]
Try closing bcml, opening a command prompt (start menu, search `cmd`), and running `pip install -U bcml`

**Comment by TheTrueShadow** [comment]
https://youtu.be/tvprpF2qU-U
That is the video of what happens after the install and I have the latest versions of python C++ and everything else

**Comment by TheTrueShadow** [comment]
> Traceback (most recent call last): File "E:\BCML\pkgs\bcml_api.py", line 49, in status_run data = func(*args, **kwargs) File "E:\BCML\pkgs\bcml_api.py", line 738, in update_bcml raise RuntimeError(result.stderr) RuntimeError: ERROR: Could not install packages due to an EnvironmentError: [WinError 5] Access is denied: 'e:\bcml\pkgs\_yaml.cp37-win_amd64.pyd' Consider using the `--user` option or check the permissions.
> 
> ![Screenshot 2021-12-11 183338](https://user-images.githubusercontent.com/80232013/145694871-d675f5bf-31fc-4344-94c7-4b0022631947.png)
--------------------------------------------------------------------------------------------------------------------------------------------
https://youtu.be/tvprpF2qU-U
That is the video of what happens after the install and I have the latest versions of python C++ and everything else

**Comment by NiceneNerd** [comment]
What version do you have right now?
