### ISSUE TITLE
Error: Neither CEF...

### ISSUE THREAD

**Issue by Scubayogi** [NiceneNerd/BCML#226]
Hi,
when loading after install I get the following error, any ideas?
Thanks so much for any help!

![image](https://user-images.githubusercontent.com/96073706/145853367-43125020-de97-4f8e-9b99-2397a14e5433.png)

**Comment by Scubayogi** [comment]
Oh, needless to say, I did the WebVeiw 2 install but got the same error multiple times...

**Comment by HGStone** [comment]
please run this at the cmd line
pip install cefpython3

**Comment by Scubayogi** [comment]
Worked like a charm! Thank you so much for the quick response!

Happy holidays!

**Comment by Torphedo** [comment]
I should add this to my installer script

**Comment by Spark9999** [comment]
yes thnx i faced the same issue. worked . cheers.

**Comment by NiceneNerd** [comment]
It still *shouldn't* be necessary to install CEF, though. Not sure what's going on with Edge.
