### ISSUE TITLE
error trying to install/convert mod

### ISSUE THREAD

**Issue by floofycat** [NiceneNerd/BCML#23]
Hi! I updated from Cemu 1.15.0 to 1.15.18, and see that a mod I once made now requires BCML and a .bnp file on gamebanana or it stays hidden. I downloaded the installer version of BCML, but whenever I try to either install my mod from graphicPacks folder, or click on the Create BNP mod button, all i get is this error:
BCML has encountered an error while performing an operation. Error details:
Traceback (most recent call last):
File "C:\Users.........\BCML\pkgs\bcml\install.py" , line 240, in generate_logs
merger.log_diff(tmp_dir, modded_files)
File ".....data.py" line 708, in generate_diff
actor_info=byml.Byml(util.decompress_file(str(actor_file))).parse()
File ".....byml.py" line 72, in __init__
raise Value Error(Invalid version: %u-wiiu (expected 1-3) % version)
ValueError: Invalid version: 1-wiiu (expected 1-3)

Please help! I feel like I'm missing some valuable step in the process, something that needs to be done to my mod that worked pre-BCML to get it to work now...

**Comment by NiceneNerd** [comment]
This means your mod includes an actor info file corrupted by an outdated BYML tool.

**Comment by floofycat** [comment]
Thank you! Do you happen to know how I could fix that?

**Comment by NiceneNerd** [comment]
You can try to rebuild your actor info from a fresh copy, and this time edit it using [`byml`](https://zeldamods.org/wiki/Help:Tools/byml-v2) or [Wild Bits](https://zeldamods.org/wiki/Help:Tools/Wild_Bits).

**Comment by floofycat** [comment]
Ok, I'll search and try to find out how to do that. I only ever made the 1 mod and that was hard enough then lol, I've forgotten it all already. Thanks again!  =)
