### ISSUE TITLE
Neither CEF nor Edge Webview 2 is available

### ISSUE THREAD

**Issue by alexblaauw** [NiceneNerd/BCML#230]
I tried installing BCML using the pip install command, only to receive this message. The odd thing is, I have Edge Webview 2, and even after BCML tries to install it for me, I still get the error. Building from source made no difference. I decided to post here as I saw nobody else having this issue. Is there anything I can do?

**Comment by Torphedo** [comment]
run `pip install cefpython3`

**Comment by alexblaauw** [comment]
Thanks for the quick response!
I missed #226 when I searched through the closed issues earlier. My bad.
Though the pip install works now, the version I installed from the repo still gives the same error, oddly enough. That might be worth looking into.
