### ISSUE TITLE
Issue with MelonSpeedruns randomizer

### ISSUE THREAD

**Issue by SalamenceLvX** [NiceneNerd/BCML#232]
I am trying to create a BNP of melonspeedruns randomizer and am getting the following error 
[message.txt](https://github.com/NiceneNerd/BCML/files/7740219/message.txt)

**Comment by GingerAvalanche** [comment]
It's hard to say what to do about this error. The error is happening on decompress - which means that bcml's backing library can't even open one of the archives from the mod. This isn't really an error with bcml, it's an error between the backing library and the mod.

It doesn't say what file is causing the error, though, so it'd be hard to make any further progress on it, without that. Is the MelonSpeedruns randomizer available somewhere now?

**Comment by SalamenceLvX** [comment]
I can send a discord link, is tha tallowed?
