### ISSUE TITLE
Nothing but white screen on Fedora 35

### ISSUE THREAD

**Issue by ghost** [NiceneNerd/BCML#235]
**Description** 
Launching bcml produces a window that is just white. Like so 
![Screenshot from 2021-12-23 23-20-38](https://user-images.githubusercontent.com/54917666/147319882-b80848a4-e285-4f61-96c3-ca5d6268efc6.png)

**Steps to reproduce**
Install python 3.9.9, then use pip to install bcml as per the official instructions. Run bcml through the python 3.9.9 installation.

**Notes**
If I run `python3.9 -m bcml bcml-debug` I get 
```
[pywebview] Using Qt 5.15.2

DevTools listening on ws://127.0.0.1:8228/devtools/browser/0c3b636e-4937-41fe-946d-4de77bab1249
Remote debugging server started successfully. Try pointing a Chromium-based browser to http://127.0.0.1:8228
```
Then if I hit `Ctrl+c` I get
```
Traceback (most recent call last):
  File "/home/USER/.local/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/USER/.local/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/USER/.local/lib/python3.9/site-packages/bcml/_server.py", line 17, in start_server
    httpd.serve_forever()
  File "/home/USER/.local/lib/python3.9/socketserver.py", line 232, in serve_forever
    ready = selector.select(poll_interval)
  File "/home/USER/.local/lib/python3.9/selectors.py", line 416, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt
```
I know nothing when it comes to programming so any help would be appreciated.

**Comment by NiceneNerd** [comment]
Try right-clicking the white screen and then clicking Reload or Refresh or whatever

**Comment by BoloDragonheart** [comment]
Right clicking does nothing, unfortunately. Thank you for the response. Is there anything else I can do or try?

**Comment by NiceneNerd** [comment]
Try using a venv

**Comment by BoloDragonheart** [comment]
The venv produces the same result. I've gotten Fedora 35 on a virtual machine running and done the same things and gotten the same results, so I don't think this is an issue with my machine, but with Fedora in general. Or I'm installing things improperly. I don't know. I'll try installing on some VMs of other distros later to be sure. Thank you for helping. If there's anything else I can do, I'm willing to try.

**Comment by stayupthetree** [comment]
try `pip install cefpython3`

**Comment by nezd5553** [comment]
I found a workaround for using BCML on Fedora 35 that involves running it in a Flatpak sandbox. I installed the [VSCode Flatpak from Flathub](https://flathub.org/apps/details/com.visualstudio.code), opened a terminal in VSCode (Ctrl+Shift+\`), and installed BCML with `python -m pip install bcml`. Then I was able to run it with `python -m bcml`.

**Comment by Vii-GitHub** [comment]
> I found a workaround for using BCML on Fedora 35 that involves running it in a Flatpak sandbox. I installed the [VSCode Flatpak from Flathub](https://flathub.org/apps/details/com.visualstudio.code), opened a terminal in VSCode (Ctrl+Shift+`), and installed BCML with `python -m pip install bcml`. Then I was able to run it with `python -m bcml`.

Tried the same thing (I'm on Silverblue, but shouldn't matter since it's a Flatpak anyway), and It's telling me `webview.util.WebViewException: You must have either QT or GTK with Python extensions installed in order to use pywebview.`. 
I tried building from source, installing another Python version locally (since 3.10 won't work), which lead to the issue above, tried installing in a Pop!Os 22.04 VM, same issue. I managed to get it running in a Ubuntu 20.04 VM, but it can't deal with a mounted WebDav share from my Main OS, so it can't access the game files, and copying would take ages. I also tried switching to the Fedora Kionite Image with KDE, but the issue above persists.

**Comment by Vii-GitHub** [comment]
> I found a workaround for using BCML on Fedora 35 that involves running it in a Flatpak sandbox. I installed the [VSCode Flatpak from Flathub](https://flathub.org/apps/details/com.visualstudio.code), opened a terminal in VSCode (Ctrl+Shift+`), and installed BCML with `python -m pip install bcml`. Then I was able to run it with `python -m bcml`.

I had to also run `pip install qtpy` for it to work, but it's working great! Thank you so much.
