### ISSUE TITLE
Can't pass the BCML "Path" SETUP

### ISSUE THREAD

**Issue by ShadoGiow** [NiceneNerd/BCML#236]
Hello guys!
I've trying to setup BCML for my switch.

I've installed everything correctly, but now i've a problem on setup the path folders.

I have done a dump of both game+update and dlc, added the folder path to the program correctly (with the green V) but when I choose to save the setting, the program said:

`Your settings are not valid and cannot be saved. Check that all required fields are completed and green before submitting. If you have trouble, consult the in-app help.`

BUT, as you can see, everything is in them place correctly I think. Below a photo with my setup.

Other infos:
-Yes, the dump are legal, done with my cartridge
-Yes, the dump are full, i've checked the dungeon000 thingy
![bha dio porco](https://user-images.githubusercontent.com/96622025/147353817-d315ccff-011a-4d8d-8db0-de5b94cf3d3d.png)

![bha dio cane](https://user-images.githubusercontent.com/96622025/147353882-b199afd1-f96a-4858-a485-d4ef1d0069d2.png)

**Comment by Torphedo** [comment]
It's probably because it's in OneDrive, if I had to guess

**Comment by NiceneNerd** [comment]
OneDrive is incompatible with Python
