### ISSUE TITLE
BCML will no longer open after CEMU update 

### ISSUE THREAD

**Issue by CKingsin** [NiceneNerd/BCML#237]
Hey, I have run into a huge problem. I was playing BOTW with mods just fine a while ago, but then I realized I was unable to use my D-Pad buttons in game after updating CEMU, so I close my game and go to recalibrate my controller in CEMU thinking that would fix it. I relaunch BOTW and nothing was fixed. After trying to relaunch after fixing my controls again, my BOTW crashed so I checked my BCML settings and nothing was wrong. BOTW kept crashing from this point on, so I restarted my computer after checking my CEMU/BCML settings once more. Ever since this reboot, my BCML refuses to open. I just got an error file on my desktop after trying to open BCML that I will link. I have reinstalled everything to try and fix this, but nothing works. I have been searching for any fixes that anyone may have and seeing if anyone had a similar problem for almost 2 hours now, but no luck. My BOTW works just fine, so it seems BCML/Python is the problem here. Any ideas as to how I can fix this?
[error.log](https://github.com/NiceneNerd/BCML/files/7776919/error.log)

**Comment by NiceneNerd** [comment]
Just delete your BCML settings file and  start over

**Comment by CKingsin** [comment]
I think I already tried that. I will give it another go and see if things work afterwards

**Comment by NiceneNerd** [comment]
It's also possible it will never work if that `bcml.exe` is in your OneDrive. Python hates OneDrive.

**Comment by CKingsin** [comment]
I never save anything to OD unless its for a temporary backup

**Comment by CKingsin** [comment]
Where do I find my BCML settings file?

**Comment by NiceneNerd** [comment]
In that error the `bcml.exe` file is in OneDrive.

The settings file is ordinarily in `%LOCALAPPDATA%\bcml\`.

**Comment by CKingsin** [comment]
Thats odd. I put my BCML exe in my Python folder and have a copy on my desktop. I'll have to see if something happened when I get back on my PC. Also thank you for the information and assistance so far I will reply later should I need anything else or if it does get fixed.

**Comment by CKingsin** [comment]
> Just delete your BCML settings file and start over

This was part of my problem. My mlc path got messed up and I had to redo my CEMU from scratch, but now everything seems to be back to normal. Thank you so much for all of the help. Have a good rest of your day and happy holidays!
