### ISSUE TITLE
Explore button opens invalid path when Python is installed from Microsoft Store

### ISSUE THREAD

**Issue by Lesking72** [NiceneNerd/BCML#240]
Clicking the explore directory button in the Mods tab attempts to open `C:\Users\<user>\AppData\Local\bcml\...` while the MS Store version of python puts the BCML folder in `C:\Users\<user>\AppData\Local\Packages\PythonSoftwareFoundation.Python.<version>\LocalCache\Local\bcml\...`

**Comment by Torphedo** [comment]
I'm surprised it even allowed you to install it with the Microsoft Store version

**Comment by Lesking72** [comment]
I ran into some errors installing dependencies because [long path support](https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation) needs to be enabled but otherwise it works fine (using Python 3.8, of course)

**Comment by Torphedo** [comment]
You'd probably be better off just re-installing Python from their site, not much reason to use the Microsoft Store version

**Comment by NiceneNerd** [comment]
Torph is right, using the MS Store version frequently causes issues and is not supported for that reason.
