### ISSUE TITLE
problem when creating a mod with BCML BNP Creator

### ISSUE THREAD

**Issue by wuslang** [NiceneNerd/BCML#244]
during the process it removes packs.json contains in logs folder

**Comment by Torphedo** [comment]
Maybe it's no longer needed? Does the lack of a `packs.json` break anything?

**Comment by wuslang** [comment]
Yes it breaks mods that have it

**Comment by NiceneNerd** [comment]
Why is there a `packs.json` file before you make the BNP? There shouldn't even be a logs folder before making a BNP.
