### ISSUE TITLE
"Create BCML Shortcuts" buttons do nothing

### ISSUE THREAD

**Issue by Makonede** [NiceneNerd/BCML#246]
When attempting to use either of said buttons to create a corresponding shortcut, nothing happens. I had to manually create shortcuts.

**Comment by NiceneNerd** [comment]
I've not been able to reproduce this in the past. As far as I can tell there is no *reliable* way to make Windows shortcuts from Python, just stuff that works for some people and not others.

**Comment by GingerAvalanche** [comment]
Closing as resolved, shortcut buttons now use Rust and are reported working
