### ISSUE TITLE
Need help. Mods not showing up in game.

### ISSUE THREAD

**Issue by Mellow-S** [NiceneNerd/BCML#258]
I have installed bcml for cemu correctly it launches and installs mods, but nothing changes in game. All my paths are correct I have it checked in the graphics packs. i really dont know what the issues is I've been asking everywhere I can think of. I am only trying one mod so It's not a mod conflict either I am lost.

**Comment by GingerAvalanche** [comment]
Things to try (try them in order, as each one is more time consuming than the last):
1) Make sure the BCML graphics pack is enabled in the Cemu graphic packs

2) Make absolutely sure the Cemu path in BCML's settings is correct. (Out of every 10 people we get saying "I've set the paths correctly," 9 of them did not set them correctly.)

3) -Close Cemu
-Close BCML
-Reopen BCML
-Remerge in BCML
-Try number 1 again

4) Delete your Cemu settings.xml file then retry number 3 (including retrying number 1)

**Comment by Mellow-S** [comment]
Bro.... i seriously love you i have tried all of the thing you listed besides number 4 but that worked ive spent hours just for it to be that one file i really appreciate it man no one else would even help me and all the fixes i tried did not work.

>
