### ISSUE TITLE
v2.6.2: FileNotFoundError: [Errno 2] No such file or directory: 'docs/README.md'

### ISSUE THREAD

**Issue by yoosefi** [NiceneNerd/BCML#26]
`docs/README.md` is not bundled with the released tarball. Installing from source or pip fails.

**Comment by NiceneNerd** [comment]
Installing from pip was working with the wheel. But there we go, just fixed it: [Commit](https://github.com/NiceneNerd/BCML/commit/a7f7f18810c8e33eadcc11eff4b19d7584e25f24) and [updated release](https://github.com/NiceneNerd/BCML/releases/tag/v2.6.2)
