### ISSUE TITLE
BCML.exe won't run. FATAL ERROR in Launcher

### ISSUE THREAD

**Issue by ChetLegend** [NiceneNerd/BCML#264]
BCML seemed to install everything it needed. Pictures of files added to show this.
When I come to run BCML it says it cannot find the specified file. 

Running python 3.8 which came with the 'BCML getting started' file

![dnpYpTFYYo](https://user-images.githubusercontent.com/85112889/154681718-07ca724d-5d9e-42d6-9f23-0f11361b2e37.png)
.
![explorer_ZhULK92kUC](https://user-images.githubusercontent.com/85112889/154682061-40210dd4-df28-4c70-a6a7-7156a7c0c42b.png)

**Comment by Torphedo** [comment]
run `bcml` in a command prompt, not the python console. also does the python executable it complains about exist?

**Comment by ChetLegend** [comment]
> run `bcml` in a command prompt, not the python console. also does the python executable it complains about exist?
![brave_iYOO4jwAvm](https://user-images.githubusercontent.com/85112889/154694017-743cd223-7e23-4081-9511-4b98fcb04854.png)

It still gives the same error and the file is in the python directory

![explorer_MojwLTtN5v](https://user-images.githubusercontent.com/85112889/154694161-c02087b5-eca2-4a91-b30a-05e39b864ea1.png)

**Comment by NiceneNerd** [comment]
This is generally the result of your Python installation getting messed up at some point, has nothing to do with BCML itself. You would probably be best off scrubbing Python from the system entirely in every last trace and reinstalling.
