### ISSUE TITLE
bcml not downloading itself

### ISSUE THREAD

**Issue by Pulseinfinity** [NiceneNerd/BCML#269]
when I use python to get bcml it appears to work like I saw in the tutorial video but when I type bcml I get 
'bcml' is not recognized as an internal or external command, operable program or batch file.

**Comment by Pulseinfinity** [comment]
nevermind im just dumb

**Comment by bellisonoroff** [comment]
> nevermind im just dumb

hey im dumb atm can you tell me what it was
