### ISSUE TITLE
Stuck on Whitescreen on latest Arch

### ISSUE THREAD

**Issue by skylabhalo** [NiceneNerd/BCML#278]
Been trying this for 3 hours now without any result
The first hour I was stuck by even getting this build I tried pipx which fails then I used asdf to setup multiple python versions and that worked but when trying to launch bcml I'm stuck on this stupid white screen
I tried all the solutions I found in the Issues Tab and I didn't get it working so far tried venv and that also results in a white screen and then I tried building from aur but that also fails to build
Debug doesn't help all debug will show is this:
```
[pywebview] closing event is deprecated and will be removed in 4.0. Use events.closing instead
[pywebview] Using Qt 5.15.2

DevTools listening on ws://127.0.0.1:8228/devtools/browser/715de17f-3b49-4152-8526-2e27593c58ff
Remote debugging server started successfull
Try pointing a Chromium-based browser to http://127.0.0.1:8228
```
![Screenshot_20220313_162348](https://user-images.githubusercontent.com/97119552/158066964-3956ab96-69e4-4178-814d-657a59f17b3d.png)

**Comment by HGStone** [comment]
this might work.

`pip uninstall pywebview[qt]
pip install pywebview[gtk]`

**Comment by skylabhalo** [comment]
nope :c

**Comment by Nitr4m12** [comment]
Try running `sudo pacman -S gobject-introspection`, and then `pip install PyGObject`. After that, do what HGStone said

**Comment by skylabhalo** [comment]
I got it running by installing it with Aur and editing some pkginfo's now most mods work but certain ones (like the xbox ui mod) won't install and crashes bcml.
```
Registered new object after initialization, existing clients won't be notified!
js: [object Object]
/usr/include/c++/11.2.0/bits/stl_vector.h:1045: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>; std::vector<_Tp, _Alloc>::reference = unsigned char&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__n < this->size()' failed.
Aborted (core dumped)
```

**Comment by grinness** [comment]
Hi,

I am having the same issue (stuck on white screen) with both Arch and Manjaro
I am using virtualenv with python 3.8 (from AUR -- also tested with same results with python 3.7 from AUR)

I have installed gobject-introspection (with pacman) and PyGObject (pip install in the env)
If I try, as suggested above:

`pip install pywebview[gtk]`

I get:
`no matches found: pywebview[gtk]`

Note that bcml worked up to few months ago on both Arch and Manjaro ,  bcml installed using pip under python 3.8 virtual env.

Any advice?
(building bcml-git from AUR does not work as Arch is currently on python 3.10

Thanks

**Comment by grinness** [comment]
Hi,

is there anyone that can provide some advice?

I also tested bcml-debug (as indicated in https://github.com/NiceneNerd/BCML/issues/206) but got same result:

* bcml windows is white and blank
* debug widow on http://127.0.0.1:8228/  shows only a title ('Inspectable pages'), but the page is white and blank

Thanks

**Comment by Lightsockie** [comment]
> this might work.
> 
> pip uninstall pywebview[qt]
> 
> pip install pywebview[gtk]

(`pywebview[gtk]` pulled in

With the additional step of `pip uninstall qtpy` (all in the venv, of course), from https://github.com/NiceneNerd/BCML/issues/218#issuecomment-1125928016 , I was able to get the white screen to go away and bcml to load.

Also on Arch (actually Artix, btw), and using `python38` from the AUR. (The `bcml-git` AUR package seems to be busted for a while?)


Having some problems getting my config settings to save (despite the inputs giving the green checkmarks) that _might_ be visual errors from swapping qt to gtk, and might just be user error on my end as I try to figure out this interface for usage with the console. Worth noting tho
> `Your settings are not valid and cannot be saved. Check that all required fields are completed and green before submitting. If you have trouble, consult the in-app help.`

**Comment by NiceneNerd** [comment]
So apparently some of this is related to a similar bug in other programs (such as Calibre's ebook viewer) that use a Qt webview, and one possible fix is to set an environmental variable: `QTWEBENGINE_DISABLE_SANDBOX=1 `

**Comment by Snogard** [comment]
@skylabhalo do you happen to have an nvidia graphics card? qt sandboxing is well known issue with those cards unfortunately.
