### ISSUE TITLE
Unable to open file explorer, permission problem?

### ISSUE THREAD

**Issue by rabidgoat** [NiceneNerd/BCML#280]
Hello, First thank you for making this, its awesome.

I previously had bcml working well, then sometime after I changed a drive letter that was referenced by cemu and bcml. I reinstalled python, then reinstalled bcml.
now that bcml is installed I can only open it with admin priveliges and when it is open I cannot browse at all. 

I am practically 1.5 steps above a script kid and I dont know where to start when trying to solve this so any help would be greatly appreciated.

**Comment by ArchLeaders** [comment]
Not sure what a script kid is, but anyway; when you say you "changed a drive letter that was referenced by cemu and bcml", do you mean you moved your game dump and updated the reference paths to the new locations? or...
- Move Cemu and update BCML Cemu's reference path?
- Rename the drive that these programs were installed on?
- Something else
