### ISSUE TITLE
Not Sure What I'm Doing Wrong

### ISSUE THREAD

**Issue by rhyscis** [NiceneNerd/BCML#284]
Hi! Let me preface this by saying I'm very new at this, and was just following along with the video tutorial. When I type "install pip bcml" in Command Prompt, the following message appears: 

'pip' is not recognized as an internal or external command,
operable program or batch file.

I have installed Python 3.8.8 64-bit and am running Windows 10. Not sure what I'm doing wrong, so any help is much appreciated! Thank you!

**Comment by ArchLeaders** [comment]
It's `pip install bcml` not `install pip bcml`.
But based on the error you only typed it wrong in GitHub. The error means that Python is not added to PATH.
To add it to PATH, modify the install; under the advanced setup click `Add Python to environment variables` then click the install button.

**Comment by rhyscis** [comment]
Yes, I meant "pip install bcml" LOL.
I uninstalled and reinstalled Python and made sure to select add to PATH, and still I keep getting the same error message when I type "pip install bcml" in Command Prompt.

**Comment by ArchLeaders** [comment]
What happens when you type `python --version` in cmd?

**Comment by rhyscis** [comment]
It comes up as "Python 3.8.8"

**Comment by ArchLeaders** [comment]
Try running these commands to install pip.

```
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python get-pip.py
```

If it still does not work, you will need to add the Scripts folder to the environment variables manually.

Open the Control panel and navigate to `Edit system environment variables` (or type `environment` in search and it should come up)
![image](https://user-images.githubusercontent.com/80713508/159801327-5198f1c8-06f9-4aa4-9156-2bab74a998a1.png)

Click on `Environment Variables`
![image](https://user-images.githubusercontent.com/80713508/159801406-a36a017a-5073-40f2-86ec-66d36548d368.png)

Scroll down to `Path` and click `Edit`
![image](https://user-images.githubusercontent.com/80713508/159801486-79d43471-4217-404c-a212-91d25bd35ecf.png)

In the new window look for the python directory, double click it, and copy the text to the clipboard.
![image](https://user-images.githubusercontent.com/80713508/159801679-7ab100a6-5bc3-4e19-8249-b08d276cf753.png)

Then click `New` and paste the clipboard into the new entry. Then append `Scripts\` to the end of the field.
![image](https://user-images.githubusercontent.com/80713508/159801843-339faba0-9b05-4630-8a50-8919c0f1b30f.png)

**Comment by rhyscis** [comment]
I pasted the following into Command Prompt and this is what showed up:

curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2596k  100 2596k    0     0  3000k      0 --:--:-- --:--:-- --:--:-- 3001k

C:\Users\chris>python get-pip.py
Defaulting to user installation because normal site-packages is not writeable
Collecting pip
  Downloading pip-22.0.4-py3-none-any.whl (2.1 MB)
     ---------------------------------------- 2.1/2.1 MB 5.2 MB/s eta 0:00:00
Collecting setuptools
  Downloading setuptools-60.10.0-py3-none-any.whl (1.1 MB)
     ---------------------------------------- 1.1/1.1 MB 5.7 MB/s eta 0:00:00
Collecting wheel
  Downloading wheel-0.37.1-py2.py3-none-any.whl (35 kB)
Installing collected packages: wheel, setuptools, pip
  WARNING: The script wheel.exe is installed in 'C:\Users\chris\AppData\Roaming\Python\Python38\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts pip.exe, pip3.8.exe and pip3.exe are installed in 'C:\Users\chris\AppData\Roaming\Python\Python38\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pip-22.0.4 setuptools-60.10.0 wheel-0.37.1


And still when I typed "pip install bcml" it still says the original error message. And the error message still appeared after I manually added the Scripts folder to the environment variables.

**Comment by ArchLeaders** [comment]
It's likely that you made a typo when adding the path then. I'd double-check that you have a value leading to `C:\Users\chris\AppData\Roaming\Python\Python38\Scripts` (make sure it gets saved).

If it _**still**_ doesn't work after that, then you can open a cmd in the scripts directory and run the commands from there.

**Comment by rhyscis** [comment]
Hi, that seemed to work. Thanks so much for your help!

**Comment by ArchLeaders** [comment]
Sure thing!

P.S. you should close this issue now that it's been resolved
