### ISSUE TITLE
Is it possible to install on Steam Deck?

### ISSUE THREAD

**Issue by wstratton26** [NiceneNerd/BCML#287]
I've been trying to install BCML onto the Steam Deck but I just do not have enough understanding to make it work. I tried going through the AUR route with yay as the Steam Deck is running a version of Arch Linux but I just can't get it installed. I've also tried following tutorials for installing it with pip & pipx to no avial. I'm not sure if it's an issue that the Steam Deck has Python 3.10.x installed? Any insight would be super helpful, I'm super lost.

**Comment by ArchLeaders** [comment]
You need Python 3.7 or 3.8 to install/run BCML.

**Comment by NiceneNerd** [comment]
Python 3.10 might work on Steam Deck (since it's Linux), but I can only confirm success with 3.9. Try using pyenv to install and use something between 3.7 and 3.9.

**Comment by ttay24** [comment]
@wstratton26 check out this little guide: https://www.reddit.com/r/SteamDeck/comments/uv922p/tutorial_installing_bcml_breath_of_the_wild/

I was able to successfully get it running. If you install the flatpak version of VS Code, it has Python 3.9 built into the terminal. You can use that version of python to install BCML.

Also (separate question from above), which dependencies require Python 3.9, and won't run on 3.10?
