### ISSUE TITLE
BCLM Browse button in plus button submenu does nothing when pressed.

### ISSUE THREAD

**Issue by DalMo1409** [NiceneNerd/BCML#288]

**Comment by DalMo1409** [comment]
![image](https://user-images.githubusercontent.com/83739699/160973979-e5ab746b-25fe-43be-a4a1-69bf330b4a52.png)

**Comment by NiceneNerd** [comment]
This probably means you somehow ended up with a Python installation that doesn't include Tkinter. Try `pip install tk`
