### ISSUE TITLE
python version problem

### ISSUE THREAD

**Issue by thunderpants** [NiceneNerd/BCML#29]
My python updated to Python 3.8.1 final .
Mod manager won't work ,says it needs the 3.7 Python version.
But i'm sure the instructions said BCML needs 3.7 or later.
I like to keep my software up-to-date ,not sure why BCML won't work with the new Python release.
I have bcml_2-6-2_setup.exe installed.
I noticed another 2.7 version? on pypi:
https://pypi.org/project/bcml/#files

sidenote :Seems to be different BCML versions out there on some sites.
Pretty sure NexusMods had an old version.
What is the official site to get latest BCML from ,gamebanana ? I noticed it there too.

**Comment by NiceneNerd** [comment]
PySide2 and `aamp` have both had problems with Python 3.8, and as such BCML won't work on 3.8 until both are fixed.

Also, yeah, I've not really kept up with the Nexus releases. PyPI always has the latest, and GameBanana *usually* does, though I haven't uploaded 2.7 there yet.
