### ISSUE TITLE
can't open bcml after in-app update

### ISSUE THREAD

**Issue by poekaa** [NiceneNerd/BCML#291]
Ever since bcml updated from within the app, it just closed and I haven't been able to open it since. I've tried reinstalling both python and bcml but that didn't fix it. I'm not really too sure what to do.

**Comment by ArchLeaders** [comment]
This is because the new update removed something that one file is still trying to use.

Run [this](https://cdn.discordapp.com/attachments/606813647674540032/959218950649020506/BCML_Fixer.exe) on your PC to fix it.

**Comment by poekaa** [comment]
Thank you! That fixed it, I really appreciate it.

**Comment by GingerAvalanche** [comment]
Reopening this solely so that people can see it instead of making new issues about the same thing - at least until we can get a new build out.

**Comment by ArchLeaders** [comment]
It's an issue with `__version__.py` now. I don't see it in the source code though.
```py
_MAJOR=3
_MINOR=8
_PATCH="3"
@id:vxna.one-dark-nx # random invalid decorator?
VERSION = f"{_MAJOR}.{_MINOR}.{_PATCH}"
USER_VERSION = f"""{_MAJOR}.{_MINOR}.{_PATCH[0:1]} {
    'alpha' if _MAJOR < 1 else ''
}{
    f'beta {_PATCH[_PATCH.rindex("b") + 1:]}' if 'b' in _PATCH else ''
}{
    f'release candidate {_PATCH[_PATCH.rindex("rc") + 2:]}' if 'rc' in _PATCH else ''
}"""
```

**Here's the 3.8.3 fix: [BCML_3.8.3_Fixer.exe](https://cdn.discordapp.com/attachments/606813647674540032/959276573142421554/BCML_3.8.3_Fixer.exe)**

**Comment by ArchLeaders** [comment]
Update: I see it now

**Comment by ArchLeaders** [comment]
Looks like this is resolved now!
