### ISSUE TITLE
How to make it work with Yuzu emulator?

### ISSUE THREAD

**Issue by LifeIsStrange** [NiceneNerd/BCML#296]
Yuzu has excellent BOTW support and support mods.
However I can't setup BCML, I say to BCML that I am on switch mode, then for the game folder I give the path
C:\Users\steph\OneDrive\Desktop\switchgame\TLOZ-BOTW-(RF)-NSwTcH-NSP-Ziperto
This folder contains the following NSP file:
The Legend of Zelda Breath of the Wild [01007EF00011E000][v0].nsp

On BCML the input does not goes green. I don't know what to do.
@NiceneNerd friendly ping

**Comment by NiceneNerd** [comment]
It's all in the help.

**Comment by LifeIsStrange** [comment]
@NiceneNerd No it's not, I have read the troubleshooting, it says I need to set a path to the romfs but I don't have a romfs, I have a NSP...

**Comment by NiceneNerd** [comment]
That's in the help, too

**Comment by Torphedo** [comment]
Also you should buy the game, I'm 99.9% sure this is a pirated copy based on the folder name.
