### ISSUE TITLE
Cannot open BCML after trying to update

### ISSUE THREAD

**Issue by SneezyWeavile** [NiceneNerd/BCML#297]
BCML notified me it had an update, so I let it try to update. It never reopened itself like it usually does, and trying to start it from anywhere results in nothing happening. I've tried uninstalling and reinstalling BCML (unsuccessfully), and I'm completely lost as to what I should do.

**Comment by ArchLeaders** [comment]
try running `pip install --force-reinstall bcml` in cmd and see if it works after that.

**Comment by asom905** [comment]
same problem, cant open bcml. When i do that option it says access denied

**Comment by ArchLeaders** [comment]
> same problem, cant open bcml. When i do that option it says access denied

Run cmd as admin. This is usually caused when python is installed somewhere that requires admin.
