### ISSUE TITLE
Where do i find DLC? i cant find DLC patch anywhere AT ALL. does anybody know how to get this? i don't wanna mod my switch either so shush mr. i think im so smart.

### ISSUE THREAD

**Issue by collinator-coder** [NiceneNerd/BCML#300]
yeah man i need help with wiiusbhelper on linux

**Comment by collinator-coder** [comment]
PS: i dont have windows

**Comment by HGStone** [comment]
have you tried this? https://tinyurl.com/z6e6bwjk

**Comment by NiceneNerd** [comment]
Definitely not helping you with piracy questions

**Comment by ArchLeaders** [comment]
> yeah man i need help with wiiusbhelper on linux

WiiU USB Helper is illegal, we can't help you with that.<br><br>

You should check these links for hacking your switch and dumping the game: [Dumping Games](https://zeldamods.org/wiki/Help:Dumping_games/#Switch) | [Switch Hacking Guide](https://switch.homebrew.guide/)
