### ISSUE TITLE
Text mods is not merged correctly when using Chinese game language

### ISSUE THREAD

**Issue by SoapSoul** [NiceneNerd/BCML#302]
I am using the Japanese game version and replaced the contents into Chinese with patch, when modding a mod with text included, the game text cannot display correctly. After I remove the Bootup_JPja.pack from the merged folder the text became correct but the text from mods will be blank.

This is the patch I used: https://drive.google.com/file/d/1vV4ejpxNcjaQcMCjjzMOQ2YLtxXHzyUy/view

**Comment by GingerAvalanche** [comment]
Isn't there a Chinese language already in the game? I thought that was what Bootup_CNzh.pack contained.

To clarify the problem you're having: The text in Bootup_JPja.pack works fine *in Japanese*, but using a mod to change the text to Chinese is what does not work?

**Comment by SoapSoul** [comment]
No, the game doesn't allow us to change language to any CN / ZH, so we have a patched version of Bootup_JPja with chinese content to replace the original Bootup_JPja.


This is the image WITHOUT Bootup_JPja.pack in BreathOfTheWild_BCML:
![Screenshot 2022-04-10 193314](https://user-images.githubusercontent.com/34182225/162616087-1a3a50e4-d651-4bb2-a511-9b08af37e4e2.png)
I manually deleted the Bootup_JPja.pack in BreathOfTheWild_BCML to display normal Chinese Traditional text without the mod text.

This is the image WITH merged Bootup_JPja.pack in BreathOfTheWild_BCML:
![Screenshot 2022-04-10 193430](https://user-images.githubusercontent.com/34182225/162616090-e2278e30-46f1-4b7e-958b-717a340744fc.png)
All the text has changed to display incorrect Japanese text with the mod text

**Comment by NiceneNerd** [comment]
You mean you patched your original game itself?

**Comment by SoapSoul** [comment]
> You mean you patched your original game itself? Because game files which are modified in any way are not supported at all.

I see.  I thought the loader is using the bootUp file in the base game to merge, but I found out it is using a static text_refs to merge the text.  I unpacked text_refs and replaced the content of JPja with TWzh and repack, and the merging has no problem now.

**Comment by GingerAvalanche** [comment]
Seems to me like this is working as intended
