### ISSUE TITLE
Unable to launch BCML 

### ISSUE THREAD

**Issue by Apo35310** [NiceneNerd/BCML#304]
Hello, I'm trying to launch BCML on my Windows 10 PC.

I have dowload the program and run it a first time everything was good.

But I try to run it today but it run into this error :

![image](https://user-images.githubusercontent.com/103412139/162688901-5074da84-30a8-4910-8c5e-f83c085f8b1d.png)

I already install WebVIwe2 and when I close the Edge window, this append :

![image](https://user-images.githubusercontent.com/103412139/162688833-3eed43ee-352d-4965-80d8-d24605ca63d2.png)

I don't know why it's doesnt work and if this error was already fixed, but i need help

**Comment by ArchLeaders** [comment]
Run `pip install cefpython3` in cmd.

**Comment by Apo35310** [comment]
It worked !

Now I can update it and install some mods to have fun

Thank you =)

**Comment by Apo35310** [comment]
PS : The update worked too, it launch normally, I will ask you again if i'm in trouble

In any case, thanks =)
