### ISSUE TITLE
BCML simply won't start

### ISSUE THREAD

**Issue by firstretromaster** [NiceneNerd/BCML#31]
I've installed BCML 10 times with the 2 first method and the application won't start. When I double click on the application or write BCML on the command promp, nothing happens. Since all the mods on GamesBanana required BCML, I can't install any mod...

**Comment by qqq1701** [comment]
Same issue. Installs but won't run. Tried each version back to 2.6.2. Issue seems to be once you got to 2.7.x.

**Comment by NiceneNerd** [comment]
New dependency that I didn't realize at first. Install the [Visual C++ 2015-2019 redist](https://aka.ms/vs/16/release/vc_redist.x64.exe).
