### ISSUE TITLE
RuntimeError: Broken toolchain: cannot link a simple C program

### ISSUE THREAD

**Issue by Johtoboy** [NiceneNerd/BCML#311]
RuntimeError: Broken toolchain: cannot link a simple C program
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

I know it says that the problem is not the pip, but does anyone know how to fix this error?

**Comment by ArchLeaders** [comment]
What python version do you have? (You can find out with `pip -V`)

**Comment by Johtoboy** [comment]
Python 3.10

**Comment by NiceneNerd** [comment]
There's your problem
