### ISSUE TITLE
legacy-install-failure

### ISSUE THREAD

**Issue by Johtoboy** [NiceneNerd/BCML#312]
note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> syaz0

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

      CMake Error at CMakeLists.txt:2 (project):
        Failed to run MSBuild command:

          MSBuild.exe

        to get the value of VCTargetsPath:

          MÃ¤Ã¤ritettyÃ¤ tiedostoa ei lÃ¶ydy
         (the specified file cannot be found)

How do I fix this?

**Comment by HGStone** [comment]
are you still using python 3.10?

**Comment by Johtoboy** [comment]
No
