### ISSUE TITLE
BCML opens blank window

### ISSUE THREAD

**Issue by lisa-wolfgang** [NiceneNerd/BCML#313]
I installed BCML on my Ubuntu 21.10 via Python 3.9.7 and `pip install bcml` as described in the README, but when entering `bcml` into the terminal, I get a blank window and these logs:
```
[pywebview] closing event is deprecated and will be removed in 4.0. Use events.closing instead
[pywebview] QT cannot be loaded
Traceback (most recent call last):
  File "/home/me/.local/lib/python3.9/site-packages/webview/guilib.py", line 29, in import_qt
    import webview.platforms.qt as guilib
  File "/home/me/.local/lib/python3.9/site-packages/webview/platforms/qt.py", line 30, in <module>
    from qtpy import QtCore
ModuleNotFoundError: No module named 'qtpy'
EGLDisplay Initialization failed: EGL_NOT_INITIALIZED
Cannot create EGL context: invalid display (last error: EGL_SUCCESS)

```
I tried installing qtpy (`pip install qtpy`) and then running `bcml`, but just get these logs instead:
```
[pywebview] closing event is deprecated and will be removed in 4.0. Use events.closing instead
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted (core dumped)
```
I've also tried the other install methods described in the README, but they all result in the same thing.

Running `sudo bcml` loads the UI correctly, but it's unable to write a settings file due to the root user not having a home directory to put it in.

**Comment by NiceneNerd** [comment]
Have you recently had a Qt update, and if so have you rebooted since it?

**Comment by lisa-wolfgang** [comment]
I believe there was a recent system update, but I don't know if it updated Qt. I now remember that BCML was running fine before I rebooted for the first time after this update.

**Comment by NiceneNerd** [comment]
The life of Qt bindings is a very annoying and often finnicky one. Check the comments on #202 for more stuff people have tried with issues along these lines.

**Comment by lisa-wolfgang** [comment]
I tried using `pyenv` to switch the Python version to 3.7, no luck there.

Upon reading related issues again, I stumbled upon this comment, which I had not noticed before: https://github.com/NiceneNerd/BCML/issues/265#issuecomment-1046397611

Following these steps, I think I at least made some headway in that I don't get as many errors as before. Now, upon opening the application, I get a blank screen and these logs:
```
[pywebview] closing event is deprecated and will be removed in 4.0. Use events.closing instead
EGLDisplay Initialization failed: EGL_NOT_INITIALIZED
Cannot create EGL context: invalid display (last error: EGL_SUCCESS)
```

I tried bcml-debug and it looked like there was stuff in there when inspecting, but it wasn't rendering anything visible.

**Comment by NiceneNerd** [comment]
See what happens if you run like so: `WEBKIT_DISABLE_COMPOSITING_MODE=1 bcml-debug`

**Comment by lisa-wolfgang** [comment]
That worked great! It also worked with the regular `bcml` command, and I was able to successfully complete setup without any further problems.

I'll leave this issue open for others who encounter this problem as well. (I could also PR these troubleshooting steps to the README/docs if that's something you'd be open to.)

Thank you for your time and patience!
