### ISSUE TITLE
Broke CEF renderer

### ISSUE THREAD

**Issue by GingerAvalanche** [NiceneNerd/BCML#323]
#317 fixed pywebview, broke cefpython. Linking #316 in here cuz the most recent post from that is actually this issue.

Solution: check which renderer is being used before subscribing to the closing event, maybe?

**Comment by GingerAvalanche** [comment]
@AgentOtter run the command `pip install -U pywebview cefpython3` and then try opening bcml again. I believe you just have an outdated version of pywebview

**Comment by AgentOtter** [comment]
Yes that fixed it, thank you.
