### ISSUE TITLE
Extended Memory Mod Botw

### ISSUE THREAD

**Issue by NuggetBoy420** [NiceneNerd/BCML#329]
for some reason when I try and enable extended memory this error pops up.  
<img width="667" alt="image" src="https://user-images.githubusercontent.com/100390147/167231673-4db4d912-8def-4fc3-af22-b0956a7e4060.png">
anyone know how to help with this?

**Comment by NiceneNerd** [comment]
Why are you installing the extended memory pack into BCML?

**Comment by GingerAvalanche** [comment]
For clarity, the extended memory pack is a code patch. BCML doesn't handle code patches because those are *already* merged. At runtime. By Cemu.
