### ISSUE TITLE
Problems installing new mods 

### ISSUE THREAD

**Issue by RXElier** [NiceneNerd/BCML#342]
I'm having problems installing mods where bcml tells me that it can't find any rules.txt or info.json and it doesn't install it, I know that the problem is not the mods because previously it installed them fine

**Comment by GingerAvalanche** [comment]
What format is the mod in? (zip, bnp, loose files)

**Comment by RXElier** [comment]
Bnp format

**Comment by GingerAvalanche** [comment]
What’s the full stack trace you get when the error happens?

**Comment by RXElier** [comment]
never mind I fixed it, apparently the problem was due to one of my personal projects in python that interfered with the process of writing the mods in the bcml folder
