### ISSUE TITLE
BCML get's stuck on loading

### ISSUE THREAD

**Issue by boygaymer** [NiceneNerd/BCML#345]
I just updated to the newest version of BCML (3.9.5) but now it gets stuck on any loading screen. When I install mods, it just sits there "installing". If I close the program and reopen it, sometimes the mod will be installed but I have one that just won't. Either way, even when I manage to get mods on there, when I try to export them, it just gets stuck loading and never exports. I tried reinstalling but that didn't work. I was just using bcml yesterday and it worked fine until I updated.

**Comment by NiceneNerd** [comment]
Run with `bcml-debug` and post the output

**Comment by boygaymer** [comment]
I think I did it right? Let me know. Thank you for your help!

Microsoft Windows [Version 10.0.19044.1706]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Boygaymer>bcml-debug
[pywebview] Using WinForms / CEF

DevTools listening on ws://127.0.0.1:60694/devtools/browser/15a09ebc-39a8-4718-bb5f-89423245ed7e
CEF window with uid master does not exist
CEF window with uid master does not exist
VERBOSE[
  {
    "name": "Own a House in Tarry Town",
    "date": "06/03/2022 9:14 PM",
    "priority": 100,
    "path": "C:\\Users\\Boygaymer\\AppData\\Local\\bcml\\mods_nx\\0100_OwnaHouseinTarryTown",
    "disabled": false,
    "id": "T3duIGEgSG91c2UgaW4gVGFycnkgVG93bj09MS4wLjA="
  },
  {
    "name": "Own a House in Tabantha",
    "date": "06/03/2022 9:15 PM",
    "priority": 101,
    "path": "C:\\Users\\Boygaymer\\AppData\\Local\\bcml\\mods_nx\\0101_OwnaHouseinTabantha",
    "disabled": false,
    "id": "T3duIGEgSG91c2UgaW4gVGFiYW50aGE9PTEuMC4w"
  }
]
VERBOSEBcmlMod(name="Own a House in Tabantha", path="C:/Users/Boygaymer/AppData/Local/bcml/mods_nx/0101_OwnaHouseinTabantha", priority=101)

**Comment by GingerAvalanche** [comment]
You did enter the command correctly, and that's the start of the output, but it's not the part we need. When you try to install a mod in debug mode, it should have a lot more output.

Try it again and install something. The console should have something printed at least once every 5 seconds until it either hangs or finishes installing. If it doesn't finish installing, and doesn't print anything for 5 seconds, copy the last 20-30 lines that were printed and paste them here.

**Comment by boygaymer** [comment]
Omg yeah, I think I realized that as I was falling asleep last night XD. So here's me installing the mod that won't finish:

Microsoft Windows [Version 10.0.19044.1706]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Boygaymer>bcml-debug
[pywebview] Using WinForms / CEF

DevTools listening on ws://127.0.0.1:63930/devtools/browser/5542c31f-d587-4616-856a-6337df9ff0ab
CEF window with uid master does not exist
CEF window with uid master does not exist
VERBOSE[
  {
    "name": "Own a House in Tarry Town",
    "date": "06/03/2022 9:14 PM",
    "priority": 100,
    "path": "C:\\Users\\Boygaymer\\AppData\\Local\\bcml\\mods_nx\\0100_OwnaHouseinTarryTown",
    "disabled": false,
    "id": "T3duIGEgSG91c2UgaW4gVGFycnkgVG93bj09MS4wLjA="
  },
  {
    "name": "Own a House in Tabantha",
    "date": "06/03/2022 9:15 PM",
    "priority": 101,
    "path": "C:\\Users\\Boygaymer\\AppData\\Local\\bcml\\mods_nx\\0101_OwnaHouseinTabantha",
    "disabled": false,
    "id": "T3duIGEgSG91c2UgaW4gVGFiYW50aGE9PTEuMC4w"
  }
]
VERBOSEBcmlMod(name="Own a House in Tabantha", path="C:/Users/Boygaymer/AppData/Local/bcml/mods_nx/0101_OwnaHouseinTabantha", priority=101)
VERBOSE{
  "mods": [
    "C:\\Users\\Boygaymer\\Downloads\\climber_bandana_alt_v4.bnp"
  ],
  "options": {
    "disable": [],
    "options": {}
  },
  "selects": null
}
Opening mod...
Looks like an older mod, let's upgrade it...
Converting meta file...
Upgrading old logs...
Upgrading RSTB log...
Finding modified files...
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error("invalid type: null, expected path string", line: 3, column: 18)', src\settings.rs:197:83
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Exception in thread Thread-15:
Traceback (most recent call last):
  File "c:\users\boygaymer\appdata\local\programs\python\python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "c:\users\boygaymer\appdata\local\programs\python\python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\boygaymer\appdata\local\programs\python\python38\lib\site-packages\webview\util.py", line 138, in _call
    result = func(*func_params.values())
  File "c:\users\boygaymer\appdata\local\programs\python\python38\lib\site-packages\bcml\_api.py", line 33, in status_run
    data = func(*args, **kwargs)
  File "c:\users\boygaymer\appdata\local\programs\python\python38\lib\site-packages\bcml\install.py", line 265, in do_and_refresh
    res = func(*args, **kwargs)
  File "c:\users\boygaymer\appdata\local\programs\python\python38\lib\site-packages\bcml\_api.py", line 380, in install_mod
    mods = [
  File "c:\users\boygaymer\appdata\local\programs\python\python38\lib\site-packages\bcml\_api.py", line 381, in <listcomp>
    install.install_mod(
  File "c:\users\boygaymer\appdata\local\programs\python\python38\lib\site-packages\bcml\install.py", line 296, in install_mod
    tmp_dir = open_mod(mod)
  File "c:\users\boygaymer\appdata\local\programs\python\python38\lib\site-packages\bcml\install.py", line 123, in open_mod
    upgrade.convert_old_mod(rulesdir, delete_old=True)
  File "c:\users\boygaymer\appdata\local\programs\python\python38\lib\site-packages\bcml\upgrade.py", line 48, in convert_old_mod
    convert_old_logs(mod)
  File "c:\users\boygaymer\appdata\local\programs\python\python38\lib\site-packages\bcml\upgrade.py", line 119, in convert_old_logs
    _convert_rstb_log(mod_dir)
  File "c:\users\boygaymer\appdata\local\programs\python\python38\lib\site-packages\bcml\upgrade.py", line 143, in _convert_rstb_log
    files = install.find_modded_files(mod, pool=pool)
  File "c:\users\boygaymer\appdata\local\programs\python\python38\lib\site-packages\bcml\install.py", line 195, in find_modded_files
    for f in rsext.find_modified_files(str(tmp_dir), util.get_settings("wiiu"))
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: Error("invalid type: null, expected path string", line: 3, column: 18)

**Comment by boygaymer** [comment]
And here I did the same thing with another one:

Microsoft Windows [Version 10.0.19044.1706]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Boygaymer>bcml-debug
[pywebview] Using WinForms / CEF

DevTools listening on ws://127.0.0.1:51828/devtools/browser/ed3bd98c-97f7-4d5a-95cf-ec9df40be480
CEF window with uid master does not exist
CEF window with uid master does not exist
VERBOSE[
  {
    "name": "Own a House in Tarry Town",
    "date": "06/03/2022 9:14 PM",
    "priority": 100,
    "path": "C:\\Users\\Boygaymer\\AppData\\Local\\bcml\\mods_nx\\0100_OwnaHouseinTarryTown",
    "disabled": false,
    "id": "T3duIGEgSG91c2UgaW4gVGFycnkgVG93bj09MS4wLjA="
  },
  {
    "name": "Own a House in Tabantha",
    "date": "06/03/2022 9:15 PM",
    "priority": 101,
    "path": "C:\\Users\\Boygaymer\\AppData\\Local\\bcml\\mods_nx\\0101_OwnaHouseinTabantha",
    "disabled": false,
    "id": "T3duIGEgSG91c2UgaW4gVGFiYW50aGE9PTEuMC4w"
  }
]
VERBOSEBcmlMod(name="Own a House in Tabantha", path="C:/Users/Boygaymer/AppData/Local/bcml/mods_nx/0101_OwnaHouseinTabantha", priority=101)
VERBOSE{
  "mods": [
    "C:\\Users\\Boygaymer\\Downloads\\malice_link_136_switch.bnp"
  ],
  "options": {
    "disable": [],
    "options": {}
  },
  "selects": null
}
Opening mod...
Identified mod: MaliceLink1.36switch
Loading mod logs...
Assigned mod priority of 102
Moving mod to C:\Users\Boygaymer\AppData\Local\bcml\mods_nx\0102_MaliceLink1.36switch...
VERBOSEInstalled 1 mods
Installed 1 mods
Cleansing old merges...
Refreshing merged mods...
Loading modded SARC list...
Merging 17 SARC files...
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error("invalid type: null, expected path string", line: 3, column: 18)', src\settings.rs:197:83
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Exception in thread Thread-15:
Traceback (most recent call last):
  File "c:\users\boygaymer\appdata\local\programs\python\python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "c:\users\boygaymer\appdata\local\programs\python\python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\boygaymer\appdata\local\programs\python\python38\lib\site-packages\webview\util.py", line 138, in _call
    result = func(*func_params.values())
  File "c:\users\boygaymer\appdata\local\programs\python\python38\lib\site-packages\bcml\_api.py", line 33, in status_run
    data = func(*args, **kwargs)
  File "c:\users\boygaymer\appdata\local\programs\python\python38\lib\site-packages\bcml\install.py", line 265, in do_and_refresh
    res = func(*args, **kwargs)
  File "c:\users\boygaymer\appdata\local\programs\python\python38\lib\site-packages\bcml\_api.py", line 392, in install_mod
    install.refresh_merges()
  File "c:\users\boygaymer\appdata\local\programs\python\python38\lib\site-packages\bcml\install.py", line 603, in refresh_merges
    merger.perform_merge()
  File "c:\users\boygaymer\appdata\local\programs\python\python38\lib\site-packages\bcml\util.py", line 462, in timed_function
    res = func(*args, **kwargs)
  File "c:\users\boygaymer\appdata\local\programs\python\python38\lib\site-packages\bcml\mergers\pack.py", line 206, in perform_merge
    rsext.mergers.packs.merge_sarcs(sarcs)
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: Error("invalid type: null, expected path string", line: 3, column: 18)

**Comment by boygaymer** [comment]
But that one shows the mod installed after closing and opening again:

Microsoft Windows [Version 10.0.19044.1706]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Boygaymer>bcml-debug
[pywebview] Using WinForms / CEF

DevTools listening on ws://127.0.0.1:55221/devtools/browser/5e4291e3-83ef-4269-b972-386bf705af0f
CEF window with uid master does not exist
CEF window with uid master does not exist
VERBOSE[
  {
    "name": "Own a House in Tarry Town",
    "date": "06/03/2022 9:14 PM",
    "priority": 100,
    "path": "C:\\Users\\Boygaymer\\AppData\\Local\\bcml\\mods_nx\\0100_OwnaHouseinTarryTown",
    "disabled": false,
    "id": "T3duIGEgSG91c2UgaW4gVGFycnkgVG93bj09MS4wLjA="
  },
  {
    "name": "Own a House in Tabantha",
    "date": "06/03/2022 9:15 PM",
    "priority": 101,
    "path": "C:\\Users\\Boygaymer\\AppData\\Local\\bcml\\mods_nx\\0101_OwnaHouseinTabantha",
    "disabled": false,
    "id": "T3duIGEgSG91c2UgaW4gVGFiYW50aGE9PTEuMC4w"
  },
  {
    "name": "Malice_Link_1.36_switch",
    "date": "06/04/2022 7:52 AM",
    "priority": 102,
    "path": "C:\\Users\\Boygaymer\\AppData\\Local\\bcml\\mods_nx\\0102_MaliceLink1.36switch",
    "disabled": false,
    "id": "TWFsaWNlX0xpbmtfMS4zNl9zd2l0Y2g9PTEuMC4w"
  }
]
VERBOSEBcmlMod(name="Malice_Link_1.36_switch", path="C:/Users/Boygaymer/AppData/Local/bcml/mods_nx/0102_MaliceLink1.36switch", priority=102)

**Comment by NiceneNerd** [comment]
Open `%LOCALAPPDATA%\bcml\settings.json` and replace all instances of `null` with `""`.

**Comment by boygaymer** [comment]
That worked! Turns out the one that wouldn't install is for wii u. Thank you so much for your help ♥
