### ISSUE TITLE
it processed successfully, but could not be added to your BCML mods

### ISSUE THREAD

**Issue by walrussmashbros** [NiceneNerd/BCML#35]
![Capture](https://user-images.githubusercontent.com/60533196/73586906-ae0c6180-4479-11ea-899f-0b3b0d9c5ba2.PNG)

I keep getting this error not sure what to do about it. I have all the correct directory locations, and have tried uninstalling and reinstalling many times. I have just been trying to install the Linkle mod.

**Comment by GingerAvalanche** [comment]
This is an issue with Cemu1.17.0e, being handled by #33 and #34 

Cemu1.17.0d and earlier don't have this. The latest version has a new way of handling graphic pack entries. I've made a fix for this, but it hasn't made it into any of the official releases. You can roll back to an earlier Cemu version, or you can visit the discord and try your luck obtaining the file that works and placing it in your bcml installation.

**Comment by savrahe** [comment]
Hi, same problem here, my version of Cemu is 1.15.10

**Comment by savrahe** [comment]
> Hi, same problem here, my version of Cemu is 1.15.10


Hello, for me it has been fixed, I have installed in the default directory (C) and not the custom one I was putting (D)

**Comment by walrussmashbros** [comment]
Thank you Ginger fixed it. :)
