### ISSUE TITLE
Language options missing

### ISSUE THREAD

**Issue by batboiben** [NiceneNerd/BCML#350]
As the title says. The only option in the drop-down list is the prompt of "Select a language".

**Comment by GingerAvalanche** [comment]
BCML can only choose from languages that your game/update dump has available. So, after you select your game dump path, BCML scans it for the language packs you have. If your update dump was chosen correctly, then the list of languages will populate.

Specifically, it happens when your typing cursor is inside the update dump input line and then you click somewhere else to make the typing cursor leave the update dump input line.

**Comment by batboiben** [comment]
> BCML can only choose from languages that your game/update dump has available. So, after you select your game dump path, BCML scans it for the language packs you have. If your update dump was chosen correctly, then the list of languages will populate.
> 
> Specifically, that population happens when your typing cursor is inside the update dump input line and then you click somewhere else to make the typing cursor leave the update dump input line.

I discovered this while troubleshooting. Thank you for the confirmation, still. It seems like I've opened up a new can of worms, though. It doesn't seem like the BCML loader actually supports BOTW switch modding. I've had to hunt for tutorials/advice that's actually helpful. (It's at least, very difficult to work with.)  
I'm resorting to using Yuzu to mod and merge with BCML, and then copying the game over to my switch. This is the easiest method so far. 
Sorry if I should have opened a new thread for this info or something. New to commenting on GitHub. Thanks.

**Comment by NiceneNerd** [comment]
I'm confused, what's the difficulty with using it with Switch? Install mods, click Export, extract to SD card, like it says in the help

**Comment by GingerAvalanche** [comment]
There's no difference between using switch mode and using wiiu mode without cemu.

Yuzu doesn't have a mod merger, it just overlays one mod on top of another, which often breaks one of them (which is the reason BCML exists in the first place.)

**Comment by batboiben** [comment]
> I'm confused, what's the difficulty with using it with Switch? Install mods, click Export, extract to SD card, like it says in the help

You're the dev so I respect your efforts, truly. But it's definitely not that easy. If you google basic questions about BCML and switch, there is a lot of confusion. It's not at all impossible but just to quote some forum titles; "Breath of the Wild modding, BCML, nightmares, please send help" (2/9/2022), "Don't use BCML for Switch" (3/24/2022), etc... After more reading, other people have found that the solution I came across was the easiest (which is much easier said than done), there are a lot of people figuring it out on their own (if they can) instead of being able to find direction VIA the actual developers. In many threads, there are a couple of recurring usernames that are considerably rude towards people asking for help. I'm guessing they're probably other devs for your project if they're so focused on BCML particularly. 

I know working on a project like this isn't easy, but I wish there were an official tutorial for BCML on the switch. I'm honestly so lost with answer sources that I almost want to write out a tutorial myself, to save other people the hours long struggles.

**Comment by NiceneNerd** [comment]
I'm just confused because the Help does specifically tell you what to do, and I'm asking which step mentioned in the help seems to be the issue.
