### ISSUE TITLE
Issues setting up BCML routing folders for update and DCL

### ISSUE THREAD

**Issue by gbombs223** [NiceneNerd/BCML#352]
I am trying to set up BCML for the first time, and the program is unable to find the correct DLC and Update directory.  I am able to assign the correct location of the Cemu and Base Game directory, but when BCML tries to autopopulate these directories I do not get green checks allowing me to proceed.

I have read the Second Wind Installation Guide written by Torphedo on github, and think the main issue is I do not have the "content" folders available to select, as they were not created when I initially installed the game or the update/DLC.  I tried to manually create these subfolders but the BCML installer will not take them when I do this.  Has anyone encounter this problem and know what I should do?  Do I need to reinstall BOTW or Cemu to make this work?  Both Cemu and BOTW work fine but I am unable to install mods at this point.

**Comment by ArchLeaders** [comment]
You just need to manually set the game paths. If the game runs in Cemu with the DLC, then the game files must be present in the `mlc01` folder.

**Comment by NiceneNerd** [comment]
You can always just right click the game in Cemu to find the update and DLC folders, then use the hints in the help to set them correctly from the folders that pop up.

**Comment by gbombs223** [comment]
Unfortunately that didn't seem to help.  I was able to locate the update directory, but when I manually added it I did not get a green checkmark.  Also, when I used the method you explain here, the DLC directory is grayed out which makes me wonder if its installed at all.  When I run BOTW in Cemu, the title screen shows I am running "DLC version 3.0", so I'm pretty sure its also installed.  Any idea what I should do?

**Comment by gbombs223** [comment]
Is there any other method by which I can add mods to BOTW without having to use BCML or is there a different mod loading program I can try?

**Comment by GingerAvalanche** [comment]
BCML is the only program of its kind. Other mod loaders simply replace archives, which breaks most mods unless you use only one mod at a time.

Mods are also often distributed in bnp (BCML-only) format, because bnp's are tiny when compared to standalone mods.

**Comment by NiceneNerd** [comment]
@gbombs223 There are only three possible explanations for this:
- You're putting the folders into BCML incorrectly (i.e. selecting it at the wrong part of the folder structure)
- Your game is missing files from the dump (unlikely if the game runs correctly)
- The game is on an unsupported file system (e.g. OneDrive)

To rule out the first, please post the update and DLC folders that Cemu opens, along with your BCML settings.
