### ISSUE TITLE
When Trying to install BCML i get the following error:

### ISSUE THREAD

**Issue by AM7999** [NiceneNerd/BCML#353]
Building on Manjaro ARM

things done before installing: `python -m venv bcml_env
source bcml_env/bin/activate # will activate the venv
pip install bcml`

 × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Querying qmake about your Qt installation...
      /bin/qmake -query
      These bindings will be built: QtWebEngineCore, QtWebEngine, QtWebEngineWidgets.
      Generating the QtWebEngineCore bindings...
      _in_process.py: /tmp/pip-install-m90kz0n8/pyqtwebengine_a81b745c06bc4e31a958b8ab185453a1/sip/QtWebEngineCore/QtWebEngineCoremod.sip: line 25 column 9: 'QtCore/QtCoremod.sip' could not be found
      /tmp/pip-install-m90kz0n8/pyqtwebengine_a81b745c06bc4e31a958b8ab185453a1/sip/QtWebEngineCore/QtWebEngineCoremod.sip: line 26 column 9: 'QtGui/QtGuimod.sip' could not be found
      /tmp/pip-install-m90kz0n8/pyqtwebengine_a81b745c06bc4e31a958b8ab185453a1/sip/QtWebEngineCore/QtWebEngineCoremod.sip: line 27 column 9: 'QtNetwork/QtNetworkmod.sip' could not be found
      /tmp/pip-install-m90kz0n8/pyqtwebengine_a81b745c06bc4e31a958b8ab185453a1/sip/QtWebEngineCore/qwebengineclientcertificatestore.sip: line 24 column 6: 'PyQt_SSL' is not a known qualifier
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by GingerAvalanche** [comment]
Looks like you might be trying to install on python 3.10, which is not supported. 3.7.4 and above, and any 3.8 and 3.9 are supported.

**Comment by NiceneNerd** [comment]
In addition to that I doubt it works on ARM at all

**Comment by AM7999** [comment]
> Looks like you might be trying to install on python 3.10, which is not supported. 3.7.4 and above, and any 3.8 and 3.9 are supported.

Alright

>in addition to that i doubt it works on ARM at all

I mean, i could still try

**Comment by NiceneNerd** [comment]
You can, but I'd bet against it

**Comment by syne0x** [comment]
i had the same error i removed python 3.10 from my path added 3.8.8 and then the installation worked perfectly fine

**Comment by AM7999** [comment]
> i had the same error i removed python 3.10 from my path added 3.8.8 and then the installation worked perfectly fine

And how would i go about that? @syne0x

**Comment by AM7999** [comment]
But it always seems like it always gets stuck at `pyqtwebengine`

**Comment by NiceneNerd** [comment]
Well, that's not surprising since it doesn't provide wheels for ARM
