### ISSUE TITLE
BCML just infinite loading

### ISSUE THREAD

**Issue by syne0x** [NiceneNerd/BCML#355]
When i install Linkle mod at bcml it just is literally infinitely loading when i restart the software and reopen the mod is there as "installed" but when i launch BotW just nothing changes the same goes for deleteing it again its infinitly after restart its gone

**Comment by linktlh** [comment]
Start BCML via command line using `bcml-debug` and reply w/ the output.

**Comment by syne0x** [comment]
when i run bcml-debug its instantly finished with this error and bcml is started up dont have enough time to install while its debuging

**Comment by syne0x** [comment]
well i tried something i ran the bcml-debug.exe in python's scripts folder while the infinite loading occured then i got this message:

Exception in thread Thread-1:
Traceback (most recent call last):
  File "c:\users\andyn\appdata\local\programs\python\python38\lib\site-packages\bcml\_oneclick.py", line 17, in listen
    sock.bind(("127.0.0.1", 6666))
OSError: [WinError 10048] Normalerweise darf jede Socketadresse (Protokoll, Netzwerkadresse oder Anschluss) nur jeweils einmal verwendet werden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\andyn\appdata\local\programs\python\python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "c:\users\andyn\appdata\local\programs\python\python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\andyn\appdata\local\programs\python\python38\lib\site-packages\bcml\_oneclick.py", line 19, in listen
    send_arg(sock)
  File "c:\users\andyn\appdata\local\programs\python\python38\lib\site-packages\bcml\_oneclick.py", line 37, in send_arg
    sock.sendall(sys.argv[1].encode("utf8"))
IndexError: list index out of range
[pywebview] Using WinForms / CEF

DevTools listening on ws://127.0.0.1:58885/devtools/browser/2e13333e-ba6a-4b9f-8ac6-95d3e0a9fd24
CEF window with uid master does not exist
CEF window with uid master does not exist
[0614/202946.130:ERROR:cache_util_win.cc(20)] Unable to move the cache: 5
[0614/202946.130:ERROR:cache_util.cc(134)] Unable to move cache folder C:\Users\Andyn\AppData\Local\bcml\cef_cache\GPUCache to C:\Users\Andyn\AppData\Local\bcml\cef_cache\old_GPUCache_000
[0614/202946.130:ERROR:disk_cache.cc(169)] Unable to create cache
[0614/202946.130:ERROR:shader_disk_cache.cc(601)] Shader Cache Creation failed: -2
[0614/202946.139:ERROR:cache_util_win.cc(20)] Unable to move the cache: 5
[0614/202946.139:ERROR:cache_util.cc(134)] Unable to move cache folder C:\Users\Andyn\AppData\Local\bcml\cef_cache\Cache to C:\Users\Andyn\AppData\Local\bcml\cef_cache\old_Cache_000
[0614/202946.140:ERROR:disk_cache.cc(169)] Unable to create cache
VERBOSE[
  {
    "name": "Linkle Mod",
    "date": "06/14/2022 8:29 PM",
    "priority": 100,
    "path": "C:\\Users\\Andyn\\AppData\\Local\\bcml\\mods\\0100_LinkleMod",
    "disabled": false,
    "id": "TGlua2xlIE1vZD09Mi42"
  }
]
VERBOSEBcmlMod(name="Linkle Mod", path="C:/Users/Andyn/AppData/Local/bcml/mods/0100_LinkleMod", priority=100)
VERBOSEBcmlMod(name="Linkle Mod", path="C:/Users/Andyn/AppData/Local/bcml/mods/0100_LinkleMod", priority=100)
VERBOSEBcmlMod(name="Linkle Mod", path="C:/Users/Andyn/AppData/Local/bcml/mods/0100_LinkleMod", priority=100)

( it instantly stopped doing the infinite loading thing) but still no changes to the game link's still link

**Comment by syne0x** [comment]
and when i try to disable the mod (just for testing reasons) it simply gets stuck at loading again

**Comment by GingerAvalanche** [comment]
Zip and upload your settings.json from `%localappdata%\bcml`

**Comment by syne0x** [comment]
its an 2 TB harddrive disk built into my pc

**Comment by syne0x** [comment]
basically where i put on everything i dont need to have on my ssd

**Comment by syne0x** [comment]
so what you want me to say is Internal drive i guess xd

**Comment by GingerAvalanche** [comment]
Are you trying to install the mod through one-click install? Or are you trying to install by downloading the file and then using the blue circle with a + inside it on the bottom right of the main BCML window?

**Comment by syne0x** [comment]
After the debug it shows up in the list but this background picture is glitched / not there when I run remerge an infinite loading occures once again but I’m sorry to tell you that I can’t take place here for now because I have to go to school rn and I’m writing an math test today in like 5-6 hours I will test everything you wrote in your last answer

**Comment by syne0x** [comment]
even when i tried debuging while the remerge was stuck it stopped / finished but still no changes ingame

**Comment by syne0x** [comment]
I NEED TO SAY THANKS FOR THE OFFER OF HELP BUT I FIGURED IT OUT


TO EVERYONE MEETING THIS ISSUE THE SIMPLE WAY TO FIX IT IS TO GO INTO BCML AND CHOOSE RUN SETUP WIZARD AT THE DROPDOWN AFTER DOING THAT SELECT AT LANGUAGE EU ENGLISH , THE ERROR WAS THAT I HAD GERMAN SELECTED AFTER THAT REMERGE THE MOD ( THE INFINITE LOADING WILL BE GONE ) WHEN U DID THIS LAUNCH THE GAME AND THE MOD WORKS PERFECTLY FINE!!!!!!!!!!!!

**Comment by syne0x** [comment]
fr i hate my country for the many issues you encounter when u try to use everything on german xd

**Comment by GingerAvalanche** [comment]
BCML should merge the german language fine. The expected behavior is that, if the mod doesn't contain a language pack for your chosen language, BCML should merge changes from a language that the mod *does* contain a pack for.

The only issue should be if you've chosen a different language in the settings for your console/cemu and in the settings for BCML. If those two don't match, then any text changed/added by the mod will be ignored by your console. But the mod should finish merging.

If you would like to help fix this issue, please start BCML via command line using `bcml-debug`, set your language to German again, attempt to install a mod, and then copy the output from the console - if the output is too long, copy the end of it.
