### ISSUE TITLE
not enough data for valid sarc fix?

### ISSUE THREAD

**Issue by kamikazilucas** [NiceneNerd/BCML#358]

**Comment by NiceneNerd** [comment]
No details?

**Comment by kamikazilucas** [comment]
wdym no details

**Comment by NiceneNerd** [comment]
You didn't put in any information whatsoever

**Comment by kamikazilucas** [comment]
when i add the mod for second wind it doesn't install instead it says not enough data for valid sarc and idk why

**Comment by NiceneNerd** [comment]
Post the full error details

**Comment by kamikazilucas** [comment]
![image](https://user-images.githubusercontent.com/20354993/173868442-b2d1da17-9035-42f4-8464-d073c45fceca.png)

**Comment by kamikazilucas** [comment]
its 0 kb

**Comment by NiceneNerd** [comment]
That's the problem; you'll need to get a valid version of the file
