### ISSUE TITLE
Errors while enabling/disabling mods, mods won't load

### ISSUE THREAD

**Issue by Paddels** [NiceneNerd/BCML#36]
Hey, I wanted to try out BCML, because it seemed a lot easier than how I installed mods before. I have the currently latest version of Cemu (1.17.1) and Version 2.7.3 of BCML.

I ran into some problems earlier, but I found solutions online to fix them. But for the problems I have now, I can't find a thing. When ever I install a mod, I get an error message as seen in the first picture. It sometimes doesn't have any problems and the mod shows up in my list, or I get an error but it shows up anyway.
Whenever I enable oder disable a mod, I get the error message seen in picture 2.
However when I try to start the game with the mods that worked, they aren't present in my game (won't load).

![20200208_164808](https://user-images.githubusercontent.com/60820534/74088223-208dca80-4a94-11ea-9e9c-17720a9c5312.jpg)

![20200208_162854](https://user-images.githubusercontent.com/60820534/74087992-d0156d80-4a91-11ea-8a5e-72d22a00bb20.jpg)

Edit: I have the same problems as in #35

I hope there is a solution for my problem I have. Thanks in advance.

**Comment by NiceneNerd** [comment]
The first error is from using a mod in some format BCML doesn't support. The latter should be fixed in by the latest release today.
