### ISSUE TITLE
BCML Crashes when trying to install mods

### ISSUE THREAD

**Issue by ShahRyan777** [NiceneNerd/BCML#366]
At first, my issue was with getting the mods to work with cemu, I temporarily fixed it. This fixed caused an overwrite to the cemu community graphics packs. I tried reverting the fix and now cemu crashes on mod download even after a fresh install of bcml.

The following is what the debugger reads when I install a mod. 

 "options": {
    "disable": [],
    "options": {}
  },
  "selects": null
}
Opening mod...
Looks like an older mod, let's upgrade it...
Converting meta file...
Identified mod: Exported BCML mod
VERBOSE{
  "disable": [],
  "options": {}
}
Scanning for modified files...
Finding modified files...
Found 1828 modified files...

The following is my BCML Information.

Name: bcml
Version: 3.9.11
Summary: A mod manager for The Legend of Zelda: Breath of the Wild
Home-page: None
Author: Caleb Smith
Author-email: None
License: None
Location: c:\users\ohare\appdata\local\programs\python\python38\lib\site-packages
Requires: botw-havok, byml, xxhash, botw-utils, numpy, pywebview, aamp, oead, pythonnet, pycrosskit, requests, rstb, PyYAML, cefpython3
Required-by:

**Comment by NiceneNerd** [comment]
Should be fixed as of 3.9.12
