### ISSUE TITLE
the launch button is gone

### ISSUE THREAD

**Issue by ShadowSlayerFX1** [NiceneNerd/BCML#368]
![image](https://user-images.githubusercontent.com/80198511/175815102-b703f14f-b170-444c-9292-56aba1b9cedd.png)

**Comment by NiceneNerd** [comment]
The launch button only appears if you have a valid Cemu folder set

**Comment by ShadowSlayerFX1** [comment]
but that dont work i have it installed where i have cemu installed and it dont works

**Comment by ShadowSlayerFX1** [comment]
nevermind
