### ISSUE TITLE
Winreg issue for linux

### ISSUE THREAD

**Issue by Furaihai** [NiceneNerd/BCML#37]
Hello,
It looks like while linux versions of the software exist for download BCML will not correctly run because of a winreg import (which is only valid when used in windows) that exists in line 880 of the util.py file:

`def create_schema_handler():
    import winreg
    with winreg.CreateKey(winreg.HKEY_CURRENT_USER, r'Software\Classes\bcml') as key:
        try:
            winreg.OpenKey(winreg.HKEY_CURRENT_USER, r'Software\Classes\bcml\shell\open\command',
                           0, winreg.KEY_READ)
        except (WindowsError, OSError):
            winreg.SetValueEx(key, 'URL Protocol', 0, winreg.REG_SZ, '')
            with winreg.CreateKey(key, r'shell\open\command') as key2:
                if (Path(os.__file__).parent.parent / 'Scripts' / 'bcml.exe').exists():
                    exec_path = Path(os.__file__).parent.parent / 'Scripts' / 'bcml.exe'
                elif (Path(__file__).parent.parent.parent / 'bin' / 'bcml.exe'):
                    exec_path = (Path(__file__).parent.parent.parent / 'bin' / 'bcml.exe')
                else:
                    return
                winreg.SetValueEx(key2, '', 0, winreg.REG_SZ, f'"{exec_path.resolve()}" "%1"')`

Has this ever been used successfully on linux? If so, I would like to know how to get around this winreg issue.

**Comment by Furaihai** [comment]
That's the error I get when BCML is installed using PIP anyway. When I try building from source I get an error within __init__.py
`Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    from bcml.__version__ import VERSION
  File "/home/flyhigh/BCML/bcml/__init__.py", line 37, in <module>
    class MainWindow(QtWidgets.QMainWindow, Ui_MainWindow):
NameError: name 'Ui_MainWindow' is not defined
`
Googling solutions hasn't helped me with this one either if anyone could be of assistance.

**Comment by NiceneNerd** [comment]
BCML does not as of yet support Linux. Linux support is coming in BCML 3, which I expect to release in a couple weeks.

**Comment by Furaihai** [comment]
> BCML does not as of yet support Linux. Linux support is coming in BCML 3, which I expect to release in a couple weeks.

Ah ok thank you. I'll be looking out for the linux release then.
