### ISSUE TITLE
some issues since last update

### ISSUE THREAD

**Issue by Rodorufoe1994** [NiceneNerd/BCML#370]
1-BCML will upload infinitely now
2-installing, merging or removing mods will cause crash
3-BCML now displays an error stating "no storage folder found"
is anyone having these issues? It was perfectly fine up until I updated the app, how can I solve this?

**Comment by NiceneNerd** [comment]
Are you sure you're on 3.9.12?

Also, post your setting?

**Comment by GingerAvalanche** [comment]
We're on 3.9.17 now, and these things have almost certainly been affected by changes since then. Try the new update, and open another issue if you still get them.

In the meantime, closing this as stale.
