### ISSUE TITLE
Updated to 3.9.13 and BCML won't launch..

### ISSUE THREAD

**Issue by gogogadgetearl** [NiceneNerd/BCML#372]
Originally had python 3.9 installed and was having troubles with some of BCML's dependencies installing properly.  So I fell back to python 3.8.10 and everything installed and ran as expected.

Updated today to BCML 3.9.13, and it wasn't starting from the shortcut I set up.  When I run from the command line, I get this:
```
Traceback (most recent call last):
  File "runpy.py", line 192, in _run_module_as_main
  File "runpy.py", line 85, in _run_code
  File "D:\Software\Games\Emulation\Wii U\python-3.8.10-embed-amd64\lib\site-packages\bcml\__main__.py", line 19, in <module>
    from bcml._api import Api
  File "D:\Software\Games\Emulation\Wii U\python-3.8.10-embed-amd64\lib\site-packages\bcml\_api.py", line 12, in <module>
    from packaging.version import Version
ModuleNotFoundError: No module named 'packaging'
```

**Comment by awsomenes** [comment]
similar issue except i also tried 3.8 and bcml isnt launching also

**Comment by NiceneNerd** [comment]
`pip install packing`

**Comment by Julienraptor01** [comment]
the only way i got bcml working is by downloading the old windows exectuable in release and to use bcml 3.3.3, but when it tries to upgrade it don't work

**Comment by NiceneNerd** [comment]
That's a bad idea

**Comment by Julienraptor01** [comment]
> That's a bad idea

it's a bad idea but at least it work so it's better than nothing

**Comment by NiceneNerd** [comment]
That's related to pythonnet, try downgrading it: `pip install pythonnet==2.5.2`

**Comment by Julienraptor01** [comment]
> the only way i got bcml working is by downloading the old windows exectuable in release and to use bcml 3.3.3, but when it tries to upgrade it don't work

i get this error
`[0627/215948.483:ERROR:request_handler.cpp(109)] [Browser process] OnRenderProcessTerminated()`

**Comment by NiceneNerd** [comment]
Nothing happens at all? Because that's not a real error, it says that all the time

**Comment by Julienraptor01** [comment]
> Nothing happens at all? Because that's not a real error, it says that all the time

no, i get nothing after, python closes and no process stay and the usual cmd prompt that appear doesn't appear

**Comment by NiceneNerd** [comment]
Run `bcml-debug`

**Comment by gogogadgetearl** [comment]
> `pip install packaging`

```
PS D:\Software\Games\Emulation\Wii U\python-3.8.10-embed-amd64> .\python.exe -m pip install packaging
Collecting packaging
  Downloading packaging-21.3-py3-none-any.whl (40 kB)
     ---------------------------------------- 40.8/40.8 kB 2.0 MB/s eta 0:00:00
Collecting pyparsing!=3.0.5,>=2.0.2
  Downloading pyparsing-3.0.9-py3-none-any.whl (98 kB)
     ---------------------------------------- 98.3/98.3 kB 5.5 MB/s eta 0:00:00
Installing collected packages: pyparsing, packaging
Successfully installed packaging-21.3 pyparsing-3.0.9
PS D:\Software\Games\Emulation\Wii U\python-3.8.10-embed-amd64> .\python.exe -m bcml

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Forms.Control.get_CacheTextInternal()
   at System.Windows.Forms.Control.get_Text()
   at System.Windows.Forms.Control.set_Text(String value)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Python.Runtime.PythonException.ThrowLastAsClrException()
   at Python.Runtime.Dispatcher.TrueDispatch(Object[] args)
   at Python.Runtime.Dispatcher.Dispatch(Object[] args)
   at __System_Threading_ThreadStartDispatcher.Invoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by NiceneNerd** [comment]
> > Run `bcml-debug`
> 
> how ? with what command ? ./python -m bcml-debug ?

No, by itself.

@gogogadgetearl This one above: https://github.com/NiceneNerd/BCML/issues/372#issuecomment-1167822130

**Comment by Julienraptor01** [comment]
> > > Run `bcml-debug`
> > 
> > 
> > how ? with what command ? ./python -m bcml-debug ?
> 
> No, by itself.
> 
> @gogogadgetearl This one above: [#372 (comment)](https://github.com/NiceneNerd/BCML/issues/372#issuecomment-1167822130)

`bash: bcml-debug: command not found`

**Comment by NiceneNerd** [comment]
Weird, in that case try alternatively `bcml --debug`

**Comment by gogogadgetearl** [comment]
> @gogogadgetearl This one above: [#372 (comment)](https://github.com/NiceneNerd/BCML/issues/372#issuecomment-1167822130)

That worked.  👍

**Comment by Julienraptor01** [comment]
ok so i took a clean version of the old windows bcml zip thing,
ran
```
./python -m pip install -U bcml
./python -m pip install packaging
./python -m pip install pythonnet==2.5.2
```
then i moved all the content of the folder on top of my good old broken folder and it's fixed

**Comment by jameshop2102** [comment]
Also, just to clarify, I have never gotten this to work, so this is a fresh install, and not an update.
Thanks

**Comment by Julienraptor01** [comment]
> ok so i took a clean version of the old windows bcml zip thing, ran
> 
> ```
> ./python -m pip install -U bcml
> ./python -m pip install packaging
> ./python -m pip install pythonnet==2.5.2
> ```
> 
> then i moved all the content of the folder on top of my good old broken folder and it's fixed



> ok so i took a clean version of the old windows bcml zip thing, ran
> 
> ```
> ./python -m pip install -U bcml
> ./python -m pip install packaging
> ./python -m pip install pythonnet==2.5.2
> ```
> 
> then i moved all the content of the folder on top of my good old broken folder and it's fixed

@jameshop2102 try running these 3 commands (remove the -U)

**Comment by Jmulder08** [comment]
also updated bcml and now won't launch anymore, on python version 3.9.13

**Comment by Jmulder08** [comment]
running `pip install pythonnet==2.5.2` gives an error

**Comment by gogogadgetearl** [comment]
> also updated bcml and now won't launch anymore, on python version 3.9.13

Could be a total coincidence, but the BCML release that broke for me was version 3.9.13 -- I think your actual Python version may be different.  Possibly.  It's worth double-checking.

**Comment by Jmulder08** [comment]
> > also updated bcml and now won't launch anymore, on python version 3.9.13
> 
> Could be a total coincidence, but the BCML release that broke for me was version 3.9.13 -- I think your actual Python version may be different. Possibly. It's worth double-checking.

Yeah no its just a coincidence, python 3.8.10 works fine though

**Comment by NiceneNerd** [comment]
All should be over as of 3.9.14
