### ISSUE TITLE
i cant install it on Pop_OS 22.04

### ISSUE THREAD

**Issue by SolareLeFox** [NiceneNerd/BCML#376]
it prints it on terminal:
[log.txt](https://github.com/NiceneNerd/BCML/files/9034657/log.txt)
somebody can help me?

**Comment by GingerAvalanche** [comment]
You have Python 3.10, but BCML doesn't work with that Python version. Uninstall it and install Python 3.8 or 3.9 instead.

**Comment by SolareLeFox** [comment]
My bad, i can't uninstall it because the system needs it, but i found a workaround installing Python3.8 and Pip 22.1.2 setting a alias for it on terminal and running 'pip install bcml', Thank for the help :D
