### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'docs/README.md'

### ISSUE THREAD

**Issue by windosws** [NiceneNerd/BCML#377]
I can't use pip to install BCML for some errors, so i tried to install with setup.py, would you help me please ?

![image](https://user-images.githubusercontent.com/101200483/177049662-fe728100-4d3f-4383-808d-be75ad8ed8a7.png)

**Comment by NiceneNerd** [comment]
Did you follow all of the build from source instructions?

Also, it's way better to use pip, if you're getting errors it would be better to check into those

**Comment by windosws** [comment]
Well, i get the following errors:

`` pip install bcml
Collecting bcml
  Using cached bcml-3.9.14-cp39-none-win_amd64.whl (19.1 MB)
Collecting oead~=1.2.4
  Using cached oead-1.2.4.post2-cp39-cp39-win_amd64.whl (881 kB)
Collecting numpy==1.19.2
  Using cached numpy-1.19.2.zip (7.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [231 lines of output]
      Running from numpy source directory.
      setup.py:470: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
        run_build = parse_setuppy_commands()
      Processing numpy/random\_bounded_integers.pxd.in
      Processing numpy/random\bit_generator.pyx
      Processing numpy/random\mtrand.pyx
      Processing numpy/random\_bounded_integers.pyx.in
      Processing numpy/random\_common.pyx
      Processing numpy/random\_generator.pyx
      Processing numpy/random\_mt19937.pyx
      Processing numpy/random\_pcg64.pyx
      Processing numpy/random\_philox.pyx
      Processing numpy/random\_sfc64.pyx
      Cythonizing sources
      blas_opt_info:
      blas_mkl_info:
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries mkl_rt not found in ['c:\\users\\antoine\\appdata\\local\\programs\\python\\python39\\lib', 'C:\\', 'c:\\users\\antoine\\appdata\\local\\programs\\python\\python39\\libs']
        NOT AVAILABLE

      blis_info:
        libraries blis not found in ['c:\\users\\antoine\\appdata\\local\\programs\\python\\python39\\lib', 'C:\\', 'c:\\users\\antoine\\appdata\\local\\programs\\python\\python39\\libs']
        NOT AVAILABLE

      openblas_info:
        libraries openblas not found in ['c:\\users\\antoine\\appdata\\local\\programs\\python\\python39\\lib', 'C:\\', 'c:\\users\\antoine\\appdata\\local\\programs\\python\\python39\\libs']
      get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
      customize GnuFCompiler
      Could not locate executable g77
      Could not locate executable f77
      customize IntelVisualFCompiler
      Could not locate executable ifort
      Could not locate executable ifl
      customize AbsoftFCompiler
      Could not locate executable f90
      customize CompaqVisualFCompiler
      Could not locate executable DF
      customize IntelItaniumVisualFCompiler
      Could not locate executable efl
      customize Gnu95FCompiler
      Found executable C:\mingw64\bin\gfortran.exe
      Using built-in specs.
      COLLECT_GCC=C:\mingw64\bin\gfortran.exe
      COLLECT_LTO_WRAPPER=c:/mingw64/bin/../libexec/gcc/x86_64-w64-mingw32/12.1.0/lto-wrapper.exe
      OFFLOAD_TARGET_NAMES=nvptx-none
      Target: x86_64-w64-mingw32
      Configured with: ../configure --prefix=/R/winlibs64ucrt_stage/inst_gcc-12.1.0/share/gcc --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --enable-offload-targets=nvptx-none --with-pkgversion='MinGW-W64 x86_64-ucrt-posix-seh, built by Brecht Sanders' --with-tune=generic --enable-checking=release --enable-threads=posix --disable-sjlj-exceptions --disable-libunwind-exceptions --disable-serial-configure --disable-bootstrap --enable-host-shared --enable-plugin --disable-default-ssp --disable-rpath --disable-libstdcxx-debug --disable-version-specific-runtime-libs --with-stabs --disable-symvers --enable-languages=c,c++,fortran,lto,objc,obj-c++,jit --disable-gold --disable-nls --disable-stage1-checking --disable-win32-registry --disable-multilib --enable-ld --enable-libquadmath --enable-libada --enable-libssp --enable-libstdcxx --enable-lto --enable-fully-dynamic-string --enable-libgomp --enable-graphite --enable-mingw-wildcard --enable-libstdcxx-time --disable-libstdcxx-pch --with-mpc=/d/Prog/winlibs64ucrt_stage/custombuilt --with-mpfr=/d/Prog/winlibs64ucrt_stage/custombuilt --with-gmp=/d/Prog/winlibs64ucrt_stage/custombuilt --with-isl=/d/Prog/winlibs64ucrt_stage/custombuilt --enable-libstdcxx-backtrace --enable-install-libiberty --enable-__cxa_atexit --without-included-gettext --with-diagnostics-color=auto --enable-clocale=generic --with-libiconv --with-system-zlib --with-build-sysroot=/R/winlibs64ucrt_stage/gcc-12.1.0/build_mingw/mingw-w64 CFLAGS='-I/d/Prog/winlibs64ucrt_stage/custombuilt/include/libdl-win32 -D__USE_MINGW_ACCESS' CXXFLAGS=-D__USE_MINGW_ACCESS LDFLAGS='-Wl,--disable-nxcompat -Wl,--disable-high-entropy-va -Wl,--disable-dynamicbase'
      Thread model: posix
      Supported LTO compression algorithms: zlib zstd
      gcc version 12.1.0 (MinGW-W64 x86_64-ucrt-posix-seh, built by Brecht Sanders)
        NOT AVAILABLE

      atlas_3_10_blas_threads_info:
      Setting PTATLAS=ATLAS
        libraries tatlas not found in ['c:\\users\\antoine\\appdata\\local\\programs\\python\\python39\\lib', 'C:\\', 'c:\\users\\antoine\\appdata\\local\\programs\\python\\python39\\libs']
        NOT AVAILABLE

      atlas_3_10_blas_info:
        libraries satlas not found in ['c:\\users\\antoine\\appdata\\local\\programs\\python\\python39\\lib', 'C:\\', 'c:\\users\\antoine\\appdata\\local\\programs\\python\\python39\\libs']
        NOT AVAILABLE

      atlas_blas_threads_info:
      Setting PTATLAS=ATLAS
        libraries ptf77blas,ptcblas,atlas not found in ['c:\\users\\antoine\\appdata\\local\\programs\\python\\python39\\lib', 'C:\\', 'c:\\users\\antoine\\appdata\\local\\programs\\python\\python39\\libs']
        NOT AVAILABLE

      atlas_blas_info:
        libraries f77blas,cblas,atlas not found in ['c:\\users\\antoine\\appdata\\local\\programs\\python\\python39\\lib', 'C:\\', 'c:\\users\\antoine\\appdata\\local\\programs\\python\\python39\\libs']
        NOT AVAILABLE

      accelerate_info:
        NOT AVAILABLE

      C:\Users\map\AppData\Local\Temp\pip-install-13i85hve\numpy_a31b7f76d4284e0387d6b0fa41c03c61\numpy\distutils\system_info.py:1914: UserWarning:
          Optimized (vendor) Blas libraries are not found.
          Falls back to netlib Blas library which has worse performance.
          A better performance should be easily gained by switching
          Blas library.
        if self._calc_info(blas):
      blas_info:
        libraries blas not found in ['c:\\users\\antoine\\appdata\\local\\programs\\python\\python39\\lib', 'C:\\', 'c:\\users\\antoine\\appdata\\local\\programs\\python\\python39\\libs']
        NOT AVAILABLE

      C:\Users\map\AppData\Local\Temp\pip-install-13i85hve\numpy_a31b7f76d4284e0387d6b0fa41c03c61\numpy\distutils\system_info.py:1914: UserWarning:
          Blas (http://www.netlib.org/blas/) libraries not found.
          Directories to search for the libraries can be specified in the
          numpy/distutils/site.cfg file (section [blas]) or by setting
          the BLAS environment variable.
        if self._calc_info(blas):
      blas_src_info:
        NOT AVAILABLE

      C:\Users\map\AppData\Local\Temp\pip-install-13i85hve\numpy_a31b7f76d4284e0387d6b0fa41c03c61\numpy\distutils\system_info.py:1914: UserWarning:
          Blas (http://www.netlib.org/blas/) sources not found.
          Directories to search for the sources can be specified in the
          numpy/distutils/site.cfg file (section [blas_src]) or by setting
          the BLAS_SRC environment variable.
        if self._calc_info(blas):
        NOT AVAILABLE

      non-existing path in 'numpy\\distutils': 'site.cfg'
      lapack_opt_info:
      lapack_mkl_info:
        libraries mkl_rt not found in ['c:\\users\\antoine\\appdata\\local\\programs\\python\\python39\\lib', 'C:\\', 'c:\\users\\antoine\\appdata\\local\\programs\\python\\python39\\libs']
        NOT AVAILABLE

      openblas_lapack_info:
        libraries openblas not found in ['c:\\users\\antoine\\appdata\\local\\programs\\python\\python39\\lib', 'C:\\', 'c:\\users\\antoine\\appdata\\local\\programs\\python\\python39\\libs']
      get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
      customize GnuFCompiler
      customize IntelVisualFCompiler
      customize AbsoftFCompiler
      customize CompaqVisualFCompiler
      customize IntelItaniumVisualFCompiler
      customize Gnu95FCompiler
      Using built-in specs.
      COLLECT_GCC=C:\mingw64\bin\gfortran.exe
      COLLECT_LTO_WRAPPER=c:/mingw64/bin/../libexec/gcc/x86_64-w64-mingw32/12.1.0/lto-wrapper.exe
      OFFLOAD_TARGET_NAMES=nvptx-none
      Target: x86_64-w64-mingw32
      Configured with: ../configure --prefix=/R/winlibs64ucrt_stage/inst_gcc-12.1.0/share/gcc --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --enable-offload-targets=nvptx-none --with-pkgversion='MinGW-W64 x86_64-ucrt-posix-seh, built by Brecht Sanders' --with-tune=generic --enable-checking=release --enable-threads=posix --disable-sjlj-exceptions --disable-libunwind-exceptions --disable-serial-configure --disable-bootstrap --enable-host-shared --enable-plugin --disable-default-ssp --disable-rpath --disable-libstdcxx-debug --disable-version-specific-runtime-libs --with-stabs --disable-symvers --enable-languages=c,c++,fortran,lto,objc,obj-c++,jit --disable-gold --disable-nls --disable-stage1-checking --disable-win32-registry --disable-multilib --enable-ld --enable-libquadmath --enable-libada --enable-libssp --enable-libstdcxx --enable-lto --enable-fully-dynamic-string --enable-libgomp --enable-graphite --enable-mingw-wildcard --enable-libstdcxx-time --disable-libstdcxx-pch --with-mpc=/d/Prog/winlibs64ucrt_stage/custombuilt --with-mpfr=/d/Prog/winlibs64ucrt_stage/custombuilt --with-gmp=/d/Prog/winlibs64ucrt_stage/custombuilt --with-isl=/d/Prog/winlibs64ucrt_stage/custombuilt --enable-libstdcxx-backtrace --enable-install-libiberty --enable-__cxa_atexit --without-included-gettext --with-diagnostics-color=auto --enable-clocale=generic --with-libiconv --with-system-zlib --with-build-sysroot=/R/winlibs64ucrt_stage/gcc-12.1.0/build_mingw/mingw-w64 CFLAGS='-I/d/Prog/winlibs64ucrt_stage/custombuilt/include/libdl-win32 -D__USE_MINGW_ACCESS' CXXFLAGS=-D__USE_MINGW_ACCESS LDFLAGS='-Wl,--disable-nxcompat -Wl,--disable-high-entropy-va -Wl,--disable-dynamicbase'
      Thread model: posix
      Supported LTO compression algorithms: zlib zstd
      gcc version 12.1.0 (MinGW-W64 x86_64-ucrt-posix-seh, built by Brecht Sanders)
        NOT AVAILABLE

      openblas_clapack_info:
        libraries openblas,lapack not found in ['c:\\users\\antoine\\appdata\\local\\programs\\python\\python39\\lib', 'C:\\', 'c:\\users\\antoine\\appdata\\local\\programs\\python\\python39\\libs']
      get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
      customize GnuFCompiler
      customize IntelVisualFCompiler
      customize AbsoftFCompiler
      customize CompaqVisualFCompiler
      customize IntelItaniumVisualFCompiler
      customize Gnu95FCompiler
      Using built-in specs.
      COLLECT_GCC=C:\mingw64\bin\gfortran.exe
      COLLECT_LTO_WRAPPER=c:/mingw64/bin/../libexec/gcc/x86_64-w64-mingw32/12.1.0/lto-wrapper.exe
      OFFLOAD_TARGET_NAMES=nvptx-none
      Target: x86_64-w64-mingw32
      Configured with: ../configure --prefix=/R/winlibs64ucrt_stage/inst_gcc-12.1.0/share/gcc --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --enable-offload-targets=nvptx-none --with-pkgversion='MinGW-W64 x86_64-ucrt-posix-seh, built by Brecht Sanders' --with-tune=generic --enable-checking=release --enable-threads=posix --disable-sjlj-exceptions --disable-libunwind-exceptions --disable-serial-configure --disable-bootstrap --enable-host-shared --enable-plugin --disable-default-ssp --disable-rpath --disable-libstdcxx-debug --disable-version-specific-runtime-libs --with-stabs --disable-symvers --enable-languages=c,c++,fortran,lto,objc,obj-c++,jit --disable-gold --disable-nls --disable-stage1-checking --disable-win32-registry --disable-multilib --enable-ld --enable-libquadmath --enable-libada --enable-libssp --enable-libstdcxx --enable-lto --enable-fully-dynamic-string --enable-libgomp --enable-graphite --enable-mingw-wildcard --enable-libstdcxx-time --disable-libstdcxx-pch --with-mpc=/d/Prog/winlibs64ucrt_stage/custombuilt --with-mpfr=/d/Prog/winlibs64ucrt_stage/custombuilt --with-gmp=/d/Prog/winlibs64ucrt_stage/custombuilt --with-isl=/d/Prog/winlibs64ucrt_stage/custombuilt --enable-libstdcxx-backtrace --enable-install-libiberty --enable-__cxa_atexit --without-included-gettext --with-diagnostics-color=auto --enable-clocale=generic --with-libiconv --with-system-zlib --with-build-sysroot=/R/winlibs64ucrt_stage/gcc-12.1.0/build_mingw/mingw-w64 CFLAGS='-I/d/Prog/winlibs64ucrt_stage/custombuilt/include/libdl-win32 -D__USE_MINGW_ACCESS' CXXFLAGS=-D__USE_MINGW_ACCESS LDFLAGS='-Wl,--disable-nxcompat -Wl,--disable-high-entropy-va -Wl,--disable-dynamicbase'
      Thread model: posix
      Supported LTO compression algorithms: zlib zstd
      gcc version 12.1.0 (MinGW-W64 x86_64-ucrt-posix-seh, built by Brecht Sanders)
        NOT AVAILABLE

      flame_info:
        libraries flame not found in ['c:\\users\\antoine\\appdata\\local\\programs\\python\\python39\\lib', 'C:\\', 'c:\\users\\antoine\\appdata\\local\\programs\\python\\python39\\libs']
        NOT AVAILABLE

      atlas_3_10_threads_info:
      Setting PTATLAS=ATLAS
        libraries lapack_atlas not found in c:\users\antoine\appdata\local\programs\python\python39\lib
        libraries tatlas,tatlas not found in c:\users\antoine\appdata\local\programs\python\python39\lib
        libraries lapack_atlas not found in C:\
        libraries tatlas,tatlas not found in C:\
        libraries lapack_atlas not found in c:\users\antoine\appdata\local\programs\python\python39\libs
        libraries tatlas,tatlas not found in c:\users\antoine\appdata\local\programs\python\python39\libs
      <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
        NOT AVAILABLE

      atlas_3_10_info:
        libraries lapack_atlas not found in c:\users\antoine\appdata\local\programs\python\python39\lib
        libraries satlas,satlas not found in c:\users\antoine\appdata\local\programs\python\python39\lib
        libraries lapack_atlas not found in C:\
        libraries satlas,satlas not found in C:\
        libraries lapack_atlas not found in c:\users\antoine\appdata\local\programs\python\python39\libs
        libraries satlas,satlas not found in c:\users\antoine\appdata\local\programs\python\python39\libs
      <class 'numpy.distutils.system_info.atlas_3_10_info'>
        NOT AVAILABLE

      atlas_threads_info:
      Setting PTATLAS=ATLAS
        libraries lapack_atlas not found in c:\users\antoine\appdata\local\programs\python\python39\lib
        libraries ptf77blas,ptcblas,atlas not found in c:\users\antoine\appdata\local\programs\python\python39\lib
        libraries lapack_atlas not found in C:\
        libraries ptf77blas,ptcblas,atlas not found in C:\
        libraries lapack_atlas not found in c:\users\antoine\appdata\local\programs\python\python39\libs
        libraries ptf77blas,ptcblas,atlas not found in c:\users\antoine\appdata\local\programs\python\python39\libs
      <class 'numpy.distutils.system_info.atlas_threads_info'>
        NOT AVAILABLE

      atlas_info:
        libraries lapack_atlas not found in c:\users\antoine\appdata\local\programs\python\python39\lib
        libraries f77blas,cblas,atlas not found in c:\users\antoine\appdata\local\programs\python\python39\lib
        libraries lapack_atlas not found in C:\
        libraries f77blas,cblas,atlas not found in C:\
        libraries lapack_atlas not found in c:\users\antoine\appdata\local\programs\python\python39\libs
        libraries f77blas,cblas,atlas not found in c:\users\antoine\appdata\local\programs\python\python39\libs
      <class 'numpy.distutils.system_info.atlas_info'>
        NOT AVAILABLE

      lapack_info:
        libraries lapack not found in ['c:\\users\\antoine\\appdata\\local\\programs\\python\\python39\\lib', 'C:\\', 'c:\\users\\antoine\\appdata\\local\\programs\\python\\python39\\libs']
        NOT AVAILABLE

      C:\Users\map\AppData\Local\Temp\pip-install-13i85hve\numpy_a31b7f76d4284e0387d6b0fa41c03c61\numpy\distutils\system_info.py:1748: UserWarning:
          Lapack (http://www.netlib.org/lapack/) libraries not found.
          Directories to search for the libraries can be specified in the
          numpy/distutils/site.cfg file (section [lapack]) or by setting
          the LAPACK environment variable.
        return getattr(self, '_calc_info_{}'.format(name))()
      lapack_src_info:
        NOT AVAILABLE

      C:\Users\map\AppData\Local\Temp\pip-install-13i85hve\numpy_a31b7f76d4284e0387d6b0fa41c03c61\numpy\distutils\system_info.py:1748: UserWarning:
          Lapack (http://www.netlib.org/lapack/) sources not found.
          Directories to search for the sources can be specified in the
          numpy/distutils/site.cfg file (section [lapack_src]) or by setting
          the LAPACK_SRC environment variable.
        return getattr(self, '_calc_info_{}'.format(name))()
        NOT AVAILABLE

      numpy_linalg_lapack_lite:
        FOUND:
          language = c
          define_macros = [('HAVE_BLAS_ILP64', None), ('BLAS_SYMBOL_SUFFIX', '64_')]

      c:\users\antoine\appdata\local\programs\python\python39\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'define_macros'
        warnings.warn(msg)
      running dist_info
      running build_src
      build_src
      building py_modules sources
      creating build
      creating build\src.win-amd64-3.9
      creating build\src.win-amd64-3.9\numpy
      creating build\src.win-amd64-3.9\numpy\distutils
      building library "npymath" sources
      error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.``

**Comment by NiceneNerd** [comment]
Python 3.9 support on Windows is still experimental and not very good. Try Python 3.8.

**Comment by windosws** [comment]
so for me i think its better to use setup.py

**Comment by windosws** [comment]
i still have the same error using Python 3.8

**Comment by NiceneNerd** [comment]
Then it must still be running 3.9 even though you installed 3.8
