### ISSUE TITLE
The Latest(2019) Visual C++ redistributable is required to run BCML.

### ISSUE THREAD

**Issue by sublimejer** [NiceneNerd/BCML#378]
BCML is successfully installed, but when launched this error is given
![125162695f224422945822d06c8195e4](https://user-images.githubusercontent.com/108367388/177063676-bbecfb51-7b5d-4909-92a6-7721599bd134.png)

I'm currently running the latest Visual C++ redistributable from the link on the main GitHub page, which is the 2015-2022 version, and I've tried the download link that the error provides, which downloads the 2015-2019 version of Visual C++. I've tried both and I've restarted my computer between each try, however, the error is still here.

Is this error with my copy of Visual C++?

**Comment by GingerAvalanche** [comment]
It's an old error message that should be updated. The 2022 version has been tested to work. Thanks for letting us know.

This error is a blanket error that comes up if `oead` could not be loaded. We don't really have access to *why* it can't be loaded, if it can't, so prompting the user to install the redist is just our best guess as to what's going on.

Try opening a python shell and importing oead (start menu -> cmd -> `py` -> `import oead`) and let us know what it says.

**Comment by sublimejer** [comment]
Not sure if I did it right, as I am inexperienced in python.

First, it didn't recognise import oead as a valid command or something, as seen
![094feac695cf2b3fb6e36cdc76c83897](https://user-images.githubusercontent.com/108367388/177069473-a22b31bf-d5d6-4b8e-bbe4-0fee76e505b2.png)
Uninstalling then reinstalling oead through pip un/install oead let me import oead, however, when launching the BCML script directly or through cmd, no script launches
![9cf3c03d0f89448acd05092cd6024367](https://user-images.githubusercontent.com/108367388/177069624-1c4ee0b2-6f76-4f06-b938-5d7c64c7e9bb.png)

**Comment by sublimejer** [comment]
By the way, there is no error message given, the script just doesn't launch

**Comment by NiceneNerd** [comment]
See about `bcml-debug`

**Comment by sublimejer** [comment]
Through cmd, bcml-debug does not start and spits this out
![image](https://user-images.githubusercontent.com/108367388/177072899-1cb6d9e7-e6fa-46b7-8474-9f820c153838.png)

**Comment by sublimejer** [comment]
Eventually got past issues on my own with relative ease. The initial issue has been solved, gonna mark as closed.
