### ISSUE TITLE
UnicodeDecodeError when specifying content directory

### ISSUE THREAD

**Issue by JmTexas19** [NiceneNerd/BCML#38]
I get the following error when I specify the botw content directory.

```
Traceback (most recent call last):
  File "C:\Users\jmtex\AppData\Local\BCML\pkgs\bcml\util.py", line 252, in get_update_dir
    title_id = get_title_id()
  File "C:\Users\jmtex\AppData\Local\BCML\pkgs\bcml\util.py", line 239, in get_title_id
    for line in a_file:
UnicodeDecodeError: 'cp932' codec can't decode byte 0xef in position 0: illegal multibyte sequence

```

**Comment by JmTexas19** [comment]
This is probably an issue with cp932 being the default character encoder which happens when the system locale is changed to `Japanese`. Changing it to `United States` or enabling `Beta: Use Unicode UTF-8 for worldwide language support` fixes the issue.

**Comment by DrShadow34** [comment]
Can report same problem here. But my system locale set to russian.
