### ISSUE TITLE
Folder drag & drop shows folder content instead

### ISSUE THREAD

**Issue by ratijas** [NiceneNerd/BCML#381]
So, as a part of an onboarding (first launch, fist steps) I was prompted to specify Cemu directory.

I is conveniently placed on a Desktop, as suggested in tutorial on Cemu wiki, so I just dragged it from a desktop onto BCML window. This is what happened instead:

![image](https://user-images.githubusercontent.com/6737986/177531463-9786fe75-0dbd-460c-b2c1-4fa6bd6bb035.png)

A slightly broken page listing directory content, and no visible means of going back. Very confused about this.

**Comment by ratijas** [comment]
Have you considered Qt frontend? 🤔  I bet packaging wouldn't be any harder than currently Python is. There's not much of a graphics going on, mostly just slightly stylized pretty standard controls.

**Comment by NiceneNerd** [comment]
The frontend will not be changed, as that would be a gigantic rewrite for little, if any, benefit.

**Comment by ratijas** [comment]
Understandable, of course. I just asked out of curiosity, like, what's the story behind it, and how it ended up being Web + Python + Rust project distributed as pip wheel.

On topic, it's a bit unfortunate that even in 2022 Windows OS is still barely usable in such basic tasks: drag&dropping a folder onto an "Open folder..." window is going to copy/move/link it into whichever the currently browsed folder is, instead of, well, actually navigating to it and offering to choose it.
