### ISSUE TITLE
Note about patch_patches.asm on "BOTW Randomizer by Waikuteru" page

### ISSUE THREAD

**Issue by ratijas** [NiceneNerd/BCML#382]
https://gamebanana.com/mods/345664

> CEMU USERS - BCML: Open BCML and install the mod folder by selecting the rules.txt.
>
> ATTENTION:
> If you install via BCML, BCML will get rid of the patch_patches.asm file in the process of installing. You will have to manually drag and drop this file next to the rules.txt file into the BCML-generated graphicPack. This graphicPack is found where your Cemu.exe is located inside the graphicPack folder and is called "BreathOfTheWild_BCML".

I double checked folders and contents, and the `patch_patches.asm` is just there, installed in the `graphicPacks\BreathOfTheWild_BCML`, identical to the one that's bundled in the Randomizer mod.

I guess that comment is just outdated?  But I also didn't find anything in issues or Pull Request to confirm that it was fixed at some point in past.

**Comment by NiceneNerd** [comment]
I'm really not sure, I don't recall Waiku ever asking about it.

**Comment by Torphedo** [comment]
Why doesn't he just make a `patches` folder with a graphics pack that is on by default? That'd solve this whole issue
