### ISSUE TITLE
Can't use the one click install on gamebanana for BCML

### ISSUE THREAD

**Issue by StrokeBold** [NiceneNerd/BCML#39]
I am not able to install mods via the one click tool anymore, even after reinstalling bcml a view times and also trying some older versions. A friend of mine doesn't have that problem, so I haven't been able to find a solution.

**Comment by DarthDub** [comment]
I got the following when trying to use 1-click install with Hero Blight Sword on GameBanana.

BCML has encountered an error while performing an operation. Error details:

There was an error installing Hero Blight Sword. It processed successfully, but could not be added to your BCML mods. This may indicate a problem with your BCML installation. Here is the error:

Traceback (most recent call last):
 File "C:\Users\DarthDub\AppData\Local\BCML\pkgs\bcml\install.py", line 433,
in install mod
  refresh_cemu_mods()
 File "C:\Users\DarthDub\AppData\Local\BCML\pkgs\bcml\install.py", line 256,
in refresh_cemu_mods
   for line in setfile:
UnicodeDecodeError: 'cp932' codec can't decode byte 0x83 in position 5151:
illegal multibyte sequence


Hero Blight Sword is being removed and no changes will be made.

**Comment by NiceneNerd** [comment]
That's a known encoding error to be fixed in the first BCML 3 release. In the meantime, see if you can remove any non-English characters from Cemu's `settings.xml` file

**Comment by DarthDub** [comment]
I kind of had a feeling it was that since I have my PC set to Japan locale.

**Comment by GingerAvalanche** [comment]
If you're feeling brave, you can edit your bcml files to reflect the changes in this diff: https://github.com/NiceneNerd/BCML/pull/42/commits/c2b1bded32a050e9ca35ca1352a41526c1f7988b

Other than that, you can try using bcml3. If your computer has utf-8 paths then you're going to be removing those characters from your settings.xml file pretty much every time you install a mod, assuming you can even get Cemu to run that way.

**Comment by NiceneNerd** [comment]
^ What she said

**Comment by DarthDub** [comment]
Changing Japan locale back to USA (English) fixed this issue.
