### ISSUE TITLE
Bcml not working

### ISSUE THREAD

**Issue by DudeCanIGet** [NiceneNerd/BCML#396]
I installed Visual c++  i am using python 3.9.13 i installed bcml via pip and numpy. i  typed in bcml in cmd  then ran script as admin it has a little wheel then nothing happens

**Comment by GingerAvalanche** [comment]
Python 3.9 support is very hit and miss. For some people it works, for others it doesn't. Try uninstalling 3.9 and installing 3.8 instead.

**Comment by DudeCanIGet** [comment]
thank you

**Comment by DudeCanIGet** [comment]
Whelp... Crud
![screenshot](https://user-images.githubusercontent.com/86628736/180259780-a701b1b8-eef3-4967-bdf1-6e208c36fd5c.png)

**Comment by DudeCanIGet** [comment]
Help please
