### ISSUE TITLE
Bootup_ language can't not found for Cemu (Botw Wii U) when install bnp file

### ISSUE THREAD

**Issue by TakeiHoang** [NiceneNerd/BCML#406]
![image](https://user-images.githubusercontent.com/48914374/181897300-4336b2f2-cd15-42a5-a239-787423f1e08d.png)
Also everytime i try to re-install from gamebanana it's show different of language pack that missing like KRen.pack, USen.pack etc but my game on Cemu is EU

**Comment by GingerAvalanche** [comment]
3.9.23 should fix this
