### ISSUE TITLE
BCML seemingly missing some menu headers?

### ISSUE THREAD

**Issue by TheQuantumAnchovie** [NiceneNerd/BCML#409]
I just updated my installation of bcml to the most recent version with the built-in update button, and now it's missing the top menu headers that allow you to access GameBanana and/or install mods. Is this a know issue/is there some part of the config i need to change to reaccess these parts of bcml, or should i just reinstall the program entirely?

(I'm running on windows 10, using python 3.7.9, if that helps)

This is what my BCML window looks like:
![image](https://user-images.githubusercontent.com/54431873/182010892-eefb70d7-4543-4867-b033-18d2ca309183.png)

**Comment by Torphedo** [comment]
The GameBanana tab was removed because it was a mess on the technical side and their API is always changing / terrible.

**Comment by TheQuantumAnchovie** [comment]
oh dang I guess i wasn't tracking that - my bad, thank you for letting me know!
