### ISSUE TITLE
Python crashes when looking for Cemu.exe

### ISSUE THREAD

**Issue by sweetkiwi** [NiceneNerd/BCML#41]
I've tried using the easy installer and the pip installer but neither work. Every time it opens BCML and asks to look for the cemu.exe location. I click okay and it opens my files to look for cemu.exe then it immediately crashes. I've tried reinstalling C++, Python, and BCML. I've even gotten different versions of Python but nothing works. Please help.

**Comment by NiceneNerd** [comment]
Can't reproduce.
