### ISSUE TITLE
Having trouble with setup for Ryujinx emulator

### ISSUE THREAD

**Issue by Dr69onS6mur6i** [NiceneNerd/BCML#411]
I'm following the directions in the video, setting the folders correctly, but nothing ticks and turns green. What am I doing wrong?

https://www.youtube.com/watch?v=8gKRifYyA68 <-- the video I'm following

![Untitled](https://user-images.githubusercontent.com/63492967/183235113-a3dde5c3-2589-47d8-ab24-f14611e182fc.png)

**Comment by GingerAvalanche** [comment]
If nothing ticks or turns green, then the statement "I'm... setting the folders correctly" is almost certainly incorrect. I don't mean to call you out, it's just that if you say that (and the person you're asking for help believes you) then you've redirected away from the correct answer, and made it harder to get help.

We can't know exactly what you're doing without seeing your settings.

First try the in-app help pages. That will be a lot faster than back-and-forth messages here. Specifically, "How do I set up my game folders for BCML?" in the Troubleshooting page. (Should be accessible by pressing F1 in the app. If not, the page you want is also [here](https://github.com/NiceneNerd/BCML/blob/master/docs/trouble.md))

If that still doesn't solve it, screenshot your settings, post it here, and we'll see what we can do.
