### ISSUE TITLE
Yuzu game launch boot-loop

### ISSUE THREAD

**Issue by S1ayerXYZ** [NiceneNerd/BCML#413]
I've set up BCML for yuzu and verified that everything was green but when I try to launch the mod (labeled SDMC in the properties tab) yuzu gets locked in an infinite launching loop
![yuzu 1142 _ The Legend of Zelda_ Breath of the Wild (64-bit) _ 1 6 0 _ NVIDIA 8_23_2022 7_08_01 PM](https://user-images.githubusercontent.com/111932481/186287167-9308c413-0e24-43a2-b033-d024ddfc6ccb.png)

**Comment by Torphedo** [comment]
Yuzu just kinda does that...not a BCML problem, that's just how Yuzu is

**Comment by S1ayerXYZ** [comment]
any idea on how to fix it? if so it would be much appreciated!

**Comment by S1ayerXYZ** [comment]
the game launches fine without mods, though I still want to play with mods

**Comment by HGStone** [comment]
if you want to play mods, then just do it on your console, it's already homebrewed anyway since you dumped your game from it
