### ISSUE TITLE
BCML wont open on windows 11

### ISSUE THREAD

**Issue by GamingReborn** [NiceneNerd/BCML#415]
dont know if it works on windows 11 but ive tried game banana to open it, going to the file and nothing works.

**Comment by NiceneNerd** [comment]
What is the output of `bcml-debug`?

**Comment by DragonSoul2875** [comment]
I'm also having the same issue, mine is:

DevTools listening on ws://127.0.0.1:60927/devtools/browser/e2a6d094-2b85-452d-9a39-b64b9954cedd

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Forms.Control.get_CacheTextInternal()
   at System.Windows.Forms.Control.get_Text()
   at System.Windows.Forms.Control.set_Text(String value)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Python.Runtime.PythonException.ThrowLastAsClrException()
   at Python.Runtime.Dispatcher.TrueDispatch(Object[] args)
   at Python.Runtime.Dispatcher.Dispatch(Object[] args)
   at __System_Threading_ThreadStartDispatcher.Invoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by NiceneNerd** [comment]
Python 3.9 support  on Windows is still wonky with mixed results, use 3.8

**Comment by GamingReborn** [comment]
i am

**Comment by NiceneNerd** [comment]
I was talking to the guy above me who is using 3.9. For your part, I'm still waiting on the `bcml-debug` output.

**Comment by GamingReborn** [comment]
the thing isi uninstalled it and now i cant reinstall it with the pip install bcml

**Comment by NiceneNerd** [comment]
What happens when you try?

**Comment by GamingReborn** [comment]
error after using pipx install bcml
![image](https://user-images.githubusercontent.com/94934670/186558034-ec3ac235-65ce-4b05-acaf-fc518eb400d9.png)

**Comment by NiceneNerd** [comment]
pipx is not a supported install method on Windows.

**Comment by GamingReborn** [comment]
well then how else am i supposed to install it?

**Comment by NiceneNerd** [comment]
Using regular pip, per the instructions

**Comment by GamingReborn** [comment]
it says requirements already met

**Comment by NiceneNerd** [comment]
So does `bcml-debug` do anything?

**Comment by GamingReborn** [comment]
i dont have that

**Comment by NiceneNerd** [comment]
You mean it's not a recognized command? Make sure you have your Python PATH setup correctly.

**Comment by GamingReborn** [comment]
i do

**Comment by GamingReborn** [comment]
![image](https://user-images.githubusercontent.com/94934670/186558833-e5212b38-a279-4977-ae22-c0df36f69208.png)
thats all it says

**Comment by GamingReborn** [comment]
plus a few more

**Comment by NiceneNerd** [comment]
But what happens when you actually run `bcml-debug`? What message then?

**Comment by GamingReborn** [comment]
what do you mean?

**Comment by NiceneNerd** [comment]
When you run the command `bcml-debug`, what happens, or what error do you get?

**Comment by GamingReborn** [comment]
there is no command

**Comment by NiceneNerd** [comment]
In that case the PATH must be the issue

**Comment by GamingReborn** [comment]
so rerun the python install and select add to path?

**Comment by NiceneNerd** [comment]
You can try that, or check one of the various tutorials out there for manually correcting PATH problems.

You might also just try `pip install --force-reinstall bcml` first, just in case that works quickly.

**Comment by GamingReborn** [comment]
![image](https://user-images.githubusercontent.com/94934670/186560455-f839a350-bfd5-4bed-92d4-9f7a4acf9f41.png)

**Comment by NiceneNerd** [comment]
Full view, plz

**Comment by GamingReborn** [comment]
![image](https://user-images.githubusercontent.com/94934670/186560593-44863d78-6c52-42bb-b8ef-75b2e0b18003.png)

**Comment by NiceneNerd** [comment]
That's Python 3.9

**Comment by GamingReborn** [comment]
i have both

**Comment by NiceneNerd** [comment]
Well, it's trying to use 3.9, so you'll need to try with 3.8

**Comment by GamingReborn** [comment]
im uninstalling it

**Comment by GamingReborn** [comment]
it worked thank you so much

**Comment by NiceneNerd** [comment]
Glad to be of service
