### ISSUE TITLE
I keep on getting this error and I can't seem to fix it. On Windows 10, ran 'pip install bcml'

### ISSUE THREAD

**Issue by BrutalBoy1** [NiceneNerd/BCML#419]
m = lambda self, *args, **kw: func(self, *args, **kw)
      TypeError: CCompiler_spawn() got an unexpected keyword argument 'env'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by GingerAvalanche** [comment]
Pretty sure this isn't the entire error log. Hard to say without seeing the whole thing, but this typically means you're trying to use python 3.10, which isn't compatible. Use the highest version of 3.8 that you can get. (3.8.10, I think?)

**Comment by BrutalBoy1** [comment]
> > Pretty sure this isn't the entire error log. Hard to say without seeing the whole thing, but this typically means you're trying to use python 3.10, which isn't compatible. Use the highest version of 3.8 that you can get. (3.8.10, I think?)
> 
> I have both Python 3.9 and 3.10, so I don't really see the issue.

Hold on, let me try uninstalling Python 3.10

**Comment by BrutalBoy1** [comment]
Uninstalling Python 3.10 seemed to have worked.
