### ISSUE TITLE
BCML doesn't accept the new Linux port of cemu

### ISSUE THREAD

**Issue by Melechtna** [NiceneNerd/BCML#421]
Title pretty much says it all. BCML will only accept it if an exe is present, but there's a Linux version now, so it'd be nice if it could use that version now without having to copy the exe into the directory.

**Comment by HGStone** [comment]
just setup a "merged export directory" to the needed location under the graphic packs folder

**Comment by HGStone** [comment]
oh, and use "without cemu" settings

**Comment by Melechtna** [comment]
The only problem with that, is I either get a "directory doesn't exist" error linking it, or it doesn't actually copy everything from the merge. Granted, I can correct for this by copying the last 3 files over, but that's obviously not how that should work.

**Comment by Zetsphiron** [comment]
It works even worse for me. I get the same directory missing error... but it's actually true. For some reason, when picking the path for the graphics pack, the whole graphics pack(s) folder gets deleted.

**Comment by HGStone** [comment]
you might need to "disable links for master mod" and try again

**Comment by Zetsphiron** [comment]
Still deletes.
Guess we only have copying the files manually then?

**Comment by Zetsphiron** [comment]
Copying the files manually worked, although I only tried to copy the merged mod graphics pack that I had on Windows. I don't know if putting the 9999_BCML (linux side) folder into your /graphicsPacks/downloadedGraphicsPacks/BreathOfTheWild/ folder named as BCML would do the trick too

**Comment by GingerAvalanche** [comment]
Finally taking a look at this. BCML should now support up to py311 (current), so the only remaining issue would be the Cemu directory checker, which looks for the name of the executable, and only knows the Windows executable name.

@jpenguin or @Melechtna what is the executable called on Linux? Is it just `Cemu` or is there some extension?
