### ISSUE TITLE
BCML does not launch on Nixos

### ISSUE THREAD

**Issue by WryOpussum** [NiceneNerd/BCML#423]
bcml-debug gives no output. I got it by installing python3.7 from nix packages then installing pipx then running `pipx install bcml`.
[Screencast from 09-10-2022 02:58:16 PM.webm](https://user-images.githubusercontent.com/100379319/189499892-d5dbdbec-54bb-4630-b362-18163a4b19c7.webm)

**Comment by NiceneNerd** [comment]
Given NixOS is radically different from most other operating systems, I can't promise it'll ever work, but see what this does:
`python -m bcml --debug`

**Comment by WryOpussum** [comment]
still no output. Can I export to a graphic pack cuz if so I can just build a VM for bcml

**Comment by NiceneNerd** [comment]
Yes

**Comment by WryOpussum** [comment]
Found out the issue was that nixos does not execute standard linux executables without a software called steam-run. Thanks for the help!
