### ISSUE TITLE
Troubles while exporting mods

### ISSUE THREAD

**Issue by mando973** [NiceneNerd/BCML#425]
I'm using the new Linux version of Cemu so I must export my mods because BCML don't support this version of Cemu but when I try to export my mods and use them as a GraphicPack, the exportation didn't work and I get this message : 

Waiting for Python and Windows to figure themselves out...

And nothing else, just this message that repeats endlessly

**Comment by HGStone** [comment]
just alter your bcml settings.. " use without cemu" and then set your "merged export folder" to the proper place for a cemu graphic pack

**Comment by aem111607** [comment]
Also experiencing this

**Comment by jedinjapan** [comment]
Experiencing this issue as well. The debug log shows the following before the message repeats infinitely:

```
Preparing output folder at C:\Users\USERNAME\AppData\Local\Temp\tmpk_ne6t2o
Attempting to link output folder at C:\Users\Sky\AppData\Local\Temp\tmpk_ne6t2o to merged folder
Adding rules.txt...
Waiting for Python and Windows to figure themselves out...
```

**Comment by GingerAvalanche** [comment]
Fixed in [65135a](https://github.com/NiceneNerd/BCML/commit/65135a5be48539801b686ac0c533805d39fc1b64)
