### ISSUE TITLE
Unable to Compile BCML

### ISSUE THREAD

**Issue by CoulsTech** [NiceneNerd/BCML#426]
Issue: when installing BCML with python pip, on windows, Linux, or compiling from source in venv 
installing / compiling numpy errors out the installation
Steps to recreate: run python pip installer on Ubuntu or Windows 11 or attempt to compile from source on Ubuntu

Steps taken to remediate:
I BELIEVE I have followed all listed requirements and steps, I have tried to install using several OS platforms, and I have collected and read through error logs

Paste of Linux Source compilation in venv error:
https://pastebin.com/XefXdPG4

**Comment by HGStone** [comment]
use python 3.8
