### ISSUE TITLE
I am not able to download bcml [linux]

### ISSUE THREAD

**Issue by xFedee** [NiceneNerd/BCML#430]
![image](https://user-images.githubusercontent.com/87451140/194776975-34593cdd-5861-4dc4-9d2e-950f8cf1ba8f.png)

**Comment by ArchLeaders** [comment]
You need Python `3.8` or `3.7`.

**Comment by xFedee** [comment]
i have python 3.10, i need to install python 8?

**Comment by xFedee** [comment]
i tryed install using an aur helper but i have an
![image](https://user-images.githubusercontent.com/87451140/194782401-f2236a1a-68ff-492b-a794-1c48f9e1a0fa.png)
![image](https://user-images.githubusercontent.com/87451140/194782404-751665d3-9d83-4734-bd69-fd794c071246.png)
other error

**Comment by ArchLeaders** [comment]
> i tryed install using an aur helper but i have an [...] [...] other error

Run `python3 --version` to check your version, and make sure one of the valid versions is printed.

I don't use linux, so I may not be able to help much beyond that, but you can message me in my Discord server if you want and I'll try to help troubleshoot the issue: https://discord.gg/cbA3AWwfJj
