### ISSUE TITLE
Infinite Installing and Deleting

### ISSUE THREAD

**Issue by Kinrex** [NiceneNerd/BCML#434]
I have installed the new BCML and imported the configuration of a very old version of my BCML, when I did the configuration at the time of importing the configuration and the mods entered an infinite loop.

After that I have tried to simply reinstall them and the same thing happened to me, and when I close and reopen the program, the mod comes out and with the doubt of whether it is really installed or not I try to uninstall it and it enters another loop again.

The Installing problem with the debug:

> Preparing output folder at D:\Emuladores\Cemu - Wii U\graphicPacks\BreathOfTheWild_BCML
> thread '<unnamed>' panicked at 'Failed to spawn mklink process: Error { kind: NotFound, message: "program not found" }', src\manager.rs:161:26
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> Exception in thread Thread-14:
> Traceback (most recent call last):
>   File "d:\python\lib\threading.py", line 932, in _bootstrap_inner
>     self.run()
>   File "d:\python\lib\threading.py", line 870, in run
>     self._target(*self._args, **self._kwargs)
>   File "d:\python\lib\site-packages\webview\util.py", line 138, in _call
>     result = func(*func_params.values())
>   File "d:\python\lib\site-packages\bcml\_api.py", line 33, in status_run
>     data = func(*args, **kwargs)
>   File "d:\python\lib\site-packages\bcml\install.py", line 265, in do_and_refresh
>     refresh_master_export()
>   File "d:\python\lib\site-packages\bcml\util.py", line 464, in timed_function
>     res = func(*args, **kwargs)
>   File "d:\python\lib\site-packages\bcml\install.py", line 274, in refresh_master_export
>     link_master_mod()
>   File "d:\python\lib\site-packages\bcml\install.py", line 745, in link_master_mod
>     rsext.manager.link_master_mod(str(output) if output else None)
> pyo3_runtime.PanicException: Failed to spawn mklink process: Error { kind: NotFound, message: "program not found" }

**Comment by NiceneNerd** [comment]
For some reason it can't find `mklink` on your system. What happens if you run `mklink` in the Command Prompt?

**Comment by Kinrex** [comment]
I just tried to invoke the mklink command in the cmd, it detects it and shows me the instructions on how to use it.

As additional information, I have seen that the folder "BreathOfTheWild_BCML" did not exist in the path and had the folder of the previous version of the software that was "BCML", I have tried to create the folder manually but there has been no luck.

**Comment by King-Broken** [comment]
I have this exact same error when checking debug.
I've looked everywhere for a solution and just can't get it to work.

**Comment by GingerAvalanche** [comment]
I don't think it's `mklink` that's missing, I think it's powershell. Some systems, for some reason, can't invoke powershell on the command line, which is what's going on. You can either fix powershell - which, I have no idea what's going on, so I wouldn't be able to help you - or you can check the setting to `Disable links for master mod` in the settings and it'll copy the files instead of `mklink`ing them.
