### ISSUE TITLE
BCML does not work on Linux build

### ISSUE THREAD

**Issue by Zetsphiron** [NiceneNerd/BCML#435]
Even after installing using pyenv, it seems BCML's setup requires that your cemu folder contains a cemu.exe, which is not the case for the new 2.0 Linux builds.

**Comment by HGStone** [comment]
you need to configure bcml to "use without cemu" and then setup a merged export directory where you want the merged bcml graphic pack to be..

**Comment by Zetsphiron** [comment]
Alright
I'll reinstall the packages and bcml through pyenv (since my distro uses python 3.10) and then report back to confirm closing the issue.

**Comment by Zetsphiron** [comment]
For now I found out that...

https://github.com/NiceneNerd/BCML/issues/421#issuecomment-1281299774

Using the resulting graphics pack made by BCML through WIndows works wonders on Linux. Needs more testing as if copying the resulting graphics pack made by BCML on Linux would work any differently. I will move to the afore...linked issue to avoid duplicates.

**Comment by jpenguin** [comment]
On garuda (arch based), I had to do a couple extra thing, including installing an older version of python

```
mkdir -p ~/.local/share/cemu/graphicPacks/BreathOfTheWild_BCML
python3.9 -m venv /.local/bcml_env
source ~/.local/bcml_env/bin/activate
pip inststall bcmL
~/.local/bcml_env/bin/
```

- In BCML, check 'without cemu' & 'disable links for master mod'; set export path to '~/.local/share/cemu/graphicPacks/BreathOfTheWild_BCML'
- install your mods

`curl https://pastebin.com/raw/igCLK2tz -o ~/.local/share/cemu/graphicPacks/BreathOfTheWild_BCML/rules.txt`
