### ISSUE TITLE
issue installing bcml

### ISSUE THREAD

**Issue by BBandit18** [NiceneNerd/BCML#444]
I keep getting this messeage 

note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for numpy
Failed to build numpy
ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects 

please help

**Comment by HGStone** [comment]
https://zeldamods.org/wiki/Help:Tools/BCML

**Comment by BBandit18** [comment]
and what am I looking for at this link? I'm a newbie at this could be more specific

**Comment by NiceneNerd** [comment]
You're probably not using a supported Python version
