### ISSUE TITLE
Infinite un/installing

### ISSUE THREAD

**Issue by therealcharmics** [NiceneNerd/BCML#445]
When attempting to perform mod operations, it gets stuck on the loading popup.

From bcml-debug:

> PS C:\Users\Polaroid> bcml-debug
> [pywebview] Using WinForms / CEF
> 
> DevTools listening on ws://127.0.0.1:62185/devtools/browser/fd9287bc-b98b-46fa-aac5-283f1868869d
> CEF window with uid master does not exist
> CEF window with uid master does not exist
> VERBOSE[]
> VERBOSE{
>   "mods": [
>     "C:\\Users\\Polaroid\\Games\\Cemu\\mods\\thelinklemod301.bnp"
>   ],
>   "options": {
>     "disable": [],
>     "options": {}
>   },
>   "selects": {
>     "C:\\Users\\Polaroid\\Games\\Cemu\\mods\\thelinklemod301.bnp": [
>       "Royal Weapons"
>     ]
>   }
> }
> Opening mod...
> Identified mod: The Linkle Mod 3.0.1
> Loading mod logs...
> Assigned mod priority of 100
> Moving mod to C:\Users\Polaroid\AppData\Local\bcml\mods\0100_TheLinkleMod3.0.1...
> VERBOSEInstalled 1 mods
> Installed 1 mods
> Cleansing old merges...
> Refreshing merged mods...
> Loading modded SARC list...
> Merging 132 SARC files...
> thread '<unnamed>' panicked at 'Failed to read settings file: Error("missing field `dark_theme`", line: 26, column: 1)', src\settings.rs:214:14
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> Exception in thread Thread-14:
> Traceback (most recent call last):
>   File "c:\python\lib\threading.py", line 932, in _bootstrap_inner
>     self.run()
>   File "c:\python\lib\threading.py", line 870, in run
>     self._target(*self._args, **self._kwargs)
>   File "c:\python\lib\site-packages\webview\util.py", line 138, in _call
>     result = func(*func_params.values())
>   File "c:\python\lib\site-packages\bcml\_api.py", line 33, in status_run
>     data = func(*args, **kwargs)
>   File "c:\python\lib\site-packages\bcml\install.py", line 264, in do_and_refresh
>     res = func(*args, **kwargs)
>   File "c:\python\lib\site-packages\bcml\_api.py", line 406, in install_mod
>     install.refresh_merges()
>   File "c:\python\lib\site-packages\bcml\install.py", line 602, in refresh_merges
>     merger.perform_merge()
>   File "c:\python\lib\site-packages\bcml\util.py", line 464, in timed_function
>     res = func(*args, **kwargs)
>   File "c:\python\lib\site-packages\bcml\mergers\pack.py", line 206, in perform_merge
>     rsext.mergers.packs.merge_sarcs(sarcs)
> pyo3_runtime.PanicException: Failed to read settings file: Error("missing field `dark_theme`", line: 26, column: 1)

...at which point it gets stuck and I must manually terminate. 

I have uninstalled everything (all python and pip) and reinstalled only requirements. I have tried running as admin. It seems to be a configuration thing? Dark theme????

(I did read all help documentation and google much as well.)

**Comment by NiceneNerd** [comment]
Try just adding a `"dark_theme" = false,` line to `settings.json`

**Comment by therealcharmics** [comment]
On my way to attempt this, I ran debug mode as admin from an admin PowerShell and that seems to have fixed it.

**Comment by therealcharmics** [comment]
Closing issue.
