### ISSUE TITLE
BCML fails to install

### ISSUE THREAD

**Issue by Sergorov** [NiceneNerd/BCML#447]
Hello. This issue could be related to [BCML fails to install - metadata generation failed](https://github.com/NiceneNerd/BCML/issues/420)

I tried to install BCML via pip, and I also tried the installation batch from https://gamebanana.com/tools/7462. 
vc_redist.x64.exe and python-3.8.10-amd64.exe install fine, manually as well as via the batch script. But "pip install bcml -q" always fails. When running "pip install bcml" manually via cmd you can see it works up until this:

`Building wheel for bcml (pyproject.toml) ... error`

**Comment by GingerAvalanche** [comment]
Can you post the entire log, not just the error line? It almost looks like it's trying to *make* the wheel. It's supposed to download the correct wheel and then just extract it to the right folder.

**Comment by Sergorov** [comment]
`C:\WINDOWS\system32>pip install bcml
Collecting bcml
  Using cached bcml-3.9.27.tar.gz (12.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting rstb>=1.2.2
  Using cached rstb-1.2.2-py3-none-any.whl (15 kB)
Collecting PyYAML~=5.4.1
  Using cached PyYAML-5.4.1-cp38-cp38-win32.whl (196 kB)
Collecting pythonnet==2.5.2
  Using cached pythonnet-2.5.2-cp38-cp38-win32.whl (81 kB)
Collecting numpy==1.19.2
  Using cached numpy-1.19.2-cp38-cp38-win32.whl (10.9 MB)
Collecting byml~=2.4.2
  Using cached byml-2.4.2-py3-none-any.whl (16 kB)
Requirement already satisfied: cefpython3~=66.1 in d:\programme\python38-32\lib\site-packages (from bcml) (66.1)
Collecting oead~=1.2.4
  Using cached oead-1.2.4.post2.tar.gz (36 kB)
  Preparing metadata (setup.py) ... done
Collecting packaging~=21.3
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
Collecting aamp~=1.4.1
  Using cached aamp-1.4.1-py3-none-any.whl (337 kB)
Collecting pywebview~=3.6.3
  Using cached pywebview-3.6.3-py3-none-any.whl (351 kB)
Collecting xxhash~=1.4
  Using cached xxhash-1.4.4-cp38-cp38-win32.whl (16 kB)
Collecting botw-utils~=0.2.3
  Using cached botw_utils-0.2.3-py3-none-any.whl (3.5 MB)
Collecting requests~=2.27.1
  Using cached requests-2.27.1-py2.py3-none-any.whl (63 kB)
Collecting botw-havok~=0.3.18
  Using cached botw_havok-0.3.18-py3-none-any.whl (117 kB)
Collecting pycparser
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Collecting colorama~=0.4.3
  Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting sortedcontainers~=2.0
  Using cached sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Collecting pyparsing!=3.0.5,>=2.0.2
  Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
Collecting proxy-tools
  Using cached proxy_tools-0.1.0.tar.gz (3.0 kB)
  Preparing metadata (setup.py) ... done
Collecting idna<4,>=2.5
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.12-py2.py3-none-any.whl (140 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2022.9.24-py3-none-any.whl (161 kB)
Collecting charset-normalizer~=2.0.0
  Using cached charset_normalizer-2.0.12-py3-none-any.whl (39 kB)
Building wheels for collected packages: bcml
  Building wheel for bcml (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for bcml (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [150 lines of output]
      Running `maturin pep517 build-wheel -i d:\programme\python38-32\python.exe --compatibility off --target i686-pc-windows-msvc`
         Compiling autocfg v1.1.0
         Compiling proc-macro2 v1.0.47
         Compiling unicode-ident v1.0.5
         Compiling quote v1.0.21
         Compiling syn v1.0.103
         Compiling cfg-if v1.0.0
         Compiling scopeguard v1.1.0
         Compiling crossbeam-utils v0.8.12
      error: could not compile `cfg-if` due to 3 previous errors
      warning: build failed, waiting for other jobs to finish...
      error: could not compile `scopeguard` due to 17 previous errors
      ðŸ’¥ maturin failed
        Caused by: Failed to build a native library through cargo
        Caused by: Cargo build finished with "exit code: 101": `cargo rustc --manifest-path Cargo.toml --message-format json --release --lib --`
      ðŸ\x8d¹ Building a mixed python/rust project
      ðŸ”— Found pyo3 bindings
      ðŸ\x90\x8d Found CPython 3.8 at d:\programme\python38-32\python.exe
      error[E0463]: can't find crate for `core`
        |
        = note: the `i686-pc-windows-msvc` target may not be installed
        = help: consider downloading the target with `rustup target add i686-pc-windows-msvc`


      error[E0463]: can't find crate for `core`
        |
        = note: the `i686-pc-windows-msvc` target may not be installed
        = help: consider downloading the target with `rustup target add i686-pc-windows-msvc`


      error[E0463]: can't find crate for `compiler_builtins`


      error[E0463]: can't find crate for `compiler_builtins`


      error: aborting due to 2 previous errors


      For more information about this error, try `rustc --explain E0463`.

      error[E0463]: can't find crate for `core`
         --> C:\Users\Steamer\.cargo\registry\src\github.com-1ecc6299db9ec823\scopeguard-1.1.0\src\lib.rs:192:1
          |
      192 | extern crate core as std;
          | ^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
          |
          = note: the `i686-pc-windows-msvc` target may not be installed
          = help: consider downloading the target with `rustup target add i686-pc-windows-msvc`


      error: cannot find macro `stringify` in this scope
         --> C:\Users\Steamer\.cargo\registry\src\github.com-1ecc6299db9ec823\scopeguard-1.1.0\src\lib.rs:470:24
          |
      470 |         f.debug_struct(stringify!(ScopeGuard))
          |                        ^^^^^^^^^


      error: cannot find attribute `derive` in this scope
         --> C:\Users\Steamer\.cargo\registry\src\github.com-1ecc6299db9ec823\scopeguard-1.1.0\src\lib.rs:212:3
          |
      212 | #[derive(Debug)]
          |   ^^^^^^


      error[E0405]: cannot find trait `FnOnce` in this scope
         --> C:\Users\Steamer\.cargo\registry\src\github.com-1ecc6299db9ec823\scopeguard-1.1.0\src\lib.rs:299:14
          |
      299 |     where F: FnOnce(T),
          |              ^^^^^^ not found in this scope


      error[E0405]: cannot find trait `FnOnce` in this scope
         --> C:\Users\Steamer\.cargo\registry\src\github.com-1ecc6299db9ec823\scopeguard-1.1.0\src\lib.rs:309:14
          |
      309 |     where F: FnOnce(T),
          |              ^^^^^^ not found in this scope


      error[E0405]: cannot find trait `FnOnce` in this scope
         --> C:\Users\Steamer\.cargo\registry\src\github.com-1ecc6299db9ec823\scopeguard-1.1.0\src\lib.rs:368:14
          |
      368 |     where F: FnOnce(T)
          |              ^^^^^^ not found in this scope


      error[E0405]: cannot find trait `Sync` in this scope
         --> C:\Users\Steamer\.cargo\registry\src\github.com-1ecc6299db9ec823\scopeguard-1.1.0\src\lib.rs:422:22
          |
      422 | unsafe impl<T, F, S> Sync for ScopeGuard<T, F, S>
          |                      ^^^^ not found in this scope


      error[E0405]: cannot find trait `Sync` in this scope
         --> C:\Users\Steamer\.cargo\registry\src\github.com-1ecc6299db9ec823\scopeguard-1.1.0\src\lib.rs:423:14
          |
      423 |     where T: Sync,
          |              ^^^^ not found in this scope


      error[E0405]: cannot find trait `FnOnce` in this scope
         --> C:\Users\Steamer\.cargo\registry\src\github.com-1ecc6299db9ec823\scopeguard-1.1.0\src\lib.rs:424:14
          |
      424 |           F: FnOnce(T),
          |              ^^^^^^ not found in this scope


      error[E0405]: cannot find trait `FnOnce` in this scope
         --> C:\Users\Steamer\.cargo\registry\src\github.com-1ecc6299db9ec823\scopeguard-1.1.0\src\lib.rs:429:14
          |
      429 |     where F: FnOnce(T),
          |              ^^^^^^ not found in this scope


      error[E0405]: cannot find trait `FnOnce` in this scope
         --> C:\Users\Steamer\.cargo\registry\src\github.com-1ecc6299db9ec823\scopeguard-1.1.0\src\lib.rs:440:14
          |
      440 |     where F: FnOnce(T),
          |              ^^^^^^ not found in this scope


      error[E0405]: cannot find trait `Drop` in this scope
         --> C:\Users\Steamer\.cargo\registry\src\github.com-1ecc6299db9ec823\scopeguard-1.1.0\src\lib.rs:448:15
          |
      448 | impl<T, F, S> Drop for ScopeGuard<T, F, S>
          |               ^^^^ not found in this scope


      error[E0405]: cannot find trait `FnOnce` in this scope
         --> C:\Users\Steamer\.cargo\registry\src\github.com-1ecc6299db9ec823\scopeguard-1.1.0\src\lib.rs:449:14
          |
      449 |     where F: FnOnce(T),
          |              ^^^^^^ not found in this scope


      error[E0405]: cannot find trait `FnOnce` in this scope
         --> C:\Users\Steamer\.cargo\registry\src\github.com-1ecc6299db9ec823\scopeguard-1.1.0\src\lib.rs:466:14
          |
      466 |           F: FnOnce(T),
          |              ^^^^^^ not found in this scope


      error: aborting due to 16 previous errors


      Some errors have detailed explanations: E0405, E0463.

      For more information about an error, try `rustc --explain E0405`.

      Error: command ['maturin', 'pep517', 'build-wheel', '-i', 'd:\\programme\\python38-32\\python.exe', '--compatibility', 'off', '--target', 'i686-pc-windows-msvc'] returned non-zero exit status 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for bcml
Failed to build bcml
ERROR: Could not build wheels for bcml, which is required to install pyproject.toml-based projects

C:\WINDOWS\system32>`

**Comment by Sergorov** [comment]
What I should possibly mention: 
- this is my very first attempt to install BCML. So there should be no traces of previous installs
- Rust and python have been installed already, but I didn't use it much, so no tweaked or customized setup. Just srandard installs.
- I'm running on Windows 10 64 bit

**Comment by GingerAvalanche** [comment]
Cargo isn't installed properly, it looks like. It can't find the core rust code library.

**Comment by NiceneNerd** [comment]
The problem is you have 32 bit Python. You need 64 bit.

**Comment by Sergorov** [comment]
Thanks for the tip! I used this installer:
https://www.python.org/ftp/python/3.8.10/python-3.8.10-amd64.exe
(which by the way is the same one the batch script installs). Yet for some reason the actual pip installer insisted on using an age old 32 bit install of Python I didn't even remember I had instead of the freshly installed 64 bit version. Once that old install was removed it worked!

**Comment by NiceneNerd** [comment]
Python version management does tend to be weird and annoying
