### ISSUE TITLE
BCML infinite export loading

### ISSUE THREAD

**Issue by SZY13** [NiceneNerd/BCML#448]
Everything is set up but every time I try to export a mod it is stuck on the export loading screen.

**Comment by GingerAvalanche** [comment]
What bcml version?

**Comment by SZY13** [comment]
> What bcml version?

I'm not home rn as soon as I am will let you know

**Comment by SZY13** [comment]
> What bcml version?
3.9.27

**Comment by SZY13** [comment]
> > What bcml version?
> 3.9.27
Tried exporting to a different drive see if it would do anything and I got this error. ![image](https://user-images.githubusercontent.com/118072784/201503363-424d1e1d-180b-4f79-9e9b-d374d19d597c.jpeg)

**Comment by SwordArtXD** [comment]
What’s your python version?

**Comment by SZY13** [comment]
> What’s your python version?

3.8.8
