### ISSUE TITLE
Game crash after loading shader with any mod

### ISSUE THREAD

**Issue by DeathSkor** [NiceneNerd/BCML#453]
With any mod the game crash after loading the shader, i saw that i have to do something with the bootup file but idk why, there is the log of cemu ; https://pastebin.com/PmV275NN

**Comment by GingerAvalanche** [comment]
If it happens with *any* mod then it's not BCML's problem.

If it happens only with mods that contain Bootup.pack, then there must be a problem with those mods, as BCML properly merges every mod with Bootup.pack that has been reported so far.

**Comment by DeathSkor** [comment]
but i use like very famous mod (such as armor slot for Relic of the past) but so if it's bcml do you klnow where is the problem
 ?

**Comment by NiceneNerd** [comment]
There is a list of all the possible causes in BCML's help.
