### ISSUE TITLE
No more VC C++ or x86_86 dependency for building?

### ISSUE THREAD

**Issue by hstriepe** [NiceneNerd/BCML#454]
Since you switched to Rust in the latest version, is there still any VC C++ or X86_64 dylib dependency?

I am asking since this might make a macOS port straightforward. CEMU 2 now runs on macOS.

**Comment by NiceneNerd** [comment]
It didn't switch to Rust; it just moved some of the worst performance bottlenecks to Rust. All the other stuff is still there, including `oead`, which is what demands VC++.

**Comment by hstriepe** [comment]
I just saw there is a Mac version. Porting is theoretically possible.
