### ISSUE TITLE
Nothing Happens?

### ISSUE THREAD

**Issue by Werns** [NiceneNerd/BCML#455]
I've installed all the prerequisites (Python 3.9 64 bit, x64 Visual C++ redist, Cemu, running on Windows 11).
When I run either bcml.exe or the bcml command line prompt, nothing happens. Changed the file to run in administator mode, no difference. What have I done wrong?

**Comment by GingerAvalanche** [comment]
Uninstall python 3.9, install python 3.8, install bcml again

**Comment by Werns** [comment]
Why list 3.9 if it doesn't work?
![image](https://user-images.githubusercontent.com/12315835/205509509-0218524b-9887-4b52-bff9-41c0eb947875.png)

**Comment by NiceneNerd** [comment]
On Linux it always works. On Windows it works for some people (such as myself), but other people have problems with it.

**Comment by Werns** [comment]
Hm, strange.
