### ISSUE TITLE
 Preparing metadata (pyproject.toml) ... error   error: subprocess-exited-with-error

### ISSUE THREAD

**Issue by pleasejustgo** [NiceneNerd/BCML#477]
I can't install bcml I get an error:

Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

This is ludicrous. Just make a proper installer....

**Comment by HGStone** [comment]
it works fine on windows 11, please ensure you are using either python 3.7.9 or 3.8.10 ,  64 bit

**Comment by NiceneNerd** [comment]
> I can't install bcml I get an error:
> 
> Preparing metadata (pyproject.toml) ... error error: subprocess-exited-with-error

Try using a supported Python version. That usually means 3.7 or 3.8 on Windows, and for some people but not all 3.9 works.

> This is ludicrous. Just make a proper installer....

pip is the proper installer for Python packages. But this is an open source project, so if you would like to create some other, difficult-to-maintain Frankenstein option, you are free to do so.
