### ISSUE TITLE
BCML doesn't start CEMU

### ISSUE THREAD

**Issue by TheMemeOfficer** [NiceneNerd/BCML#48]
This might be me just being dumb, but when I click "Launch Game" nothing happens, other than the button dimming. I have 7 mods installed, including the Linkle mod, though I doubt my mods are the issue.

**Comment by NiceneNerd** [comment]
Do you usually run Cemu as administrator?

**Comment by TheMemeOfficer** [comment]
Yeah, would I have to run BCML as an admin as well, or just disable that in the properties of CEMU?

**Comment by NiceneNerd** [comment]
Either should probably solve it.

**Comment by TheMemeOfficer** [comment]
^ Just ran BCML as admin, and it started CEMU. I'll go in and change the properties of BCML so that it always runs as admin as well. Thanks for the super fast replies btw. An actual saint right here

**Comment by NiceneNerd** [comment]
'Tis my pleasure, always glad to help.
