### ISSUE TITLE
norton thinks BCML is a threat when run from cmdline

### ISSUE THREAD

**Issue by ZGStuff** [NiceneNerd/BCML#481]
exactly as it sounds...

python crashes when i try to run BCML bc of it

**Comment by GingerAvalanche** [comment]
Considering Norton is, among the computer security community, widely considered to be both a virus, itself, and worse than any built-in OS antivirus (Windows Defender, for example), I don't think we're going to try and figure out what arcane sorcery makes it think BCML is a virus.

My general computer suggestion is to remove it and activate Windows Defender if you're on Windows, or whatever your Linux build uses if you're on Linux.

If you're not willing to do that, my suggestion is to make an exception in Norton for BCML.

**Comment by ZGStuff** [comment]
lol i just had to change it to Python 3.8.10 and not python 3.9

but
I'm stuck playing on family PC
so I have to use norton
