### ISSUE TITLE
how am i supposed to use bcml directly on my switch?

### ISSUE THREAD

**Issue by nity0814** [NiceneNerd/BCML#483]

**Comment by NiceneNerd** [comment]
That's rather impossible. You run BCML on your PC and then export your merged mods to your SD card for Switch, as explained [here](https://github.com/NiceneNerd/BCML/blob/master/docs/export.md).

**Comment by nity0814** [comment]
![image](https://user-images.githubusercontent.com/79995972/210600202-94148c13-3d67-471a-9886-4749ec1bcb39.png)
what do i do here then

**Comment by nity0814** [comment]
![image](https://user-images.githubusercontent.com/79995972/210601003-72765cef-5cc0-4e02-a8ac-6a1f1eeff1d3.png)
i cant  select language too

**Comment by nity0814** [comment]
![image](https://user-images.githubusercontent.com/79995972/210601142-3490ecaa-39c9-4c97-92ed-32da865e8287.png)

**Comment by nity0814** [comment]
i need game file tho

**Comment by NiceneNerd** [comment]
Then [dump them](https://zeldamods.org/wiki/Help:Dumping_games)

**Comment by nity0814** [comment]
i don't have a wiiU-

**Comment by GingerAvalanche** [comment]
That's why you scroll down on that page to the part that says "Switch" and read how to dump them from your Switch.

**Comment by nity0814** [comment]
i didnt saw first

**Comment by nity0814** [comment]
gotta wait 24h to dump the files

**Comment by nity0814** [comment]
it askq me to merge the game file with update file I have both but idk how to merge them I didn't find anything on google abt it
