### ISSUE TITLE
python 3.9.13 / bcml 3.10.1 NullReferenceException

### ISSUE THREAD

**Issue by mickokenter** [NiceneNerd/BCML#486]
bcml won't open after successfully installation.
python --version: 3.9.13
bcml: 3.10.1

By running bcml-debug it shows below bug:

> [pywebview] Using WinForms / CEF
> 
> DevTools listening on ws://127.0.0.1:54162/devtools/browser/e5178adf-4209-4f08-bec8-740391c59441
> 
> Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
>    at System.Windows.Forms.Control.get_CacheTextInternal()
>    at System.Windows.Forms.Control.get_Text()
>    at System.Windows.Forms.Control.set_Text(String value)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Python.Runtime.PythonException.ThrowLastAsClrException()
>    at Python.Runtime.Dispatcher.TrueDispatch(Object[] args)
>    at Python.Runtime.Dispatcher.Dispatch(Object[] args)
>    at __System_Threading_ThreadStartDispatcher.Invoke()
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Threading.ThreadHelper.ThreadStart()

**Comment by GingerAvalanche** [comment]
BCML is only supported on windows for 3.7 and 3.8. 3.9 works for some people but not others on Windows, and for everyone on Linux.
