### ISSUE TITLE
BCML Won't open and can't install mods

### ISSUE THREAD

**Issue by KittenPixel-cell** [NiceneNerd/BCML#493]
When I try to install mods it won't work same thing when trying to run it won't work I am running bcml in console

**Comment by KittenPixel-cell** [comment]
Fixed but the directorys it tells me to go to for the base game update and DLC doesn't work

**Comment by KittenPixel-cell** [comment]
didn't mean to close it there

**Comment by NiceneNerd** [comment]
Everything you need to know for the directories is in the docs.
