### ISSUE TITLE
When launching it gives an error

### ISSUE THREAD

**Issue by KittenPixel-cell** [NiceneNerd/BCML#494]
when I launch BOTW from BCML it gives the error

You must perform a system update
to play The Legend Of Zelda:
BOTW

Returnng to Wii U Menu

On normal cemu this does not occur

**Comment by GingerAvalanche** [comment]
You don't need to launch Cemu with BCML, the button is there for convenience. Once the mods are installed, you can just open Cemu regularly.

**Comment by ArchLeaders** [comment]
This likely means you have two Cemu instances, one with the botw update installed (this would be the Cemu you run normally) and one without the botw update (this would be the one BCML is pointing to), change the BCML settings to point to the first instance that you're running manually (I.e. the one with the botw update installed).
