### ISSUE TITLE
How do I launch the mods from CEMU

### ISSUE THREAD

**Issue by KittenPixel-cell** [NiceneNerd/BCML#495]
When I launch the mods from CEMU it doesn't load them?

**Comment by ArchLeaders** [comment]
Make sure BCML is pointing to the right Cemu install, see #494 for more details.

**Comment by KittenPixel-cell** [comment]
it is

**Comment by KittenPixel-cell** [comment]
fixed

**Comment by KittenPixel-cell** [comment]
I think

**Comment by KittenPixel-cell** [comment]
checking

**Comment by KittenPixel-cell** [comment]
nope

**Comment by GingerAvalanche** [comment]
Please join the Discord server and ask for help if you continue needing it. The Github issues are for problems with BCML, not for user error. https://discord.gg/y7VJqMB329
