### ISSUE TITLE
BCML won’t recognize game directory

### ISSUE THREAD

**Issue by Ranchichi** [NiceneNerd/BCML#497]
Just installed bcml and filled in the required directories. I got a check on all the ones except game directory.

**Comment by ArchLeaders** [comment]
Then your game directory is wrong or incomplete. Check the tooltips for more info on getting the right one.
I can probably also provide more info if you upload your settings file (`%localappdata%\bcml\settings.json`)

**Comment by Ranchichi** [comment]
I've tried different things but doesn't seem to work.
My current directory is
D:\Wii U games folder\DATA\EMULATORS\Cemu\GAMES\The Legend of Zelda Breath of the Wild [ALZJ]\content

My settings.json:
{"cemu_dir": "", "game_dir": "", "game_dir_nx": "", "update_dir": "", "dlc_dir": "", "dlc_dir_nx": "", "store_dir": "C:\\Users\\81806\\AppData\\Local\\bcml", "export_dir": "", "export_dir_nx": "", "load_reverse": false, "site_meta": "", "dark_theme": false, "no_guess": false, "lang": "", "no_cemu": false, "wiiu": true, "no_hardlinks": false, "force_7z": false, "suppress_update": false, "nsfw": false, "last_version": "3.10.4", "changelog": true, "strip_gfx": false, "auto_gb": true, "show_gb": false}

**Comment by ArchLeaders** [comment]
Can you send a screenshot of the contents of `D:\Wii U games folder\DATA\EMULATORS\Cemu\GAMES\The Legend of Zelda Breath of the Wild [ALZJ]\content`?

**Comment by Ranchichi** [comment]
![Screenshot 2023-01-29 144549](https://user-images.githubusercontent.com/123855420/215307578-7647f2ae-4198-44d5-940a-f8f427cb974b.png)

**Comment by ArchLeaders** [comment]
Looks alright. Maybe try restarting BCML?

**Comment by Ranchichi** [comment]
I'm still getting the same issue.

**Comment by ArchLeaders** [comment]
Hmm, not sure then. I guess redump if nothing else works?
You can also get help in the discord server: https://discord.gg/vPzgy5S

**Comment by GingerAvalanche** [comment]
The game directory folder validation function asks "does `[path]/Pack/Dungeon000.pack` exist?" And if the answer is "yes," is puts a green checkmark there. If it doesn't exist, it doesn't put the checkmark there.

If the path you supplied doesn't contain a folder called Pack that contains a file called Dungeon000.pack, then that explains why the green checkmark won't appear.

Also, don't pirate the game. Dump it from your console.
