### ISSUE TITLE
How to update existing BNPs?

### ISSUE THREAD

**Issue by Kykuy** [NiceneNerd/BCML#499]
I want to update my existing BNP mod with new content. Is there any way to do so without creating a new BNP from scratch?
"Update old BNP" button in DevTools seems like not what I need sadly(

**Comment by HGStone** [comment]
you can do a "bnp to standalone" do your changes. then make a new bnp

**Comment by Kykuy** [comment]
> you can do a "bnp to standalone" do your changes. then make a new bnp

I've been making changes to a folder with "content" from which I've made the original BNP and then creating a new BNP. This sounds similar but with extra steps as if I didn't have the source files, but I wonder if there's any way to "override" the BNP with new content without having to fill out all the meta info with mod name, version, image etc. anew.

I think you could copy one of the JSONs that hold this data and then replace, but I hope there is a more streamlined way within BCML to do this which I simply overlooked.

**Comment by GingerAvalanche** [comment]
"Update old BNP" is for converting BNPs that used the old logging system to the "new" (still a couple years old) logging system.

There's no implementation of what you're asking for. Since BCML is only being supported for bug fixes now, it's not going to happen. UKMM will soon (-ish) make BCML (and BNPs) obsolete anyway.

**Comment by HGStone** [comment]
> > you can do a "bnp to standalone" do your changes. then make a new bnp
> 
> I've been making changes to a folder with "content" from which I've made the original BNP and then creating a new BNP. This sounds similar but with extra steps as if I didn't have the source files, but I wonder if there's any way to "override" the BNP with new content without having to fill out all the meta info with mod name, version, image etc. anew.
> 
> I think you could copy one of the JSONs that hold this data and then replace, but I hope there is a more streamlined way within BCML to do this which I simply overlooked.

you can place a info.json in your folder that you build the bnp out of and it will autofill the data everytime

**Comment by Kykuy** [comment]
> > > you can do a "bnp to standalone" do your changes. then make a new bnp
> > 
> > 
> > I've been making changes to a folder with "content" from which I've made the original BNP and then creating a new BNP. This sounds similar but with extra steps as if I didn't have the source files, but I wonder if there's any way to "override" the BNP with new content without having to fill out all the meta info with mod name, version, image etc. anew.
> > I think you could copy one of the JSONs that hold this data and then replace, but I hope there is a more streamlined way within BCML to do this which I simply overlooked.
> 
> you can place a info.json in your folder that you build the bnp out of and it will autofill the data everytime

I will try this, thanks.
