### ISSUE TITLE
BoTW won't launch from BCML

### ISSUE THREAD

**Issue by KayloBlaze** [NiceneNerd/BCML#50]
I can't launch BoTW from BCML and can't figure out why. I see the cmd prompt pop up and then nothing happens.

Update: I just got this error: Parameter cannot be processed because the parameter name 'g' is ambiguous. Possible matches include -gamePath gameId -glCacheSizeTolerance.

**Comment by NiceneNerd** [comment]
Cemu must have changed the flags. I'll have to update those.

**Comment by KayloBlaze** [comment]
1.19.0d is the newest version

**Comment by NiceneNerd** [comment]
Odd, I just updated to Cemu 1.19 and the `-g` flag still works

**Comment by KayloBlaze** [comment]
I was on BMCL 3.0b9 but when I downgraded to back to 2.8 that was on GameBanana it works. I want to try updating again to test. It might be something unique to me.

**Comment by KayloBlaze** [comment]
Yeah, I just tried doing a clean install of 3.0b7 as that the newest with a .exe and it won't even start for some reason when I was using 2.8 just earlier. There's something breaking on my end. Not sure what but 2.8 works fine for me.

**Comment by NiceneNerd** [comment]
Try 3.0.0b9

**Comment by 4thwsix** [comment]
I'm having the same issue, however even 2.8 can't launch CEMU.

**Comment by NiceneNerd** [comment]
@4thwsix Do you Cemu as admin? If so you would also need to run BCML as admin.
