### ISSUE TITLE
white screen

### ISSUE THREAD

**Issue by bellisonoroff** [NiceneNerd/BCML#508]
fresh install, everything went normal, get a white screen on launch.

already tried pip install cefpython3

running in debug shows

[pywebview] WebView2 initialization failed with exception:
 Couldn't find a compatible Webview2 Runtime installation to host WebViews. ---> System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
   --- End of inner exception stack trace ---
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__24.MoveNext()

**Comment by bellisonoroff** [comment]
![image](https://user-images.githubusercontent.com/95214548/218240767-15d4234a-8732-4ddf-8074-38957e4c05ff.png)

**Comment by Alopexus** [comment]
Having this issue also.

[pywebview] WebView2 initialization failed with exception:
 Unable to load DLL 'WebView2Loader.dll' or one of its dependencies: The specified module could not be found (0x8007007E)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.LoadWebView2LoaderDll()
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__24.MoveNext()

**Comment by GingerAvalanche** [comment]
This is because you don't have the edgechromium renderer installed, and for some reason bcml both failed to install it and, unless you're not telling me something, it failed to pop up the window to tell you to install it, yourself.

You can download the installer for it, here: https://go.microsoft.com/fwlink/p/?LinkId=2124703

cefpython3 won't work for you because you're using python 3.10 or python 3.11, which cefpython3 doesn't support. If all else fails, install python 3.9 instead to use cefpython3.

Or just migrate your setup over to UKMM. https://gamebanana.com/tools/12110

**Comment by bellisonoroff** [comment]
![image](https://user-images.githubusercontent.com/95214548/218275257-c98cae9c-3cde-421c-84ff-7cb7fe42e7d7.png)
already did have that installed, but downgrading to python 3.9 resolved the issue. thank you.

**Comment by th3guard1an** [comment]
Read somewhere else that running in an older python version solved their problem, and it just fixed mine.
(I'm corrently on 3.9.13). Hope it helps.

**Comment by lufixe** [comment]
i tried what was said and it still is not working

**Comment by th3guard1an** [comment]
> i tried what was said and it still is not working

"If all else fails, install python 3.9 instead..." This worked for me, although I missed it at first.

**Comment by lufixe** [comment]
tried did not work
