### ISSUE TITLE
Can this be used with Ryujinx?

### ISSUE THREAD

**Issue by oatnoodles** [NiceneNerd/BCML#513]
I don't have any unpacked files, just an .NSP rom file.

**Comment by ArchLeaders** [comment]
You need to dump the game from your switch as RomFS instead of NSP.
https://zeldamods.org/wiki/Help:Dumping_games

**Comment by HGStone** [comment]
after doing what arch says.. then yes it would work with ryujinx

**Comment by oatnoodles** [comment]
So then it's impossible to do without a hacked switch?

**Comment by NiceneNerd** [comment]
It's impossible to even legally have BOTW on your PC without a hacked Switch, so yes
