### ISSUE TITLE
Unable to install mod 

### ISSUE THREAD

**Issue by KiroDragon** [NiceneNerd/BCML#515]
I had this mod installed before but I did a new install of my Windows so I had to install everythibng from scratch. 

I was able to install other mods just fine, here is my error code: 

Traceback (most recent call last):
  File "c:\users\kiro\appdata\local\programs\python\python39\lib\site-packages\bcml\install.py", line 295, in install_mod
    tmp_dir = open_mod(mod)
  File "c:\users\kiro\appdata\local\programs\python\python39\lib\site-packages\bcml\install.py", line 122, in open_mod
    upgrade.convert_old_mod(rulesdir, delete_old=True)
  File "c:\users\kiro\appdata\local\programs\python\python39\lib\site-packages\bcml\upgrade.py", line 38, in convert_old_mod
    info = parse_rules(mod / "rules.txt")
  File "c:\users\kiro\appdata\local\programs\python\python39\lib\site-packages\bcml\upgrade.py", line 74, in parse_rules
    "name": str(rules["Definition"]["name"]).strip("\"' "),
  File "c:\users\kiro\appdata\local\programs\python\python39\lib\configparser.py", line 960, in __getitem__
    raise KeyError(key)
KeyError: 'Definition'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\kiro\appdata\local\programs\python\python39\lib\site-packages\bcml\_api.py", line 33, in status_run
    data = func(*args, **kwargs)
  File "c:\users\kiro\appdata\local\programs\python\python39\lib\site-packages\bcml\install.py", line 264, in do_and_refresh
    res = func(*args, **kwargs)
  File "c:\users\kiro\appdata\local\programs\python\python39\lib\site-packages\bcml\_api.py", line 380, in install_mod
    mods = [
  File "c:\users\kiro\appdata\local\programs\python\python39\lib\site-packages\bcml\_api.py", line 381, in <listcomp>
    install.install_mod(
  File "c:\users\kiro\appdata\local\programs\python\python39\lib\site-packages\bcml\install.py", line 312, in install_mod
    raise util.InstallError(err) from err
bcml.util.InstallError: An error occured when installing your mod. 'Definition'
Your mod is being removed, and no changes have been made.

**Comment by HGStone** [comment]
support for old bnp was removed in version 3.10.5 so in order to use or upgrade older bnp files you must use version 3.10.4, you can downgrade by typing `pip install bcml==3.10.4` and most likely will also need to use python version 3.7.9 or 3.8.10

**Comment by KiroDragon** [comment]
> support for old bnp was removed in version 3.10.5 so in order to use or upgrade older bnp files you must use version 3.10.4, you can downgrade by typing `pip install bcml==3.10.4` and most likely will also need to use python version 3.7.9 or 3.8.10

When I do that, I get the following error code: 

   ERROR: Command errored out with exit status 1:
     command: 'c:\users\kiro\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Kiro\\AppData\\Local\\Temp\\pip-install-oxh8w9cb\\xxhash\\setup.py'"'"'; __file__='"'"'C:\\Users\\Kiro\\AppData\\Local\\Temp\\pip-install-oxh8w9cb\\xxhash\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Kiro\AppData\Local\Temp\pip-record-tfirjesm\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\kiro\appdata\local\programs\python\python39\Include\xxhash'
         cwd: C:\Users\Kiro\AppData\Local\Temp\pip-install-oxh8w9cb\xxhash\
    Complete output (10 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.9
    creating build\lib.win-amd64-3.9\xxhash
    copying xxhash\__init__.py -> build\lib.win-amd64-3.9\xxhash
    running build_ext
    building '_xxhash' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
  Rolling back uninstall of xxhash
  Moving to c:\users\kiro\appdata\local\programs\python\python39\lib\site-packages\xxhash-3.2.0.dist-info\
   from C:\Users\Kiro\AppData\Local\Programs\Python\Python39\Lib\site-packages\~xhash-3.2.0.dist-info
  Moving to c:\users\kiro\appdata\local\programs\python\python39\lib\site-packages\xxhash\
   from C:\Users\Kiro\AppData\Local\Programs\Python\Python39\Lib\site-packages\~xhash
ERROR: Command errored out with exit status 1: 'c:\users\kiro\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Kiro\\AppData\\Local\\Temp\\pip-install-oxh8w9cb\\xxhash\\setup.py'"'"'; __file__='"'"'C:\\Users\\Kiro\\AppData\\Local\\Temp\\pip-install-oxh8w9cb\\xxhash\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Kiro\AppData\Local\Temp\pip-record-tfirjesm\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\kiro\appdata\local\programs\python\python39\Include\xxhash' Check the logs for full command output.

**Comment by Benna96** [comment]
As HGStone said, you'd need 3.8.10. Reading the error it seems you have 3.9.

**Comment by KiroDragon** [comment]
> As HGStone said, you'd need 3.8.10. Reading the error it seems you have 3.9.

Yeah I just realized that and uninstalled python and installed python 3.8.10 it seems to work now

Big thanks to you two!
