### ISSUE TITLE
white screen

### ISSUE THREAD

**Issue by lufixe** [NiceneNerd/BCML#518]
hello i have a problem when i launch bcml it is just a white screen and it says this in cmd: 
[pywebview] WebView2 initialization failed with exception:
 Unable to load DLL 'WebView2Loader.dll' or one of its dependencies: Le module spécifié est introuvable (0x8007007E)
   à Microsoft.Web.WebView2.Core.CoreWebView2Environment.LoadWebView2LoaderDll()
   à Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__24.MoveNext()
can someone help me so i can download and use mods

**Comment by GingerAvalanche** [comment]
See https://github.com/NiceneNerd/BCML/issues/508
