### ISSUE TITLE
i can't create shortcut on my desktop or in my start menu 

### ISSUE THREAD

**Issue by LaReunion974** [NiceneNerd/BCML#519]
Every time when i try to create a shortcut it show this wide and empty error screen on both desktop or start menu button > 
![startmenu shortcut BCML error](https://user-images.githubusercontent.com/102532446/227563675-c9783d74-af67-4149-8715-c4fb82f3085a.png)
![desktop BCML error](https://user-images.githubusercontent.com/102532446/227563684-5a788b57-4a8a-4c96-943f-4e3b33f9a7f1.png)

**Comment by GingerAvalanche** [comment]
Unfortunately, there isn't really a way to diagnose the issue without any kind of error message.
