### ISSUE TITLE
7-Zip cannot find the code that works with archives.

### ISSUE THREAD

**Issue by BrokenGale** [NiceneNerd/BCML#52]
Configuration:
CPU: i5 4570
GPU: RX 480
OS: Pop_OS 20.04
CEMU version: 1.19.0d
BCML version: bcml-3.0.0b9
p7zip version: (16.02+dfsg-7build1).

Steps used to recreate bug. 
1) Install CEMU 1.17.3 using Lutris and update to 1.19.0d
2) Install bcml through pip3
3) Download hyrule_rebalance_v7_66ecf.bnp
4) Start bcml using: python3 -m bcml
5) Browse and install the mod.
6) Look at the terminal output.

![Screenshot from 2020-05-18 11-29-16](https://user-images.githubusercontent.com/39289368/82256127-a4b0e300-990a-11ea-959d-b87de05d6a35.png)

concurrently bcml hangs on this screen.
![Screenshot from 2020-05-18 11-29-33](https://user-images.githubusercontent.com/39289368/82256156-b2666880-990a-11ea-99e0-05d52a971e59.png)

**Comment by NiceneNerd** [comment]
Fixed for beta by using system 7z.
