### ISSUE TITLE
Cemu flatpak issues

### ISSUE THREAD

**Issue by halfmexican** [NiceneNerd/BCML#521]
I'm trying to get this set up working with CEMU installed as a flatpak, but nothing works.

I couldn't set a cemu install directory as there is no exe and the flatpak binary didn't work

I tried setting the export path to .local/share/cemu and that didn't work nor did making a path within the flatpak installation directoy. 

How would I go about getting this to work with CEMU installed as a flatpak

**Comment by GingerAvalanche** [comment]
Depends entirely on where the flatpak executable reads the graphic packs from. That's something you should look into with the flatpak repository/wiki/whatever. Bcml is no longer supported and the flatpak cemu build was only released 2 days ago.

Whatever it is, you'd set the export path to `[flatpak graphic pack folder]/BreathOfTheWild_BCML` and bcml will put the files there. Might also need to make your own rules.txt file and set the option to `Disable links for master mod` if bcml doesn't put its own rules.txt there.

**Comment by halfmexican** [comment]
Thank you! I got it working!
