### ISSUE TITLE
gamebanana tab not there in bcml

### ISSUE THREAD

**Issue by RedGlitch95** [NiceneNerd/BCML#524]
ive installed bcml using pip install bcml but when i open bcml gamebanana is not there just mods, dev log, and settings

**Comment by ArchLeaders** [comment]
It was removed because gamebanana's API is garbage (or at the very least, a nightmare to use)

**Comment by RedGlitch95** [comment]
ok thank you that clears everthing up i understand now

**Comment by NiceneNerd** [comment]
Also BTW this was removed like a year ago
