### ISSUE TITLE
Want To Install On Mac..

### ISSUE THREAD

**Issue by SpaghettiSMM2** [NiceneNerd/BCML#526]
I Dont Have A Windows Computer... I Have Wine, If that Helps... Do I Need An Emulator? Or Is This Just Not Possible... Any Way To Get This??

**Comment by GingerAvalanche** [comment]
Mac can use the unix version of bcml, but there is no 7zip for mac, which is necessary for archive extraction. You would have to use linux or windows.

**Comment by HGStone** [comment]
I would suggest looking into UKMM instead, which is a bcml rewrite (still on beta test) but it does support MAC

**Comment by SpaghettiSMM2** [comment]
@HGStone I'll Try That :)

**Comment by SpaghettiSMM2** [comment]
Unlike BCML, building from source is easy.

Requirements:

Recent nightly Rust toolchain (MSRV 1.60)
A compiler that supports C++17 ()
Modern CMake (3.12+)
Nothing else special is required. Generate a release build by running cargo build --release in the **root repo folder**. It may take a while.


What Is The "root repo folder"?

And Sry I Am Very New To Programming ( And Just Computer Stuff :l )

**Comment by SpaghettiSMM2** [comment]
Ok Found It But WHAT IS THIS 

**“ukmm” can’t be opened because Sandbox is not allowed to open documents in Terminal.**

**Comment by HGStone** [comment]
https://github.com/NiceneNerd/ukmm/releases
