### ISSUE TITLE
Buggy profile switcher? Also, what is its intended behavior?

### ISSUE THREAD

**Issue by SgtSweetieBelle** [NiceneNerd/BCML#527]
I have two profiles set up: a Linkle profile and a Zelda's Ballad profile. But when I switch between the two, it very often messes with my load order, duplicates some mods, deletes others, and doesn't properly enable/disable the Linkle or Zelda mods.

Because of these bugs, I still haven't figured out what it _should_ be changing, and whether it's the right tool for my use-case of switching the main character around. I couldn't find anything about it in the readme or wiki. Is it meant to affect load order? Active/inactive mods? Installed/uninstalled mods? etc.

**Comment by GingerAvalanche** [comment]
Each profile has its own set of mods. This means mods, load order, whether they are active/inactive, their logs, their merged changes, everything about them. When you change profiles, all that *should* happen is that bcml looks at the chosen profile's folder and then links those files to the merge folder ("internal link") and then links/copies the merge folder to the destination, based on your settings ("external link"). If something else is happening, then that's weird.

UKMM is replacing bcml, and we saw no reason to keep updating bcml while another tool is out there that does all the same things, but better, so if this becomes a persistent problem, I recommend switching.
