### ISSUE TITLE
3.0 error

### ISSUE THREAD

**Issue by MisterTwelve** [NiceneNerd/BCML#53]
I get this error message when trying to start the beta release of BCML.
An error has occurred in the script on this page.
Line: 23
Char: 3
Error: Object doesn't support property or method "assign"
![Screenshot_32](https://user-images.githubusercontent.com/49352012/82771960-4cdf1400-9e03-11ea-8a4c-5992cd378746.png)

**Comment by NiceneNerd** [comment]
What OS are you on?

**Comment by MisterTwelve** [comment]
Windows 7 64 bit.

**Comment by NiceneNerd** [comment]
Windows 7 uses an IE11 based default renderer, which is far too out of date to work. You'll need to try installing cefpython3. If you installed BCML using pip, `pip install cefpython3` should work. If you're using the Windows installer, it will be slightly more complicated.

Either way, after that, you'll also need to edit `%LOCALAPPDATA\bcml\settings.json` and change `use_cef` to `true`.

**Comment by MisterTwelve** [comment]
I did use the Windows installer since I could not figure out how to get the 3.0 beta using pip.

Also unrelated to the issue, but when I do try to use the 2.8 release it gives me the no rules.txt found error on every mod I attempt to install, whether they are old .zip mods or new .bnp mods.

**Comment by NiceneNerd** [comment]
For the Windows installer, you'll need to open the Command Prompt or PowerShell to the folder where BCML is installed, and then run `Python\python.exe -m pip install cefpython3`

**Comment by MisterTwelve** [comment]
Done, so far so good. Thanks.
