### ISSUE TITLE
Cannot Create Start Menu/Desktop shortcuts | Empty Error Details

### ISSUE THREAD

**Issue by IpGa13** [NiceneNerd/BCML#530]
Just what the title says. whenever i click on any of those two fields, I get prompted with an Oops dialog box and empty error details

**Comment by GingerAvalanche** [comment]
Open the start menu, type `bcml`, right click->open file location, right click on the bcml exe and make a shortcut out of it.

This is a long-standing error and has been "fixed" multiple times, but keeps breaking. bcml is no longer being supported, so it won't be fixed.
