### ISSUE TITLE
Crash on startup 

### ISSUE THREAD

**Issue by MeowzerBowzer** [NiceneNerd/BCML#54]
I get this when I try to open the latest version of bcml (one release prior to this works(also
c++ and net installed))

![Untitled](https://user-images.githubusercontent.com/55961956/82883997-73a46400-9f43-11ea-9c80-df2adaa7a661.png)

**Comment by NiceneNerd** [comment]
Hmm, I haven't the slightest clue what that is, where it comes from, how to reproduce it, or how to diagnose it. Can you replicate it on any other systems?

**Comment by NiceneNerd** [comment]
According to Google this usually indicates something is wrong with your .NET Framework installation, and as such is not a problem with BCML.
