### ISSUE TITLE
[installer] do not request UAC elevation unless necessary

### ISSUE THREAD

**Issue by AeliusSaionji** [NiceneNerd/BCML#56]
Hey- older versions of this installer behaved better, but recently it asks for UAC elevation.

Please postpone the elevation request until the page where the user is asked where they want to install bcml: and do not elevate if "install just for me" is selected.

This is a best practice that should generally be adhered to, but if you need further motivation, then note that "just for me" is broken in a multi-user context where the current user is not an administrator.

Thank you!

**Comment by NiceneNerd** [comment]
This is very bizarre, as I've made no changes to the installer. I certainly didn't choose this; if I had my way I would only permit user installation. I'm not sure where this new behavior comes from and will have to look into it.

**Comment by AeliusSaionji** [comment]
I must be misremembering, or previously used zip releases.

It looks like the default template for pynsist is responsible for the ill advised setup. Luckily you can alter the template as noted here https://pynsist.readthedocs.io/en/latest/cfgfile.html#build-section

This is relevant line in the template https://github.com/takluyver/pynsist/blob/master/nsist/pyapp.nsi#L20

It seems to be using this plugin: https://nsis.sourceforge.io/Docs/MultiUser/Readme.html

If you're OK with expressly forbidding system-level installs, then you might only need set that to `Standard` instead of `Highest` and call it a day.

**Comment by NiceneNerd** [comment]
I don't think you're misremembering; I'm fairly sure several people, myself include, were about to install without admin before. This seems to have started the same time I got the GitHub workflow for building the installer set up, so I'm trying to figure out if there's a difference between doing itself myself on Windows and the automated build happening on GitHub servers on Linux.

**Comment by NiceneNerd** [comment]
Fixed in v1.0.0b16

**Comment by AeliusSaionji** [comment]
Thank you! ❤️ 

Sorry if I came across defensive. Often I find devs respond "wontfix because this is how everyone does it for Windows" 😞
