### ISSUE TITLE
Installation problem v3.0.0b15

### ISSUE THREAD

**Issue by MoritzB112** [NiceneNerd/BCML#57]
Hi, I have a problen installing the version 3.0.0b15, i tryed it using the windows installer and the command python setup.py install downloading the sorce coode from here and it dosnt launch. The only way to make it work is using pip install bcml but this installs me the version 2.8.0 and the mod witch I want to install requires a newer version. If any information about hardware is needed just ask me.

**Comment by NiceneNerd** [comment]
To upgrade to the beta with pip, you have to include the `--pre` flag for prerelease.

As for why it's not launching, did you install the VC++ redistributable?

**Comment by MoritzB112** [comment]
Hi thanks for the fast reply!
thanks for the tip with --pre but dispite of this it dosnt launch and yes I have installed VC++ redistributable.

**Comment by NiceneNerd** [comment]
What do you get if you run `python -m bcml`?

**Comment by MoritzB112** [comment]
Unbehandelte Ausnahme: Python.Runtime.PythonException: Exception : Der Remoteprozeduraufruf ist fehlgeschlagen. (Ausnahme von HRESULT: 0x800706BE)
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Microsoft.Toolkit.Win32.UI.Controls.Interop.WinRT.WebViewControlProcess.<CreateWebViewControlHostAsync>d__16.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Microsoft.Toolkit.Forms.UI.Controls.WebViewControlProcessExtensions.CreateWebViewControlHost(WebViewControlProcess process, IntPtr hostWindowHandle, Rectangle bounds)
   bei Microsoft.Toolkit.Forms.UI.Controls.WebView.Initialize()
   bei Microsoft.Toolkit.Forms.UI.Controls.WebView.System.ComponentModel.ISupportInitialize.EndInit()
   bei Python.Runtime.Dispatcher.Dispatch(ArrayList args)
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bei System.Threading.ThreadHelper.ThreadStart()

this apears and nothing happons.

**Comment by NiceneNerd** [comment]
Are you running BCML as admin?

**Comment by MoritzB112** [comment]
Yes tryied to launch it via cmd opening it as admin and also tryied to open the exe al admin both witout success but the strange thing is that the version 2.8.0 works without any problen whe I install it via pip

**Comment by DrBeePhD** [comment]
I'm having the same problem. BCML 3 still does not launch on my PC. I've tried reinstalling multiple times to no effect.
CEMU version: 1.19.2
Region: USA
Language: US English

**Comment by NiceneNerd** [comment]
@MoritzB112 The problem *is* running it as admin. That doesn't work with the default EdgeHTML renderer

**Comment by NiceneNerd** [comment]
@DrBeePhD Do you run it as admin, and did you install the VC++ redistributable?

**Comment by DrBeePhD** [comment]
> @DrBeePhD Do you run it as admin, and did you install the VC++ redistributable?

Yes. What is that you say about EdgeHTML? I downloaded the file from Chromium Edge. Is that the issue?

**Comment by MoritzB112** [comment]
I have done it both ways as far as I know, is there any special way to open cmd not as admin?

**Comment by NiceneNerd** [comment]
@DrBeePhD BCML uses a webview to render the UI, and it can run off EdgeHTML or Chromium Embedded Framework. It uses EdgeHTML by default, but you can't open an EdgeHTML webview as admin, so BCML won't open as admin with the default settings.

**Comment by NiceneNerd** [comment]
@MoritzB112 You shouldn't have to do anything special. Is there a chance you can get an English version of the error message so I can make sure of the problem?

**Comment by DrBeePhD** [comment]
> @DrBeePhD BCML uses a webview to render the UI, and it can run off EdgeHTML or Chromium Embedded Framework. It uses EdgeHTML by default, but you can't open an EdgeHTML webview as admin, so BCML won't open as admin with the default settings.

Ok, so how do I go about changing the settings? And why did it open as admin for the previous version?

**Comment by MoritzB112** [comment]
Ill try it but for this i would have to change the system language I think, so it could take a while

**Comment by NiceneNerd** [comment]
@DrBeePhD Try not running it as admin first.

**Comment by DrBeePhD** [comment]
> @DrBeePhD Try not running it as admin first.

Ah that seem to have done the trick. Guess the simplest thing was the solution! Now, I don't know if this is an issue with the program, but when I try to install a mod I get this error:

Traceback (most recent call last):
  File "C:\Program Files\BCML\pkgs\bcml\__main__.py", line 257, in install_mod
    merger.perform_merge()
  File "C:\Program Files\BCML\pkgs\bcml\util.py", line 425, in timed_function
    res = func(*args, **kwargs)
  File "C:\Program Files\BCML\pkgs\bcml\mergers\actors.py", line 140, in perform_merge
    actorinfo = get_stock_actorinfo()
  File "C:\Program Files\BCML\pkgs\bcml\mergers\actors.py", line 23, in get_stock_actorinfo
    actorinfo = util.get_game_file("Actor/ActorInfo.product.sbyml")
  File "C:\Program Files\BCML\pkgs\bcml\util.py", line 755, in get_game_file
    raise FileNotFoundError(f"File {str(path)} was not found in game dump.")
FileNotFoundError: File Actor\ActorInfo.product.sbyml was not found in game dump.

I'm using an emulated version of BotW from USBHelper.

**Comment by DrBeePhD** [comment]
Nevermind I figured that out! Now I'm getting this:

Traceback (most recent call last):
  File "C:\Program Files\BCML\pkgs\bcml\__main__.py", line 257, in install_mod
    merger.perform_merge()
  File "C:\Program Files\BCML\pkgs\bcml\util.py", line 425, in timed_function
    res = func(*args, **kwargs)
  File "C:\Program Files\BCML\pkgs\bcml\mergers\actors.py", line 140, in perform_merge
    actorinfo = get_stock_actorinfo()
  File "C:\Program Files\BCML\pkgs\bcml\mergers\actors.py", line 23, in get_stock_actorinfo
    actorinfo = util.get_game_file("Actor/ActorInfo.product.sbyml")
  File "C:\Program Files\BCML\pkgs\bcml\util.py", line 755, in get_game_file
    raise FileNotFoundError(f"File {str(path)} was not found in game dump.")
FileNotFoundError: File Actor\ActorInfo.product.sbyml was not found in game dump.

**Comment by NiceneNerd** [comment]
@DrBeePhD In the future, if you want to be able to run BCML as admin, go into the BCML settings and check "Use CEF renderer."

As for that error, it generally indicates one of your game folders is set incorrectly, or your update data is not installed.

**Comment by MoritzB112** [comment]
Unhandled Exception: Python.Runtime.PythonException: Exception : The remote procedure call failed. (Exception from HRESULT: 0x800706BE)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Toolkit.Win32.UI.Controls.Interop.WinRT.WebViewControlProcess.<CreateWebViewControlHostAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Toolkit.Forms.UI.Controls.WebViewControlProcessExtensions.CreateWebViewControlHost(WebViewControlProcess process, IntPtr hostWindowHandle, Rectangle bounds)
   at Microsoft.Toolkit.Forms.UI.Controls.WebView.Initialize()
   at Microsoft.Toolkit.Forms.UI.Controls.WebView.System.ComponentModel.ISupportInitialize.EndInit()
   at Python.Runtime.Dispatcher.Dispatch(ArrayList args)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

here is thes same error message but in english

**Comment by NiceneNerd** [comment]
@MoritzB112 I'm almost positive that's the error that comes from running BCML as admin with the default renderer. But I don't know why you'd be having a hard time running it not as admin.

**Comment by MoritzB112** [comment]
I will explain step by step how I tryed to run it, lets see if you find something wron.

Im the ony user at this pc, so I logg in and the in the windows search I tipe cmd and open the command prompt the I tipe bcml and run then it loads for a moment and nothing more happons.
Or what I also tryed, after llogging in going to the  installation directory of python and enter scrips then execute the bcml.exe with normal ddopple click on it.
As far as i know this things shouldnt run it as admin or am I wrong?

**Comment by NiceneNerd** [comment]
Is there a chance that your PC has only the proper Administrator account?

**Comment by MoritzB112** [comment]
In my user directoy on the c drive I have defaultuser0, defaultuser1, Moritz(my account) and Public. And I know that my account is an Administrator

**Comment by MoritzB112** [comment]
Hi I tried the newest version with euning bcml-install-cef but I get the same error as without.

**Comment by NiceneNerd** [comment]
Did `bcml-install-cef` report any errors?

**Comment by NiceneNerd** [comment]
@MoritzB112 > Hi I tried the newest version with euning bcml-install-cef but I get the same error as without.

Did `bcml-install-cef` report any errors?

**Comment by MoritzB112** [comment]
Sorry for the late response, nop when I executed it it worked fine and without errors and when I rewrite it, it says "CEF is already installed".

**Comment by NiceneNerd** [comment]
@MoritzB112 Try today's new release.

**Comment by MoritzB112** [comment]
Now it works thanks a lot!
