### ISSUE TITLE
BCML doesn't register the first click and requires doubleclicking every button?

### ISSUE THREAD

**Issue by BrokenGale** [NiceneNerd/BCML#58]
OS: Pop_OS 20.04

I am encountering a weird bug where no button in the BCML ui reacts unless I double click the button. Is this intended or is it a distro specific bug?

**Comment by NiceneNerd** [comment]
I've heard of one other person who had this problem and have not been able to replicate it myself. If I recall correctly, they had it while using the default GTK webview for the UI. Try installing `pyqtwebengine` through pip to switch to the Qt webview and see if it works better.

**Comment by BrokenGale** [comment]
That solved it, thank you very much.

**Comment by laurinneff** [comment]
In my case, installing `pyqtwebengine` through pip results in the following error when starting bcml:

```
QGLXContext: Failed to create dummy context
WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile) 
fish: “bcml” terminated by signal SIGABRT (Abbruch)
```

I can get bcml to start by installing `python3-pyqt5` and `python3-pyqt5.qtwebkit` through APT, but then I have to double click everything

I'm also on Pop!_OS 20.04

**Comment by NiceneNerd** [comment]
All of the searching I can do for that error points to graphics driver problems?

**Comment by laurinneff** [comment]
Ok, since you're suspecting graphics driver problems, here's my laptop's GPU setup: Intel + Nvidia GPU (GeForce MX250), Proprietary Nvidia driver version 455, Intel GPU not used for rendering. I could try switching to hybrid graphics and running BCML on the Intel GPU, maybe that would help

**Comment by NiceneNerd** [comment]
Sure, give it a shot.

**Comment by laurinneff** [comment]
Looks like that was the issue. Now it runs with `pyqtwebengine` from pip, and I don't need to double click. Now I just need to wait ~3 hours until my dump is done, then I can finally try BCML on my switch

**Comment by NiceneNerd** [comment]
Sounds good, glad it worked out.
