### ISSUE TITLE
what's wrong？

### ISSUE THREAD

**Issue by kklzz1982** [NiceneNerd/BCML#62]
Traceback (most recent call last):
  File "D:\\Program Files (x86)\\BCML\\pkgs\\bcml\\_api.py", line 42, in status_run
    func(*args, **kwargs)
  File "D:\\Program Files (x86)\\BCML\\pkgs\\bcml\\install.py", line 269, in do_and_refresh
    refresh_master_export()
  File "D:\\Program Files (x86)\\BCML\\pkgs\\bcml\\install.py", line 284, in refresh_master_export
    for line in setfile:
  File "D:\\obj\\windows-release\\37amd64_Release\\msi_python\\zip_amd64\\codecs.py", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xca in position 2266: invalid continuation byte

**Comment by NiceneNerd** [comment]
Something is wrong with reading Cemu's `settings.xml` file. Can you post it here?

**Comment by kklzz1982** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<content>
    <logflag>0</logflag>
    <advanced_ppc_logging>false</advanced_ppc_logging>
    <mlc_path>H:\BOTW\mlc01\</mlc_path>
    <language>44</language>
    <use_discord_presence>true</use_discord_presence>
    <fullscreen_menubar>true</fullscreen_menubar>
    <check_update>false</check_update>
    <save_screenshot>true</save_screenshot>
    <vk_warning>false</vk_warning>
    <gp_download>true</gp_download>
    <fullscreen>true</fullscreen>
    <cpu_mode>1</cpu_mode>
    <console_region>255</console_region>
    <console_language>1</console_language>
    <window_position>
        <x>-1</x>
        <y>-1</y>
    </window_position>
    <window_size>
        <x>-1</x>
        <y>-1</y>
    </window_size>
    <open_pad>false</open_pad>
    <pad_position>
        <x>-1</x>
        <y>-1</y>
    </pad_position>
    <pad_size>
        <x>-1</x>
        <y>-1</y>
    </pad_size>
    <GameList>
        <style>0</style>
        <order>{0, 1, 2, 3, 4, 5, 6, 7}</order>
        <name_width>500</name_width>
        <version_width>119</version_width>
        <dlc_width>121</dlc_width>
        <game_time_width>140</game_time_width>
        <game_started_width>160</game_started_width>
    </GameList>
    <RecentLaunchFiles>
        <Entry>.\BotW\code\U-King.rpx</Entry>
        <Entry>.\BOTW\BotW\code\U-King.rpx</Entry>
    </RecentLaunchFiles>
    <RecentNFCFiles>
        <Entry>H:\BOTW\amiibo\20蹇冨績鐨勬灄鍏嬬嫾.bin</Entry>
    </RecentNFCFiles>
    <GamePaths>
        <Entry>H:\BOTW</Entry>
    </GamePaths>
    <GameCache>
        <Entry>
            <title_id>1407375153861376</title_id>
            <name>The Legend of Zelda - Breath of the Wild</name>
            <custom_name>銆婂灏旇揪浼犺锛氭椃閲庝箣鎭€?/custom_name>
            <region>1</region>
            <version>208</version>
            <dlc_version>80</dlc_version>
            <path>H:\BOTW\BotW\code\U-King.rpx</path>
            <time_played>3050</time_played>
            <last_played>1593476907</last_played>
            <favorite>false</favorite>
        </Entry>
    </GameCache>
    <GraphicPack>
        <Entry filename="graphicPacks\BreathOfTheWild_FPS++\Limit FPS\rules.txt">
            <Preset>
                <preset>72帧 (适配144赫兹显示器)</preset>
            </Preset>
        </Entry>
        <Entry filename="graphicPacks\BreathOfTheWild_Cheats_InfStamina\rules.txt"/>
        <Entry filename="graphicPacks\BreathOfTheWild_CelShadingRemoval\Botw_CelShadingRemoval\rules.txt">
            <Preset>
                <preset>禁用动画渲染</preset>
            </Preset>
        </Entry>
        <Entry filename="graphicPacks\BreathOfTheWild_Shadows\rules.txt">
            <Preset>
                <preset>终极 (300%)</preset>
            </Preset>
        </Entry>
        <Entry filename="graphicPacks\BreathOfTheWild_Cheats_InfMotorcycle\rules.txt"/>
        <Entry filename="graphicPacks\BreathOfTheWild_!Brighter_Lights\SC Logo\rules.txt"/>
        <Entry filename="graphicPacks\BreathOfTheWild_UnobtainableChestsFix\rules.txt"/>
        <Entry filename="graphicPacks\BreathOfTheWild_Linkle\PinkWeaponsPack\rules.txt"/>
        <Entry filename="graphicPacks\BreathOfTheWild_!Intel_Shadows\rules.txt"/>
        <Entry filename="graphicPacks\BreathOfTheWild_AntiAliasing\rules.txt">
            <Preset>
                <preset>备用FXAA (通过NVIDIA实现)</preset>
            </Preset>
        </Entry>
        <Entry filename="graphicPacks\BreathOfTheWild_!NoAO\rules.txt"/>
        <Entry filename="graphicPacks\BreathOfTheWild_DistantFogRemoval\Botw_DistantFog\rules.txt">
            <Preset>
                <preset>0%雾霾 8倍提亮</preset>
            </Preset>
        </Entry>
        <Entry filename="graphicPacks\BreathOfTheWild_CelShadingRemoval\Botw_AmiiboMode\rules.txt">
            <Preset>
                <preset>45%塑料质感</preset>
            </Preset>
        </Entry>
        <Entry filename="graphicPacks\BreathOfTheWild_Cheats_InfMipha\rules.txt"/>
        <Entry filename="graphicPacks\BreathOfTheWild_Cheats_InfHearts\rules.txt"/>
        <Entry filename="graphicPacks\BreathOfTheWild_!NoDoF\rules.txt"/>
        <Entry filename="graphicPacks\BreathOfTheWild_Cheats_InfDaruk\rules.txt"/>
        <Entry filename="graphicPacks\BreathOfTheWild_BetterUniqueHorses\rules.txt"/>
        <Entry filename="graphicPacks\BreathOfTheWild_Linkle\Linkle Mod\rules.txt"/>
        <Entry filename="graphicPacks\BreathOfTheWild_CelShadingRemoval\Botw_MenuWorkaround\rules.txt">
            <Preset>
                <preset>开始菜单解决方案</preset>
            </Preset>
        </Entry>
        <Entry filename="graphicPacks\BreathOfTheWild_CelShadingRemoval\Botw_ShadowFix_SkalFate\rules.txt">
            <Preset>
                <preset>模式 1 - 8倍渲染(最佳模式)</preset>
            </Preset>
        </Entry>
        <Entry filename="graphicPacks\BreathOfTheWild_ChangeAncientGlowColor\Ancient_Armor\rules.txt">
            <Preset>
                <preset>粉红色 (在rules.txt里修改)</preset>
            </Preset>
        </Entry>
        <Entry filename="graphicPacks\BreathOfTheWild_ChangeAncientGlowColor\Ancient_Weapons\rules.txt">
            <Preset>
                <preset>邪恶红</preset>
            </Preset>
        </Entry>
        <Entry filename="graphicPacks\BreathOfTheWild_Cheats_FasterArrowDraw\rules.txt"/>
        <Entry filename="graphicPacks\BreathOfTheWild_DistantFogRemoval\Botw_WorldFogFields\rules.txt">
            <Preset>
                <preset>禁用雾霾区域</preset>
            </Preset>
        </Entry>
        <Entry filename="graphicPacks\BreathOfTheWild_Cheats_InfAmiibo\rules.txt"/>
        <Entry filename="graphicPacks\BreathOfTheWild_Cheats_Invincible_Wolf_Link\rules.txt"/>
        <Entry filename="graphicPacks\BreathOfTheWild_Cheats_InfArrows\rules.txt"/>
        <Entry filename="graphicPacks\super_resistant_link\rules.txt"/>
        <Entry filename="graphicPacks\BreathOfTheWild_Cheats_InfRevali\rules.txt"/>
        <Entry filename="graphicPacks\BreathOfTheWild_Cheats_InfUrbosa\rules.txt"/>
        <Entry filename="graphicPacks\BreathOfTheWild_Cheats_InfWeapons\rules.txt"/>
        <Entry filename="graphicPacks\BreathOfTheWild_Cheats_MotorcycleAnywhere\rules.txt"/>
        <Entry filename="graphicPacks\BreathOfTheWild_Clarity\rules.txt">
            <Preset>
                <preset>CellHunter的预设</preset>
            </Preset>
        </Entry>
        <Entry filename="graphicPacks\BreathOfTheWild_DayLength\rules.txt">
            <Preset>
                <preset>2小时</preset>
            </Preset>
        </Entry>
        <Entry filename="graphicPacks\BreathOfTheWild_DistantFogRemoval\Botw_HyruleCastleAura\rules.txt">
            <Preset>
                <preset>禁用加农瘴气雾霾</preset>
            </Preset>
        </Entry>
        <Entry filename="graphicPacks\BreathOfTheWild_DistantFogRemoval\Botw_HyruleCastleBaseFog\rules.txt">
            <Preset>
                <preset>禁用城堡地牢雾霾</preset>
            </Preset>
        </Entry>
        <Entry filename="graphicPacks\BreathOfTheWild_GrassWorkaround\rules.txt"/>
        <Entry filename="graphicPacks\BreathOfTheWild_DivineLaserBeamCustomizer\rules.txt">
            <Preset>
                <preset>七彩色</preset>
            </Preset>
        </Entry>
        <Entry filename="graphicPacks\BreathOfTheWild_FPS++\Dynamic Gamespeed\rules.txt">
            <Preset>
                <preset>平均32帧</preset>
            </Preset>
        </Entry>
        <Entry filename="graphicPacks\BreathOfTheWild_FPS++\Fence Method\rules.txt">
            <Preset>
                <preset>性能锁帧</preset>
            </Preset>
        </Entry>
        <Entry filename="graphicPacks\BreathOfTheWild_GlowLightsColors\rules.txt"/>
        <Entry filename="graphicPacks\BreathOfTheWild_Linkle\LinkleMod_Armor_Icons\rules.txt"/>
        <Entry filename="graphicPacks\BreathOfTheWild_Linkle\LinkleNMod_maiden\rules.txt"/>
        <Entry filename="graphicPacks\BreathOfTheWild_Resolution\rules.txt">
            <Preset>
                <preset>5120x2880 (16:9)</preset>
            </Preset>
        </Entry>
        <Entry filename="graphicPacks\BreathOfTheWild_LODBias\rules.txt">
            <Preset>
                <preset>极高的纹理细节 (-8)</preset>
            </Preset>
        </Entry>
        <Entry filename="graphicPacks\BreathOfTheWild_NpcNude\rules.txt"/>
        <Entry filename="graphicPacks\BreathOfTheWild_ReflExtra\rules.txt"/>
        <Entry filename="graphicPacks\BreathOfTheWild_ReshadeCompatibility\rules.txt"/>
        <Entry filename="graphicPacks\BreathOfTheWild_Weather\rules.txt">
            <Preset>
                <preset>雨天</preset>
            </Preset>
        </Entry>
    </GraphicPack>
    <Graphic>
        <api>1</api>
        <device>3610a6a606fe2ab42493e3e4071a4aef</device>
        <VSync>2</VSync>
        <GX2DrawdoneSync>true</GX2DrawdoneSync>
        <PrecompiledShaders>0</PrecompiledShaders>
        <vertex_cache_accuary>0</vertex_cache_accuary>
        <UpscaleFilter>1</UpscaleFilter>
        <DownscaleFilter>0</DownscaleFilter>
        <FullscreenScaling>0</FullscreenScaling>
        <Overlay>
            <Position>3</Position>
            <TextColor>4278222848</TextColor>
            <TextScale>300</TextScale>
            <FPS>true</FPS>
            <DrawCalls>false</DrawCalls>
            <CPUUsage>false</CPUUsage>
            <CPUPerCoreUsage>false</CPUPerCoreUsage>
            <RAMUsage>false</RAMUsage>
            <VRAMUsage>false</VRAMUsage>
            <Debug>false</Debug>
        </Overlay>
        <Notification>
            <Position>1</Position>
            <TextColor>4278222848</TextColor>
            <TextScale>300</TextScale>
            <ControllerProfiles>true</ControllerProfiles>
            <ControllerBattery>false</ControllerBattery>
            <ShaderCompiling>true</ShaderCompiling>
            <FriendService>true</FriendService>
        </Notification>
    </Graphic>
    <Audio>
        <api>0</api>
        <delay>2</delay>
        <TVChannels>1</TVChannels>
        <PadChannels>1</PadChannels>
        <TVVolume>60</TVVolume>
        <PadVolume>61</PadVolume>
        <TVDevice>E1788E62-C7A3-4B87-BFF8-1F953A836846</TVDevice>
        <PadDevice>E1788E62-C7A3-4B87-BFF8-1F953A836846</PadDevice>
    </Audio>
    <Account>
        <永久Id>2147483649</永久Id>
        <OnlineEnabled>false</OnlineEnabled>
    </Account>
    <Debug>
        <CrashDump>0</CrashDump>
        <AsyncCompile>false</AsyncCompile>
    </Debug>
    <Input>
        <DSUC host="127.0.0.1" port="26760"/>
    </Input>
</content>

**Comment by NiceneNerd** [comment]
What language does your PC use?

**Comment by kklzz1982** [comment]
Simplified Chinese

**Comment by NiceneNerd** [comment]
Hm, I haven't been able to reproduce this. Try uploading the file itself instead of pasting it.

**Comment by kklzz1982** [comment]
[settings.zip](https://github.com/NiceneNerd/BCML/files/4915828/settings.zip)

**Comment by NiceneNerd** [comment]
I can't even open this file in standard text editors; it seems to have a broken encoding. Delete it, redo your settings in Cemu, and then see if you still have the problem.

**Comment by kklzz1982** [comment]
change your code to ansi

**Comment by NiceneNerd** [comment]
Do you mean you did that, or I should do that, to BCML, or to your settings, or what?

**Comment by kklzz1982** [comment]
my settings，chinese needs to change to ansi encoded
