### ISSUE TITLE
BCML Mod list neverloads & Errors when doing some actions.

### ISSUE THREAD

**Issue by LastAi** [NiceneNerd/BCML#63]
When starting BCML fresh and clean mod list is empty and everything seems ok.
However when if I load mods from file, it completes but the mod list show the loading wheel and never loads.
If i hit a one click BCML from banana it does the same thing, completes but never show up.
I have tried running in debug but now error in the console.

I run the application in Admin.

I deleted Cemu's settings and let Cemu recreate it. no change.
CEMU 1.19.3

I am running my PC in English(Display and default app language)
Japaness is also installed.
Japanese as the 'Language for non-Unicode Programs'
I haven't tested turning this off yet.

I dont know if any of this is helpful at all but im going to list my specs:

Windows 10 pro
Intel Xeon CPU E50268W v2 @3.40GHz (2 processors)
256 GB ram

Display Language- English
App Language- English
Non-Unicode Language- Japanese

CEMU 1.19.3
BCML 3.0.0 beta 23

Errors:
When hitting update- 
`Traceback (most recent call last):
  File "F:\BCML\pkgs\bcml\_api.py", line 42, in status_run
    func(*args, **kwargs)
  File "F:\BCML\pkgs\bcml\_api.py", line 574, in update_bcml
    raise RuntimeError(result.stderr)
RuntimeError: ERROR: Could not install packages due to an EnvironmentError: [WinError 5] Access is denied: 'f:\\bcml\\pkgs\\clr.pyd'
Consider using the `--user` option or check the permissions.`

But other than that. The app seems to act normally, i just never loads the mod list.
Ive tried restarting the mod list show the loading wheel but never loads.

**Comment by NiceneNerd** [comment]
It's a known bug in v3.0.0b23 that's fixed here: 54af7de8db0ad1213b4870fdf621433f3699aa95

New release coming tonight or tomorrow, in the meantime I'd suggest rolling back to b22.

**Comment by LastAi** [comment]
Thank you!
Ill give it a shot.

**Comment by SirCanucklehead** [comment]
> The mod list thing is a known Windows-only bug in v3.0.0b23 that's fixed here: [54af7de](https://github.com/NiceneNerd/BCML/commit/54af7de8db0ad1213b4870fdf621433f3699aa95)
> 
> New release coming tonight or tomorrow, in the meantime I'd suggest rolling back to b22.
> 
> As for the updater error, I think I've suddenly realized what causes it, so I'll look into a fix.

Hi, new to using BCML and am encountering this error. Where/how would I apply the fix linked in this comment?
Thanks in advance.

**Comment by NiceneNerd** [comment]
It's fixed in beta 24, you can just update.

**Comment by SirCanucklehead** [comment]
> It's fixed in beta 24, you can just update.

Thanks, good to know. 

Turns out though, the next time I booted my game up, the mod that wouldn't show up was installed and working fine, didn't even do anything 
¯\_(ツ)_/¯

**Comment by QuartzNeko** [comment]
i have a problem im getting "RuntimeError("BCML could not load its settings file") from err
RuntimeError: BCML could not load its settings file" it will not boot at all
