### ISSUE TITLE
Mods list never loads and unable to install mods

### ISSUE THREAD

**Issue by Mihli** [NiceneNerd/BCML#67]
5.8.1-arch1-1
installed through pip.
running BCML gives the following output
```
QSettings::value: Empty key passed
QSettings::value: Empty key passed
Icon theme "gnome" not found.
Icon theme "ubuntu-mono-dark" not found.
Icon theme "Mint-X" not found.
Icon theme "elementary" not found.
Icon theme "gnome" not found.
Icon theme "gnome" not found.
Icon theme "ubuntu-mono-dark" not found.
Icon theme "Mint-X" not found.
Icon theme "elementary" not found.
Icon theme "gnome" not found.
[pywebview] Error occurred while evaluating function get_mods
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/webviewb/util.py", line 175, in js_bridge_call
    func_params = param if not param else json.loads(param)
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not dict
```
the window will open but just shows a spinning circle in the mod list, and also has the issue described in #58  .
attempting to install anything just runs forever, installing pyqtwebengine makes no difference in UI or installation.

**Comment by NiceneNerd** [comment]
Did you install pyqtwebengine using pip or your package manager?

**Comment by Mihli** [comment]
through pip

**Comment by NiceneNerd** [comment]
Try the Arch package

**Comment by Mihli** [comment]
QSettings::value: Empty key passed
QSettings::value: Empty key passed
Could not find QtWebEngineProcess
zsh: abort (core dumped)  bcml

**Comment by NiceneNerd** [comment]
Hmm, I don't know how to really investigate or replicate this. Some of the Python package management on Arch I've found troublesome. Maybe see if it works with pyenv?
