### ISSUE TITLE
Pip install broken on Linux

### ISSUE THREAD

**Issue by gameboycjp** [NiceneNerd/BCML#69]
I'm trying to get BCML working on Linux, but I get an error on startup.
`ModuleNotFoundError: No module named 'winreg'`
Am I doing something wrong, or is this the fault of the software?

**Comment by NiceneNerd** [comment]
BCML 2.8 doesn't support Linux. You need to include the `--pre` flag to get the 3.0 rc.

**Comment by gameboycjp** [comment]
Thank you, that worked. I didn't know it installed the 2.8 version.
