### ISSUE TITLE
[Bug] (rc7) Upgrading BNP Saves Results Incorrectly

### ISSUE THREAD

**Issue by SkyNinja** [NiceneNerd/BCML#72]
Version: BCML 3.0rc7
OS: Windows 10 Pro

When attempting to update an old BNP, the resultant file isn't saved to the location selected, but rather is saved to the HOME directory (here, C:\Users\MYNAME\) as a 7z file with the filename being the letter of the drive I attempted to save to.

**Comment by NiceneNerd** [comment]
Ah, one of those dumb glitches that arises from different behavior on Windows and Linux. Easy fix.
