### ISSUE TITLE
Export error (switch version)

### ISSUE THREAD

**Issue by Pokemon1995** [NiceneNerd/BCML#73]
Everything works fine but with every setup i always get this error when i try to export. Did anyone have the same issue or tipps to solve this? I use the new BCML 3.0 r7.

Traceback (most recent call last):
  File "C:\bcml\pkgs\bcml\_api.py", line 43, in status_run
    func(*args, **kwargs)
  File "C:\bcml\pkgs\bcml\_api.py", line 460, in export
    install.export(output)
  File "C:\bcml\pkgs\bcml\install.py", line 740, in export
    check=True,
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\subprocess.py", line 512, in run
subprocess.CalledProcessError: Command '['C:\\bcml\\pkgs\\bcml\\helpers\\7z.exe', 'a', 'D:\\TXOSCard\\exported-mods.zip', 'F:tmp_bcml_export\\*']' returned non-zero exit status 1.

**Comment by NiceneNerd** [comment]
Hmm, does it work if you save to the F: drive?

**Comment by Pokemon1995** [comment]
> Hmm, does it work if you save to the F: drive?

No same message.

**Comment by NiceneNerd** [comment]
Unfortunately, I haven't been able to reproduce this. One thought: can you create folders in the root of `F:` without admin permissions on your system?

**Comment by Pokemon1995** [comment]
Yes i can create folders without admin permission. I also try multiple location for the install but everytime i got the same error.

**Comment by NiceneNerd** [comment]
If you watch the `F:` drive while BCML attempts to export, does the `tmp_bcml_export` folder get created?

**Comment by Pokemon1995** [comment]
Yes it does.
