### ISSUE TITLE
I can't find my main game dump folder

### ISSUE THREAD

**Issue by MrRyno123** [NiceneNerd/BCML#77]
I can't find my main game dump folder. Can anyone help?

**Comment by NiceneNerd** [comment]
Do you have the game working on Cemu?

**Comment by MrRyno123** [comment]
yes

**Comment by NiceneNerd** [comment]
Then you can find your dump folder from you Cemu settings. Between these, the tutorial video, and the in-app help, you have everything you need.

**Comment by MrRyno123** [comment]
I have watched the tutorial but I don't have the folders you have.

**Comment by NiceneNerd** [comment]
That still leaves the Cemu settings and in-app help.
