### ISSUE TITLE
Game Folders

### ISSUE THREAD

**Issue by FateChanger** [NiceneNerd/BCML#79]
I am trying to select folders in order yo begin modding. Despite have all green checkmarks, I am getting a message saying my settings are not valid. I am not running CEMU and have attached a photo of my BoTW dump. Should I re-dump my game files and start over?
![image](https://user-images.githubusercontent.com/72468688/95249468-90905400-07cd-11eb-9a45-a5641f6d1d2c.png)

**Comment by NiceneNerd** [comment]
Where are your update and DLC files?

**Comment by FateChanger** [comment]
This is everything that was dumped. I do not think it was correctly dumped however. I used ddd to connect my laptop and Wii U. I will try and redo the process

**Comment by NiceneNerd** [comment]
Well, it's not really a BCML issue. Once you have the right folders, the in-app help and tooltips and whatnot will suffice.
