### ISSUE TITLE
Unrecoverable error when info.json blank inside of mod directory

### ISSUE THREAD

**Issue by 0xW1sKy** [NiceneNerd/BCML#81]
Computer froze while performing a sort on mods. (pretty sure computer freeze was from unrelated activity)
resulted in a lot of empty `info.json` files.

This creates an unrecoverable error in bcml.

tried looking through the code base to find where it might be leveraged but didn't spend too much time on it. looks like a handful of operations validate the the `info.json` file exists, but does not validate that it is not empty before processing.

2 things I'm thinking here:

1) should validate `info.json` file is not empty before processing.
2) the sort option should not completely empty the info.json file when processing if possible. 

if you can tell me where to look in the codebase, I can tackle these fixes.

**Comment by NiceneNerd** [comment]
It would be easy enough to implement (1), though it would probably never come up as relevant ever again, but nothing can be done about (2), as it already writes the contents of an `info.json` file in a single line of code. If they came up blank, it's at the OS level and there's nothing BCML can do to prevent it.

**Comment by 0xW1sKy** [comment]
The scenario for me affected 20+ mod folders all at once. Wasn’t a one off. I’m assuming somewhere the app isn’t working with these mod folders and info files one at a time.

**Comment by NiceneNerd** [comment]
It does actually do them one at a time; it has to when sorting. But depending on why your computer froze, those writes could all have been queued and failed together.

**Comment by 0xW1sKy** [comment]
That’s plausible. 

Another thought here as well. Would it make sense to remove the dependency of the info.json file? I.e. nice to have but not need to have for  the app?

Would solve this issue as well as potential others. 

Something like if missing or blank: create

**Comment by NiceneNerd** [comment]
It wouldn't make a great deal of sense to do so, as `info.json` is necessary for BCML to identify mods. You could hypothetically generate one if it were missing, but the new one would be missing a bunch of metadata. It would be better to simply show an explicit error message so that the user knows something has gone wrong with that mod and can attempt to fix or reinstall it.

**Comment by 0xW1sKy** [comment]
I understand your position but from a user experience perspective I’d think it would be better to do both. Throw the error, but also generate a file that says something along the lines of “corrupted mod file, please attempt reinstall” in the description included in the info.json. Maybe add a warning tag in the title as well that could highlight the mod in yellow or something in the user interface. 

Reasoning being that the information in that exact file isn’t particularly critical information. And the goal of the installed mod is to have the changes apply to botw more so than have the title, description, image represented cleanly within bcml. 

Also, for the record, I 100% acknowledge this is your app and won’t be upset whatever you decide to do with it. I’m not trying to argue here, just trying to contribute and hopefully help make things better. 🙂
