### ISSUE TITLE
BCML fails to load 

### ISSUE THREAD

**Issue by Lillievela** [NiceneNerd/BCML#83]
Ive been trying to get bcml to run on my laptop, running manjaro, through pip, at first it was working, i had to double click everything, it never fully loaded, i looked into it and saw that i needed something else, pyqtwebwngine,  but after installing that i get a whole new issue
`qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Aborted (core dumped)
`
Now no matter what i do it never begins to load bcml

**Comment by Lillievela** [comment]
I have managed to get it open again, but now it shows py errors in the terminal and is back to the forever loading

**Comment by Lillievela** [comment]
And now im up to another error
`/usr/lib/python3.8/site-packages/PyQt5/Qt/libexec/QtWebEngineProcess: symbol lookup error: /usr/lib/python3.8/site-packages/PyQt5/Qt/libexec/../lib/libQt5WebEngineCore.so.5: undefined symbol: _ZNSt12out_of_rangeC1EPKc, version Qt_5
Trace/breakpoint trap (core dumped)
`

**Comment by NiceneNerd** [comment]
How did you install PyQtWebEngine?

**Comment by NiceneNerd** [comment]
I use Manjaro myself, and it Just Works ™ right now, but it didn't at various points. It also Just Works™ on my Ubuntu machine at work.

**Comment by Lillievela** [comment]
installing from the repos shows the pyqt5 error, installing with pip just has the double click and loading issues. Although im not sure what the issue is directed at with the repo install, whether or not i need something different or not

**Comment by Lillievela** [comment]
Okay so it turns out, i had pyqt5 and pyqt5-sip installed in both pip and the repos, removing them from pip fixes the issue, now i can see about converting some mods and merging them for my wiiu
