### ISSUE TITLE
Update available but not really?

### ISSUE THREAD

**Issue by LNBZero** [NiceneNerd/BCML#88]
Hello,

Since today when I launch BCML I get a message claiming there's an update. When I agree to this it loads very briefly when it would usually download and update. However it nearly instantly continues to the message of needing to restart to finish said update. Again when I agree to this BCML closes rather than restart. So moving onto the debug it gives the following error:

[1204/115653.568:ERROR:request_handler.cpp(109)] [Browser process] OnRenderProcessTerminated()

After trying several times I came here to manually download the new update and... find out the latest release is the version what I have.

I can just decline the update and it'll run without problems but I was wondering what's up and see if anyone else perhaps has this.

Thanks in advance!

**Comment by NiceneNerd** [comment]
Turns out this is a bug in the notifier. I published a quiet beta release for testing purposes, and though the in-app updater only updates to stable releases, the notifier checks for any kind of new release. Will be fixed in the next proper update.

**Comment by LNBZero** [comment]
Hello NiceneNerd,

Thanks for the fast response! Real fast!

No problem then! Thanks for the clarification. Good luck on the fix and thanks for this project in general. =)
