### ISSUE TITLE
BCML not opening after update 

### ISSUE THREAD

**Issue by Sencren** [NiceneNerd/BCML#89]
Hello I installed BCML on windows about 2 weeks ago and it was working great I had the linkle mod and other mods running smooth. however one of the mods didn't work so after the update I was going to disable it, but I am unable to open the app it wont even register the input. 
any idea why its not opening?

**Comment by NiceneNerd** [comment]
There's a problem with the wheel that was uploaded to PyPI; are you using pip or the Windows installer?

**Comment by Sencren** [comment]
windows installer I don't have pip installed. I downloaded BCML from gamebanana.

**Comment by NiceneNerd** [comment]
Reinstall from the new GameBanana download

**Comment by Sencren** [comment]
ok,
will it erase the mods that I have installed?

**Comment by NiceneNerd** [comment]
No

**Comment by floral-qua-floral** [comment]
Getting the same issue - downloaded Windows installer from Gamebanana, it stopped launching after updating today. I used the update prompt that popped up in BCML, but once it got to the "restart" phase it didn't open again and I was no longer able to launch from the Start menu. Downloading the bcml_320.exe installer from Gamebanana as suggested & installing into the same folder seems to have fixed the issue, though.

Seems to me like there's something wrong with the in-app updater 🤷‍♀️

**Comment by NiceneNerd** [comment]
@floral-qua-floral It's not the updater; there's something wrong with the update package that got uploaded to PyPI.
