### ISSUE TITLE
[Question] BCML and Switch

### ISSUE THREAD

**Issue by MonfGeiger** [NiceneNerd/BCML#93]
I'm interested in modding my copy of BoTW for the switch, but my computer setup isnt good enough to run BotW in either cemu or yuzu (it actually did go only as far as that "link, wake up" scene with the golden light but thats it). How would I go about using BCML in switch mode and using the nxdumptool homebrew

I want to be extra sure I dont pear-shape my atmo setup even if I can re-create it if needed

**Comment by NiceneNerd** [comment]
This isn't the kind of thing you use an issue for. How to dump your game is documented in a number of places, and both the in-app help and the tutorial video on YouTube cover what to do on the BCML end.
