### ISSUE TITLE
BCML 3.2.0 In-App Help unresponsive?

### ISSUE THREAD

**Issue by MonfGeiger** [NiceneNerd/BCML#94]
I finally managed to get the loader working after setting the language to EUen (apparently it doesnt like USen). I managed to get 2 mods "installed", so I went to access the in-app help for further manuals on if what I did with it will show in-game or if I need to do more, but it only shows the following

![error](https://user-images.githubusercontent.com/28603306/102152918-4792f680-3e33-11eb-8dc7-c0cb6c6a7b1e.png)
I'd like to know if this was already mentioned somewhere so I can learn more, or if this is new

**Comment by NiceneNerd** [comment]
It's a glitch with the update package specifically for 3.2.0. I'll be fixing it with the next release. In the meantime, all of the contents of the in-app help are in the [`docs` folder on this repo](https://github.com/NiceneNerd/BCML/tree/master/docs).

**Comment by MonfGeiger** [comment]
ah....alright. Before I (or you) close this ticket, I got one question with this loader and switch mode: Do I need to restore the modified RomFS backups to my atmo setup or whatever to actually use the mods  or do I just boot up BotW and they load in automatically until I uninstall them......or is this post reaching a bit too far

**Comment by NiceneNerd** [comment]
I forgot this was fixed already, closing now
