### ISSUE TITLE
typo in Progress.jsx

### ISSUE THREAD

**Issue by Vegita2** [NiceneNerd/BCML#98]
There is a typo in [bcml/assets/src/js/Progress.jsx](https://github.com/NiceneNerd/BCML/blob/e288f4db4a9e2445bbbfea195fb45f6c52064685/bcml/assets/src/js/Progress.jsx#L74)

"Climbing Death Mountian in the buff"

should be Mountain

**Comment by NiceneNerd** [comment]
Fixed in 772ee781e05cd54a94b90729a986d0e74703261a
